In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import openpyxl
import re
import os
from variableUtils import *
from Utils import *
from ClassUtils import *
from pprint import pprint
import json
from collections import defaultdict
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from reportlab.lib.pagesizes import letter, landscape, A4, A3
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, PageBreak, Paragraph, Spacer, Image
from reportlab.lib import colors
from matplotlib.backends.backend_pdf import PdfPages
from reportlab.platypus import Paragraph, Spacer, KeepTogether, KeepInFrame
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import io
from openpyxl import load_workbook
from openpyxl.styles import PatternFill
from openpyxl.formatting.rule import FormulaRule
import PIL
import ast
from adjustText import adjust_text
warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(sns.__version__)
from datetime import datetime

# get today's date
today = datetime.now().strftime('%d-%m-%Y')
print(f"Today's date: {today}")

0.13.2
Today's date: 10-12-2025

In [13]:
# Load the ebelWeights and ebelMatrix from the saved Excel files
ebelWeightsSavePath = os.path.join('2025', 'ebelWeights.xlsx')
ebelMatrixSavePath = os.path.join('2025', 'ebelMatrix.xlsx')
ebelWeights = pd.read_excel(ebelWeightsSavePath, sheet_name=None)
ebelMatrix = pd.read_excel(ebelMatrixSavePath, sheet_name=None)
importanceWeights = {"essential":5, "important": 3, "non-essential": 1}
def getWeight(row, ebelDf):
    importance = row['Importance']
    difficulty = row['Difficulty']
    return ebelDf.loc[importance, difficulty]


for key, df in ebelWeights.items():
    # if key!= '531':
    #     continue

    df.set_index('MarkingChecklist', inplace=True)
    # change Importance to lowercase
    df['Importance'] = df['Importance'].str.lower()
    df['Difficulty'] = df['Difficulty'].str.lower()
    # strip whitespace from Importance and Difficulty
    df['Importance'] = df['Importance'].str.strip()
    df['Difficulty'] = df['Difficulty'].str.strip()
    # display(df.head())
    if 'scoreWeight' not in df.columns:
        df['scoreWeight'] = df['Importance'].map(importanceWeights)

    # ebel cutoffs
    if key not in ebelMatrix.keys():
        print(f"Key {key} not found in ebelMatrix")
        continue
    ebelDf = ebelMatrix[key].set_index('Importance')
    # change index to lowercase
    ebelDf.index = ebelDf.index.str.lower()
    # change columns to lowercase
    ebelDf.columns = ebelDf.columns.str.lower()
    df['ebelWeight'] = df.apply(getWeight, axis=1, ebelDf=ebelDf)
    ebelSum = df['ebelWeight'].sum()
    ebelCutoff = ebelSum /len(df)
    ebelWeightedSum = df['ebelWeight'] * df['scoreWeight']
    ebelWeightedSum = ebelWeightedSum.sum()
    ebelWeightedCutoff = ebelWeightedSum / df['scoreWeight'].sum()
    # if key!= '524':
        # continue
    print(f"========================\nKey: {key}")
    # display(df.head())
    print(f"EBEL Cutoff: {round(ebelCutoff,2)}")
    # print(f"EBEL Weighted Sum: {ebelWeightedSum.sum()}| {df['scoreWeight'].sum()}")
    print(f"EBEL Weighted Cutoff: {round(ebelWeightedCutoff,2)}")

========================
Key: 521
EBEL Cutoff: 74.29
EBEL Weighted Cutoff: 74.5
========================
Key: 522
EBEL Cutoff: 74.41
EBEL Weighted Cutoff: 74.59
========================
Key: 523
EBEL Cutoff: 74.41
EBEL Weighted Cutoff: 74.59
========================
Key: 524
EBEL Cutoff: 74.41
EBEL Weighted Cutoff: 74.59
========================
Key: 532
EBEL Cutoff: 62.65
EBEL Weighted Cutoff: 65.0
========================
Key: 533
EBEL Cutoff: 52.94
EBEL Weighted Cutoff: 54.06
========================
Key: 534
EBEL Cutoff: 52.94
EBEL Weighted Cutoff: 54.06
========================
Key: 577
EBEL Cutoff: 30.0
EBEL Weighted Cutoff: 30.0
========================
Key: 577-2
EBEL Cutoff: 30.0
EBEL Weighted Cutoff: 30.0
========================
Key: 578
EBEL Cutoff: 41.0
EBEL Weighted Cutoff: 42.37
========================
Key: 531
EBEL Cutoff: 77.5
EBEL Weighted Cutoff: 79.91
========================
Key: IC-BOH
EBEL Cutoff: 84.44
EBEL Weighted Cutoff: 86.97
========================
Key: DDI-DDS
EBEL Cutoff: 70.0
EBEL Weighted Cutoff: 95.68
========================
Key: SOR-DDS
EBEL Cutoff: 50.0
EBEL Weighted Cutoff: 91.53
========================
Key: SOP-DDS
EBEL Cutoff: 87.5
EBEL Weighted Cutoff: 96.08
========================
Key: MAR-31-DDS
EBEL Cutoff: 49.62
EBEL Weighted Cutoff: 50.55
========================
Key: DDS2-MAR-31
EBEL Cutoff: 49.62
EBEL Weighted Cutoff: 50.55
========================
Key: FS-DDS
EBEL Cutoff: 100.0
EBEL Weighted Cutoff: 100.0
========================
Key: 011
EBEL Cutoff: 48.89
EBEL Weighted Cutoff: 52.63
========================
Key: 012
EBEL Cutoff: 48.89
EBEL Weighted Cutoff: 52.63
========================
Key: 013
EBEL Cutoff: 20.0
EBEL Weighted Cutoff: 20.53
========================
Key: 022
EBEL Cutoff: 68.75
EBEL Weighted Cutoff: 71.84
========================
Key: 111
EBEL Cutoff: 84.17
EBEL Weighted Cutoff: 88.75
========================
Key: 141
EBEL Cutoff: 50.0
EBEL Weighted Cutoff: 50.0
========================
Key: 161
EBEL Cutoff: 82.0
EBEL Weighted Cutoff: 82.0
========================
Key: FSE-BOH
EBEL Cutoff: 68.75
EBEL Weighted Cutoff: 74.23
========================
Key: PDP-BOH
EBEL Cutoff: 70.5
EBEL Weighted Cutoff: 69.89
========================
Key: 221
EBEL Cutoff: 70.0
EBEL Weighted Cutoff: 70.0
========================
Key: 221-BOH
EBEL Cutoff: 70.0
EBEL Weighted Cutoff: 70.0
========================
Key: 222
EBEL Cutoff: 76.07
EBEL Weighted Cutoff: 76.7
========================
Key: 513
EBEL Cutoff: 56.84
EBEL Weighted Cutoff: 57.14
========================
Key: 514
EBEL Cutoff: 56.84
EBEL Weighted Cutoff: 57.14
========================
Key: CAA-DDS
EBEL Cutoff: 56.4
EBEL Weighted Cutoff: 57.62
========================
Key: 411
EBEL Cutoff: 82.0
EBEL Weighted Cutoff: 81.3
========================
Key: 114-hs
EBEL Cutoff: 77.0
EBEL Weighted Cutoff: 80.0
========================
Key: 11-12
EBEL Cutoff: 80.0
EBEL Weighted Cutoff: 80.62
========================
Key: OS
EBEL Cutoff: 75.71
EBEL Weighted Cutoff: 76.88
========================
Key: OS-DDS
EBEL Cutoff: 75.71
EBEL Weighted Cutoff: 76.88
Key OM-DDS not found in ebelMatrix
========================
Key: DDS2-2025-S01
EBEL Cutoff: 72.73
EBEL Weighted Cutoff: 73.58
========================
Key: DDS2-2025-S04
EBEL Cutoff: 71.79
EBEL Weighted Cutoff: 75.65
========================
Key: DDS2-2025-S05
EBEL Cutoff: 61.88
EBEL Weighted Cutoff: 61.88
========================
Key: DDS2-2025-S07
EBEL Cutoff: 67.27
EBEL Weighted Cutoff: 67.44
========================
Key: DDS2-2025-S09
EBEL Cutoff: 59.32
EBEL Weighted Cutoff: 60.05
========================
Key: DDS2-2025-S11
EBEL Cutoff: 72.63
EBEL Weighted Cutoff: 73.15
========================
Key: DDS2-2025-S12
EBEL Cutoff: 42.33
EBEL Weighted Cutoff: 44.12
========================
Key: DDS2-2025-S14
EBEL Cutoff: 82.73
EBEL Weighted Cutoff: 83.21
========================
Key: DDS2-2025-S15-1
EBEL Cutoff: 36.25
EBEL Weighted Cutoff: 38.21
========================
Key: DDS2-2025-S15-2
EBEL Cutoff: 36.25
EBEL Weighted Cutoff: 38.21
========================
Key: DDS2-2025-S15-3
EBEL Cutoff: 36.25
EBEL Weighted Cutoff: 38.21
========================
Key: BOH3-Examiner-2
EBEL Cutoff: 53.97
EBEL Weighted Cutoff: 61.47
========================
Key: DDS2-Endo
EBEL Cutoff: 50.62
EBEL Weighted Cutoff: 50.62
========================
Key: BOH2-Viva
EBEL Cutoff: 56.18
EBEL Weighted Cutoff: 60.56
========================
Key: BOH1_SUP1
EBEL Cutoff: 74.21
EBEL Weighted Cutoff: 75.8
========================
Key: BOH1_SUP2
EBEL Cutoff: 64.36
EBEL Weighted Cutoff: 64.61
========================
Key: BOH1_SUP3
EBEL Cutoff: 76.36
EBEL Weighted Cutoff: 76.08
========================
Key: BOH1_SUP5
EBEL Cutoff: 78.67
EBEL Weighted Cutoff: 78.16
========================
Key: BOH1_SUP6
EBEL Cutoff: 75.31
EBEL Weighted Cutoff: 75.39
========================
Key: BOH2_S1
EBEL Cutoff: 64.06
EBEL Weighted Cutoff: 69.17
========================
Key: BOH2_S2
EBEL Cutoff: 60.0
EBEL Weighted Cutoff: 69.49
========================
Key: BOH2_S3
EBEL Cutoff: 79.13
EBEL Weighted Cutoff: 79.1
========================
Key: BOH2_S4
EBEL Cutoff: 70.53
EBEL Weighted Cutoff: 71.97
========================
Key: BOH2_S5
EBEL Cutoff: 77.37
EBEL Weighted Cutoff: 78.31
========================
Key: BOH2_S6
EBEL Cutoff: 75.45
EBEL Weighted Cutoff: 78.33

### Json to excel sheet

In [ ]:
# jsonfilepath = '2025\BOH2\Form 1\\boh2.json'
# jsonfilepath = '2025\DDS2\\dds2.json'
jsonfilepath = '2025\DDS1\dds1.json'
# jsonfilepath = '2025\\all_data.json'
# jsonfilepath = '2025\\BOH1\\boh1.json'
# jsonfilepath = '2025\mini CEX\data.json'
# jsonfilepath = '2025/mini CEX/BOH1/boh1.json'
# jsonfilepath = '2025/mini CEX/DDS2/dds2.json'
# jsonfilepath = '2025\OSCE\BOH1\data.json'
folder, file, ext = getFolderandFileName(jsonfilepath)
with open(jsonfilepath, encoding='utf-8') as f:
    data = json.load(f)
# display(data)
print(json.dumps(data, indent=4))

In [ ]:
# Fields to pull out from supervisor_data
supervisorMainFields = ['time_mgmt', 'entrustment', 'communication', 'professionalism', 'assessor_feedback', 
                        'clinical_incident', 'patient_complexity']
# Field to pull out from student_data
studentMainFields = ['student_feedback']
def getStudentList(listpath, cohort='BOH3'):
    listdf = pd.read_excel(listpath, keep_default_na=False, na_values=[''])
    if cohort is not None:
        listdf = listdf[listdf['Cohort'] == cohort]
    validIds = listdf['Student ID'].to_list()
    # convert to int
    validIds = [int(id) for id in validIds]
    print(f"Number of valid student IDs in {cohort}: {len(validIds)}")
    return validIds
validIds = getStudentList('2025\RE_ Student List.xlsx', cohort=None)

def jsonToExcel(data, supervisorMainFields, studentMainFields, folder, outputFile):
    flattenedEntries = []
    nestedEntries = []
    dataDict_flat = {}
    for entry in data["result"]:
        date = entry.get("date")
        # print("Student Id:", entry.get('student_number'))
        # if entry.get('student_number') not in validIds:
        #     print(f"Skipping entry with student_id {entry.get('student_number')} {entry.get('student_name')} as it is not in the valid IDs list.")
        #     continue
        # Base fields
        baseData = {k: v for k, v in entry.items() if not isinstance(v, dict)}
        
        # Supervisor fields
        supervisorData = entry.get('supervisor_data', {})
        supervisorFieldsExtracted = {k: supervisorData.get(k) for k in supervisorMainFields}
        supervisorRemainingData = {k: v for k, v in supervisorData.items() if k not in supervisorMainFields}
        
        # Student fields
        studentData = entry.get('student_data', {})
        studentFieldsExtracted = {k: studentData.get(k) for k in studentMainFields}
        studentRemainingData = {k: v for k, v in studentData.items() if k not in studentMainFields}
        
        # Fully flattened (all keys)
        flattenedEntry = {**baseData, **studentData, **supervisorData}
        if date not in dataDict_flat:
            dataDict_flat[date] = []
        dataDict_flat[date].append(flattenedEntry)
        flattenedEntries.append(flattenedEntry)

        # Nested version
        nestedEntry = {
            **baseData,
            **supervisorFieldsExtracted,
            **studentFieldsExtracted,
            'student_data': json.dumps(studentRemainingData, indent=2, ensure_ascii=False),
            'supervisor_data': json.dumps(supervisorRemainingData, indent=2, ensure_ascii=False)
        }
        nestedEntries.append(nestedEntry)

    with pd.ExcelWriter(outputFile, engine='openpyxl') as writer:
        # Save flattened data
        for date, records in dataDict_flat.items():
            safeSheetName = str(date).replace('/', '-').replace('\\', '-').replace('*', '').replace('[', '').replace(']', '')[:31]
            df = pd.DataFrame(records)
            df.to_excel(writer, sheet_name=f'{safeSheetName}', index=False)

        # Save flattened all_data
        df_all_flat = pd.DataFrame(flattenedEntries)
        df_all_flat.to_excel(writer, sheet_name='all_data_flat', index=False)

        # Save nested all_data
        df_all_nested = pd.DataFrame(nestedEntries)
        df_all_nested.to_excel(writer, sheet_name='all_data_nested', index=False)

jsonToExcel(data, supervisorMainFields, studentMainFields, folder, os.path.join(folder, 'all_data_combined.xlsx'))

### Define variables

In [3]:
workbookpath = '2025\BOH2\\all_data_combined.xlsx'
# workbookpath = '2025\BOH2\Smile Squad\\all data scores_combined.xlsx'
# workbookpath = '2025\BOH1\\all_data_combined.xlsx'
# workbookpath = '2025\mini CEX\\BOH1\\all_data_combined.xlsx'
# workbookpath = '2025\mini CEX\\DDS2\\all_data_combined.xlsx'
# workbookpath = '2025\mini CEX\\all_data_combined.xlsx'
# workbookpath = '2025\DDS2\\all_data_combined.xlsx'
# workbookpath = '2025\DDS1\\all_data_combined.xlsx'
# workbookpath = '2025\OSCE\BOH1\\all_data_combined.xlsx'
folder, file, ext = getFolderandFileName(workbookpath)

# define variable names
colId = 'Student ID'
colName = 'Student Name'
colDate = 'Date'
colCI = 'CI'
colTS = 'TS'
colES = 'ES'
colCS = 'CS'
colPS = 'PS'
colClinicType = 'clinic'
colAssessorName = 'Assessor Name'
colAssessorFeedback = 'Assessor Feedback'
colStudentFeedback = 'Student Feedback'
colPatientComplexity = 'Patient Complexity'
colAssessorSubmitted = 'submitted_by_assessor'
colStudentSubmitted = 'submitted_by_student'
colPatientDetails = 'patient_details'
colRole = 'role'

colSubject = 'subject'
# display(df.head())
# drop na Student ID

commonList = [
    'assessment_id', colName, colId, colAssessorName, colDate,
    'cohort', 'subject', 'type', 'student_submitted', 'assessor_submitted',
    colTS, colES, colCS, colPS,
    colAssessorFeedback, colCI, colPatientComplexity, colStudentFeedback
]

beforeCols = ['assessment_id', colName, colId,  colDate, colAssessorName, 'cohort', 'subject', 'type', colPatientComplexity,
              colClinicType]
rubricCols = [colTS, colES, colCS, colPS]
feedbackCols = [colCI, colAssessorFeedback, colStudentFeedback]

replaceNotReviwedwithNo = False

headingStyleLarge = ParagraphStyle('Heading1', parent=styles['Heading1'], fontSize=72, alignment=1)  # Centered

# get weights of marking checklist and rubrics
weightPS = 0.05
weightTS = 0.025
weightES = 0.15
weightCS = 0.0
weightMC = round(1 - weightPS - weightTS - weightES - weightCS, 3)
print(f"Weight of PS: {weightPS}, TS: {weightTS}, ES: {weightES}, CS: {weightCS}, MC: {weightMC}")

Weight of PS: 0.05, TS: 0.025, ES: 0.15, CS: 0.0, MC: 0.775

### Create student performance time series and other reports

In [ ]:
df = pd.read_excel(workbookpath, sheet_name='all_data_nested')
flatDf = pd.read_excel(workbookpath, sheet_name='all_data_flat')
df.rename(columns={'student_number':colId, 'student_name': colName, 'date': colDate,
                   'time_mgmt': colTS, 'entrustment': colES, 'communication': colCS, 'professionalism': colPS, 
                   'clinical_incident': 'CI', 'patient_complexity': 'Patient Complexity', 'assessor_name': colAssessorName,
                   'assessor_feedback': colAssessorFeedback}, inplace=True)
df.dropna(subset=[colId], inplace=True)
df[colId] = df[colId].astype(int)
df[colTS] = df[colTS].astype('Int64')
df[colES] = df[colES].astype('Int64')
df[colCS] = df[colCS].astype('Int64')
df[colPS] = df[colPS].astype('Int64')
df[colPatientComplexity] = df[colPatientComplexity].fillna('')
df[colPatientComplexity] = df[colPatientComplexity].astype(str)
df[colCI] = df[colCI].fillna('')
display(df.head())

In [4]:
from matplotlib.lines import Line2D
def extractCodes(supervisorDataStr):
    try:
        data = json.loads(supervisorDataStr)
        codes = set()
        for key in data.keys():
            if 'MC' in key  and 'positioning' not in key and 'Consent' not in key and 'Record' not in key and 'infection' not in key:
                code = key.split('_')[1]
                codes.add(code)
        return sorted(codes)
    except Exception:
        return []
    
# Expand the JSON with scores having two levels of keys
def expandJson(row):
    jsonDict = json.loads(row)
    flatDict = {}
    for outerKey, innerDict in jsonDict.items():
        for innerKey, value in innerDict.items():
            flatDict[f'{outerKey}_{innerKey}'] = value
    return pd.Series(flatDict)

def flattenJson(jsonData):
    flatDict = {}
    for outerKey, innerDict in jsonData.items():
        if isinstance(innerDict, dict):
            for innerKey, value in innerDict.items():
                flatDict[f'{outerKey}_{innerKey}'] = value
        else:
            flatDict[outerKey] = innerDict
    return flatDict
# get row wise scores for each item code
def getRowWiseScores(df):
    # check if supervisor_data is a string and convert to json
    # if isinstance(df['supervisor_data'].iloc[0], str):
    #     # print("Converting supervisor_data to JSON")
    #     # convert to json
    #     df['supervisor_data'] = df['supervisor_data'].apply(lambda x: json.loads(x))
        # convert to json
    df['supervisor_data'] = df['supervisor_data'].apply(lambda x: json.loads(x))
    scoresList = []

    for idx, row in df.iterrows():    
        print(f"Row: {idx}")
        jsonData = pd.json_normalize(row['supervisor_data'])
        if replaceNotReviwedwithNo:
            jsonData.replace({'Not Reviewed': 'No'}, inplace=True)
        jsonData.replace({'Not Reviewed': 'NA', 'Not Assessed': 'NA'}, inplace=True)
        itemList = row['Item Codes']
        scoreDict = {}
        # print(f'Item Codes: {itemList}')
        for item in itemList:
            # print(f'Item Code: {item}')
            scoreDict[item] = {}
            mcCols = [key for key in row['supervisor_data'].keys() if f'{item}_MC' in key]
            itemDf = jsonData[mcCols]
            # display(itemDf.head())
            itemDf.columns = [col.split('_')[2] for col in itemDf.columns]
            # display(itemDf.head())
            # rename hte columns to MC\d+ extract
            itemYes = int(itemDf[itemDf == 'Yes'].count(axis=1).sum())
            itemNo = int(itemDf[itemDf == 'No'].count(axis=1).sum())
            itemNA = int(itemDf[itemDf == 'NA'].count(axis=1).sum())
            scoreDict[item]['Yes'] = itemYes
            scoreDict[item]['No']   = itemNo
            scoreDict[item]['NA'] = itemNA
            if itemYes + itemNo > 0:
                scoreDict[item]['% Yes'] = round((itemYes / (itemYes + itemNo) * 100), 2)
            else:
                scoreDict[item]['% Yes'] = np.nan

            # get the ebel cutoffs for the item code
            if item in ebelWeights.keys():
                weightDf = ebelWeights[item]
                # use only MC items that  are not NA
                notNA = itemDf[itemDf != 'NA']
                notNA = notNA.dropna(axis=1, how='all')
                if notNA.empty:
                    print(f'Item Code: {item} has no data')
                    continue
                # display(notNA.head())
                cutoff = 0
                weightedCutoff = 0
                weightedSum = 0
                denominator = 0
                # display(weightDf)
                for col in notNA.columns:
                    # print(cutoff, weightedCutoff, weightedSum, denominator)
                    try:
                        cutoff += weightDf.loc[col, 'ebelWeight']
                        weightedCutoff += weightDf.loc[col, 'ebelWeight'] * weightDf.loc[col, 'scoreWeight']
                        if notNA.loc[0, col] == 'Yes':
                            weightedSum += weightDf.loc[col, 'scoreWeight']
                        denominator += weightDf.loc[col, 'scoreWeight']
                    except KeyError:
                        print(f"KeyError: {item} {col} not found in weightDf")
                        continue
                # print(f'Cutoff: {cutoff}, Weighted Cutoff: {weightedCutoff}, Weighted Sum: {weightedSum}, Denominator: {denominator}')
                cutoff = cutoff / len(notNA.columns)
                try:
                    weightedCutoff = weightedCutoff / denominator
                    weightedScore = round((weightedSum / denominator * 100), 2)
                except ZeroDivisionError:
                    print(f"ZeroDivisionError: Denominator is zero for item {item} with data: {scoreDict[item]}, student data: {row[colId]}")
                    weightedCutoff = np.nan
                    weightedScore = np.nan
                
                # CS TS ES PS  all should become 0 if no value is present
                row[colTS] = row[colTS] if pd.notna(row[colTS]) else 0
                row[colES] = row[colES] if pd.notna(row[colES]) else 0
                row[colCS] = row[colCS] if pd.notna(row[colCS]) else 0
                row[colPS] = row[colPS] if pd.notna(row[colPS]) else 0

                totalScore = weightMC * weightedScore + (weightTS * row[colTS]/4 + weightES * row[colES]/4 + weightPS * row[colPS]/2 + weightCS * row.get(colCS,0)/2)*100
                # get dtype of each item in the above expression

                # print(f'Cutoff: {cutoff}, Weighted Cutoff: {weightedCutoff}, Weighted Sum: {weightedSum}, Denominator: {denominator}')
                try:
                    scoreDict[item] = scoreDict[item] | {'Cutoff': round(cutoff,2), 'Weighted Cutoff': round(weightedCutoff,2), 'Weighted Sum': int(weightedSum), 'Denominator': int(denominator),
                                                     'Weighted Score': weightedScore, 'Total Score': round(totalScore, 2)}
                except TypeError:
                    print(f"Error in item {item} with data: {scoreDict[item]}, student data: {row[colId]}")
                    print(cutoff, weightedCutoff, weightedSum, denominator, weightedScore, totalScore)
                    display(notNA.head())
        # pprint(scoreDict)        
        scoresList.append(json.dumps(scoreDict))
    df['Scores'] = scoresList
    df['supervisor_data'] = df['supervisor_data'].apply(lambda x: json.dumps(x, indent=2, ensure_ascii=False))

def getSeparatedItemDf(df):
    dfDict = {}
    # check if item codes is a string and convert to list
    df['Item Codes'] = df['Item Codes'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
    itemCodes = df['Item Codes'].sum()

    itemCodes = list(set(itemCodes))
    for item in itemCodes:
        # print(f'Item Code: {item}')
        # itemDf.set_index('assessment_id', inplace=True)
        itemDf = df[df['Item Codes'].apply(lambda x: item in x)] # select rows where item is in Item Codes
        if isinstance(itemDf['supervisor_data'].iloc[0], str):
            # print("Converting supervisor_data to JSON")
            # convert to json
            itemDf['supervisor_data'] = itemDf['supervisor_data'].apply(lambda x: json.loads(x))
            itemDf['supervisor_data'] = itemDf['supervisor_data'].apply(flattenJson)
        supervisorDataDf= itemDf['supervisor_data'].apply(pd.Series)
        if replaceNotReviwedwithNo:
            supervisorDataDf.replace({'Not Reviewed': 'No'}, inplace=True)
        supervisorDataDf.replace({'Not Reviewed': 'NA', 'Not Assessed': 'NA'}, inplace=True)
        # display(itemDf.head())
        # display(supervisorDataDf.head())
        # only take columns have item code in them
        # display(supervisorDataDf.head())
        validCols = [col for col in supervisorDataDf.columns if f'{item}_MC' in col]
        supervisorDataDf = supervisorDataDf[validCols]
        # rename columns to remove assessor_ text
        supervisorDataDf.columns = [col.split('assessor_')[-1] for col in supervisorDataDf.columns]

        # Step 1: Convert Yes/No to 1/0
        supervisordataDfBinary = supervisorDataDf.replace({'Yes': 1, 'No': 0, 'NA': np.nan})
        # display(supervisordataDfBinary.head())
        # Step 2: Calculate column scores
        columnScores = supervisordataDfBinary.sum(axis=0)

        # Step 3: Sort columns based on score (descending)
        sortedColumns = columnScores.sort_values(ascending=False).index
        sortedColumns = supervisorDataDf.columns # unsort the columns
        # Step 4: Reorder dataframe columns
        sortedSupervisorDataDf = supervisorDataDf[sortedColumns]
        sortedSupervisorDataDf = sortedSupervisorDataDf.replace({'Yes': 1, 'No': 0})
        # remove item_ from column names
        sortedSupervisorDataDf.columns = [col.split(f'{item}_')[-1] for col in sortedSupervisorDataDf.columns]
        # display(sortedSupervisorDataDf.head())
        # display(supervisorDataDf.head())
        thiscommonList = [col for col in itemDf.columns if col in commonList]
        thisbeforeCols = [col for col in beforeCols if col in itemDf.columns]
        combinedDf= pd.concat([itemDf[thisbeforeCols], sortedSupervisorDataDf, itemDf[rubricCols]], axis=1)
        # display(combinedDf.head())
        expandedScores = itemDf['Scores'].apply(expandJson)
        validCols2 = [col for col in expandedScores.columns if item in col]
        expandedScores = expandedScores[validCols2]
        # rename columns to remove item_ text
        expandedScores.columns = [col.split(f'{item}_')[-1] for col in expandedScores.columns]
        # display(expandedScores.head())
        combinedDf = pd.concat([combinedDf, expandedScores], axis=1)
        combinedDf = pd.concat([combinedDf, itemDf[feedbackCols]], axis=1)
        display(combinedDf.head())
        for dateVal, subDf in itemDf.groupby(colDate):
            dateStr = pd.to_datetime(dateVal).strftime('%Y-%m-%d')
            combinedDf = pd.concat([
                subDf[thisbeforeCols],
                sortedSupervisorDataDf.loc[subDf.index],
                subDf[rubricCols],
                expandedScores.loc[subDf.index],
                subDf[feedbackCols],
            ], axis=1)

            dfDict[f'{item} ({dateStr})'] = combinedDf

        # # group by week and combine
        # itemDf[colDate] = pd.to_datetime(itemDf[colDate])
        # itemDf['weekStart'] = itemDf[colDate].dt.to_period('W-MON').apply(lambda r: r.start_time)

        # for weekVal, subDf in itemDf.groupby('weekStart'):
        #     dateStr = pd.to_datetime(weekVal).strftime('%Y-%m-%d')
        #     combinedDf = pd.concat([
        #         subDf[thisbeforeCols],
        #         sortedSupervisorDataDf.loc[subDf.index],
        #         subDf[rubricCols],
        #         expandedScores.loc[subDf.index],
        #         subDf[feedbackCols],
        #     ], axis=1)

        #     dfDict[f'{item} ({dateStr})'] = combinedDf
        # dfDict[item] = combinedDf
    
    return dfDict
def getColor(row):
    if row['NA_Flag']:
        return 'gray'
    elif row[colPatientComplexity] == 'complex':
        return 'red'
    else:
        return 'blue'
def plotStudentScoresTimeSeries(df, 
                      dateCol='Date', 
                      scoreDictCol='assessor_scores_dict', 
                      scoreKey='% Yes', 
                      fallbackKey=None,
                      title='Student Performance Over Time',
                      pageSize=variableUtils.pageSize):
    """
    Creates and returns a scatter plot of scores over time with fallback keys.

    Args:
        df (pd.DataFrame): DataFrame with date and score dict columns.
        dateCol (str): Column name for date.
        scoreDictCol (str): Column with assessor score dictionaries.
        scoreKey (str): Primary key to extract.
        fallbackKeys (list of str): List of fallback keys to use if primary key missing.
        title (str): Title of the plot.

    Returns:
        matplotlib.figure.Figure: The generated figure object.
    """

    # df[dateCol] = pd.to_datetime(df[dateCol])
    pecCodes = ['Consent', 'Record_keeping', 'infection_control', 'positioning'] + ['Record keeping', 'Positioning', 'Infection control']

    expandedRows = []
    for _, row in df.iterrows():
        if not isinstance(row[scoreDictCol], dict):
            continue
        complexity = row.get(colPatientComplexity, 'non-complex')
        for itemCode, scoreDict in row[scoreDictCol].items():
            naFlag = False
            if itemCode in pecCodes:
                print(f"Skipping PEC item code: {itemCode}")
                continue
            score = scoreDict.get(scoreKey)
            print(f"Item: {itemCode}, ScoreDict: {scoreDict}, Primary Score ({scoreKey}): {score}")
            if score is None or pd.isna(score):
                if fallbackKey is not None:
                    score = scoreDict.get(fallbackKey)
                    print(f"Item: {itemCode}, ScoreDict: {scoreDict}, Fallback Score ({fallbackKey}): {score}")
                if pd.isna(score):
                    score = -5
                    naFlag = True
            if score is not None:
                expandedRows.append({
                    'Date': row[dateCol],
                    'Item': itemCode,
                    'Score': score,
                    colAssessorName: row[colAssessorName],
                    'NA_Flag': naFlag,
                    colPatientComplexity: complexity
                })

    expandedDf = pd.DataFrame(expandedRows)
    expandedDf['Color'] = expandedDf.apply(getColor, axis=1)
    # naDf = expandedDf[expandedDf['NA_Flag']]
    # validDf = expandedDf[~expandedDf['NA_Flag']]

    if expandedDf.empty:
        print(f"No valid data for '{scoreKey}' or fallbacks {fallbackKey}.")
        return None

    # Plot
    fig, ax = plt.subplots(figsize=(14, 8))
    ax.scatter(expandedDf['Date'], expandedDf['Score'], color=expandedDf['Color'], label='Scores')
    # if not naDf.empty:
    #     ax.scatter(naDf['Date'], naDf['Score'], color='gray', label='All NA scores')
    #     ax.legend()

    # display(expandedDf)
    offsetCounter = defaultdict(int)
    for _, row in expandedDf.iterrows():
        key = (row['Date'], row['Score'])
        offset = offsetCounter[key] * 5
        offsetCounter[key] += 1
        ax.annotate(f"{row['Item']}",# ({row[colAssessorName]})",
                    (row['Date'], row['Score']),
                    textcoords="offset points", xytext=(0, 5 + 2*offset),
                    ha='center', fontsize=7)
        # ax.annotate(f"{row['assessor_name']}",
        #             (row['Date'], row['Score']),
        #             textcoords="offset points", xytext=(0, -10 - 2*offset),
        #             ha='center', fontsize=6)

    ax.set_title(title)
    ax.set_xlabel("Date")
    ax.set_ylabel("Score (% Yes or Weighted)")
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.tick_params(axis='x', rotation=45)
    ax.set_ylim(-10, 1.2*expandedDf['Score'].max())
    ax.set_yticks(range(0, int(expandedDf['Score'].max() + 1), int(max(expandedDf['Score'].max()//10, 1))))
    legendElems = [
    Line2D([0], [0], marker='o', color='w', label='Complex', markerfacecolor='red', markersize=8),
    Line2D([0], [0], marker='o', color='w', label='All NA', markerfacecolor='gray', markersize=8),
    # Line2D([0], [0], marker='o', color='w', label='Valid', markerfacecolor='blue', markersize=8),
    ]
    ax.legend(handles=legendElems, bbox_to_anchor=(0.85, 1.1), loc='upper left')
    fig.tight_layout()

    return fig

def rubricPlot(ax, studentDf, label, color, xLabelRotation=45):
    studentDf.dropna(subset=[label], inplace=True)
    if studentDf.empty:
        ax.text(0.5, 0.5, 'No data available', horizontalalignment='center', verticalalignment='center', transform=ax.transAxes)
        return
    ax.plot(studentDf[colDate], studentDf[label], label=label, color=color, marker='o')
    ax.set_title(label)
    ax.set_xlabel('Date')
    ax.set_ylim(0, studentDf[label].max() + 0.5)
    # reduce size of x labels
    ax.set_xticklabels(ax.get_xticklabels(), rotation=xLabelRotation, fontsize=8)
    ax.tick_params(axis='x', rotation=xLabelRotation)
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.set_yticks(range(0, int(studentDf[label].max()+1), 1))
    ax.set_yticklabels(range(0, int(studentDf[label].max()+1), 1))


def createTimeSeriesReport(df, scoreKey, pageSize=variableUtils.pageSize):
    elements = []
    i=0
    df.sort_values(by=[colName], inplace=True)
    for id in df[colId].unique():
        print(f"Processing student ID: {id}")
        i+=1
        studentDf = df[df[colId] == id]
        # studentDf = studentDf[(studentDf[colAssessorSubmitted]== True) | (studentDf[colAssessorSubmitted] == '1') | (studentDf[colAssessorSubmitted] == 1)| 
        #                       (studentDf[colAssessorSubmitted] == 'True') | (studentDf[colAssessorSubmitted] == 'TRUE')]
        if studentDf.empty:
            continue
        # display(studentDf)
        name = studentDf[colName].values[0]
        studentDf[colDate] = pd.to_datetime(studentDf[colDate], format= 'mixed')
        studentDf.sort_values(by=colDate, inplace=True)
        studentDf[colDate] = studentDf[colDate].dt.strftime('%d/%m')
        # display(studentDf.head())
        
        # create 4 ubplots of time series of time mgmt, professionalism, communication, entrustment
        # Set variables
        xLabelRotation = 45
        forceIntegerYTicks = True

        fig, axs = plt.subplots(4, 1, figsize=(14, 12))  # 4 rows, 1 column
        # fig.suptitle(f'colId: {id}')
        if axs.ndim > 1:
            axs = axs.flatten()
        # Define plots
        plotConfigs = [
            (3, colTS, 'blue'),
            (1, colPS, 'green'),
            (2, colCS, 'orange'),
            (0, colES, 'red')
        ]
        try:
            for idx, label, color in plotConfigs:
                ax = axs[idx]
                rubricPlot(ax, studentDf, label, color, xLabelRotation)
                # if forceIntegerYTicks:
                #     ax.yaxis.get_major_locator().set_params(integer=True)

            plt.tight_layout(rect=[0, 0, 1, 0.95])
            imgrubric = addPlotImage(fig, 0.9, pageSize)
        except Exception as e:
            print(f"Error in plotting: {e}")
            # display(studentDf)
            imgrubric = None
        # create a table of the scores for each item code
        
        elements.append(Paragraph(f'{name} ({id})', subheadingStyle))
        elements.append(Spacer(1, 12))

        figScoreSeries = plotStudentScoresTimeSeries(studentDf, dateCol=colDate, scoreDictCol='Scores', title=f'Student ID: {int(id)}',
                                                      scoreKey=scoreKey, fallbackKey='% Yes', pageSize=pageSize)
        if figScoreSeries is not None:
            imgMC = addPlotImage(figScoreSeries, 0.9, pageSize=pageSize)
            elements.append(imgMC)
            elements.append(Spacer(1, 12))

        elements.append(imgrubric)

        # now I want role counts and colPatientDetails counts
        roleCounts = studentDf[colRole].value_counts()
        # convert series to dataframe
        roleCounts = roleCounts.reset_index()
        roleCounts.columns = [colRole, 'Count']
        colPatientDetailsCounts = studentDf[colPatientDetails].value_counts()
        colPatientDetailsCounts = colPatientDetailsCounts.reset_index()
        if not (colPatientDetailsCounts.empty and roleCounts.empty):
            colPatientDetailsCounts.columns = ['Patient Attended', 'Count']
            # display(roleCounts)
            # display(colPatientDetailsCounts)
            roleCountsDict = roleCounts.set_index(colRole).to_dict()['Count']
            patientDetailsDict = colPatientDetailsCounts.set_index('Patient Attended').to_dict()['Count']
            # print(f"Role Counts Dict: {roleCountsDict}")
            # print(f"Patient Details Dict: {patientDetailsDict}")
            # Show as text
            roleCountsText = '<br/> '.join([f"<b>{role}:</b> {count}" for role, count in roleCountsDict.items()])
            patientDetailsText = '<br/> '.join([f"<b>{detail}:</b> {count}" for detail, count in patientDetailsDict.items()])
            roleCountsElement = Paragraph(f'{roleCountsText}', tableTextStyleSmall)
            patientDetailsElement = Paragraph(f'{patientDetailsText}', tableTextStyleSmall)
            headerRole = Paragraph("Role Counts", smallsubsubheadingStyleC)
            headerPatient = Paragraph("Patient Attendance", smallsubsubheadingStyleC)

            wrappingTable = Table(
                [
                    [headerRole, headerPatient],
                    [roleCountsElement, patientDetailsElement]
                ],
                colWidths=[0.45*pageSize[0], 0.45*pageSize[0]]
            )
            elements.append(Spacer(1, 12))
            elements.append(wrappingTable)
        # elements.append(roleCountsTable)
        # # elements.append(Spacer(1, 12))
        # elements.append(patientDetailsTable)

        elements.append(PageBreak())
        # if i>3:
        #     break   

    return elements

In [5]:
# item code df grouped by colId and date
def getItemCodeDf(df, colId, colName, colDate):
    itemCodeDf = df.groupby([colId, colDate])['Item Codes'].sum().reset_index()
    itemCodeDf[colName] = itemCodeDf[colId].apply(lambda x: df[df[colId] == x][colName].values[0])
    itemCodeDf = itemCodeDf[[colId, colName, colDate, 'Item Codes']]
    itemCodeDf.sort_values(by=[colName, colDate], inplace=True)
    # display(itemCodeDf.head())
    return itemCodeDf

# get unique number of dates for each student
def getUniqueDates(df, colId, colDate): 
    uniqueDatesDf = df.groupby([colId])[colDate].nunique().reset_index()
    uniqueDatesDf[colName] = uniqueDatesDf[colId].apply(lambda x: df[df[colId] == x][colName].values[0])
    uniqueDatesDf = uniqueDatesDf[[colId, colName, colDate]]
    uniqueDatesDf.rename(columns={colDate: 'Days attented'}, inplace=True)
    uniqueDatesDf.sort_values(by='Days attented', ascending=False, inplace=True)
    # display(uniqueDatesDf.head())
    return uniqueDatesDf

# entrustment level counts for each student
def getLevelCounts(df, colRubric = colES):
    levelCounts = (
        df
        .groupby([colId, colRubric])
        .size()
        .unstack(fill_value=0)  # Make levels into columns, missing levels = 0
    )
    # fill to have all level columns
    levelCounts = levelCounts.reindex(columns=[1, 2, 3, 4], fill_value=0)
    allLevelDict = {1: 'Lvl 1', 2: 'Lvl 2', 3: 'Lvl 3', 4: 'Lvl 4'}

    levelCounts.reset_index(inplace=True)
    levelCounts[colName] = levelCounts[colId].apply(lambda x: df[df[colId] == x][colName].values[0])
    levelCounts = levelCounts[[colId, colName] + list(allLevelDict.keys())]

    levelCounts.rename(columns= allLevelDict, inplace=True)
    levelCounts.sort_values(by=['Lvl 1', 'Lvl 2'], inplace=True, ascending=False)
    # remove columns with all 0 values
    levelCounts = levelCounts.loc[:, (levelCounts != 0).any(axis=0)]
    # display(levelCounts.head())

    overallEntrustmentCounts = df[colRubric].value_counts()
    overallEntrustmentCounts = overallEntrustmentCounts.reset_index()
    overallEntrustmentCounts.rename(columns={'index': colRubric, 0: 'Counts'}, inplace=True)
    return levelCounts, overallEntrustmentCounts

# get critical incident information
def getCriticalIncidents(df):
    # select rows where clinical_incident is not empty pd.na
    ciDf = df[df[colCI].notna()]
    display(ciDf.head())
    ignoreList = ['Nil', 'None', 'No comments', 'No']
    ciDf = ciDf[~ciDf[colCI].astype(str).str.strip().isin(ignoreList)]  
    ciDf = ciDf[ciDf[colCI].astype(str).str.strip() != '']
    ciDf = ciDf[ciDf[colCI] != 'nan']
    # select only the columns we need
    ciDf[colDate] = ciDf[colDate].dt.strftime('%d/%m/%Y')
    ciDf = ciDf[[colId, colName, colDate, colCI]]
    display(ciDf.head())

    # group by colId to get counts
    ciCounts = ciDf.groupby([colId])[colCI].count().reset_index()
    ciCounts[colName] = ciCounts[colId].apply(lambda x: df[df[colId] == x][colName].values[0])
    ciCounts = ciCounts[[colId, colName, colCI]]
    ciCounts.rename(columns={colCI: 'CI Counts'}, inplace=True)
    ciCounts.sort_values(by='CI Counts', ascending=False, inplace=True)
    return ciDf, ciCounts

def getNPatients(df):
    # if patient complexity is not empty
    patientDf = df[df[colPatientComplexity].notna()]
    patientDf = patientDf[patientDf[colPatientComplexity].str.strip() != '']
    print('Patients', len(patientDf))
    # display(patientDf.head())
    # get counts of each student
    patientCounts = patientDf[colId].value_counts()
    patientCounts = patientCounts.reset_index()
    display(patientCounts.head())
    patientCounts.rename(columns={ 'count': 'Patient Counts'}, inplace=True)
    patientCounts[colName] = patientCounts[colId].apply(lambda x: df[df[colId] == x][colName].values[0])
    patientCounts = patientCounts[[colId, colName, 'Patient Counts']]
    patientCounts.sort_values(by='Patient Counts', ascending=False, inplace=True)
    display(patientCounts.head())
    return patientCounts

def getAverageLevels(entrustmentData):
        # Define expected level columns and weights
    levelWeights = {'Lvl 1': 1, 'Lvl 2': 2, 'Lvl 3': 3, 'Lvl 4': 4}

    # Get only available columns from the dataframe
    availableLevels = [col for col in levelWeights if col in entrustmentData.columns]

    # Compute weighted sum and total count
    weightedSum = sum(entrustmentData[col] * levelWeights[col] for col in availableLevels)
    totalCount = entrustmentData[availableLevels].sum(axis=1)

    # Compute average safely (avoiding division by zero)
    entrustmentData['Average'] = weightedSum / totalCount.replace(0, pd.NA)
    entrustmentData['Average'] = entrustmentData['Average'].round(2)

def createData(dfSim, title, filepath=None):
    elements = []
    elements.append(Spacer(1, 104*3))
    elements.append(Paragraph(title, headingStyleLarge))
    elements.append(Spacer(1, 12))
    itemCodeDfSim = getItemCodeDf(dfSim, colId, colName, colDate)
    
    # add table for entrustment level counts
    entrustmentCountsSim, overallCountsSim  = getLevelCounts(dfSim)
    entrustmentCountsTableSim= createTable(entrustmentCountsSim, 'Entrustment Level Counts', colRatio=[1.3, 1.7, 1, 1, 1, 1], customTextCols=[1], bottomPadding=6, topPadding=6)
    elements.append(entrustmentCountsTableSim)
    elements.append(Spacer(1, 32))
    
    # add table for professionalism, communication, time management level counts
    professionalismCountsSim, overallCountsSim = getLevelCounts(dfSim, colRubric=colPS)
    professionalismCountsTableSim = createTable(professionalismCountsSim, 'Professionalism Level Counts', colRatio=[1.3, 1.7, 1, 1, 1, 1], customTextCols=[1], bottomPadding=6, topPadding=6)
    elements.append(professionalismCountsTableSim)
    elements.append(Spacer(1, 32))

    communicationCountsSim, overallCountsSim = getLevelCounts(dfSim, colRubric=colCS)
    communicationCountsTableSim = createTable(communicationCountsSim, 'Communication Level Counts', colRatio=[1.3, 1.7, 1, 1, 1, 1], customTextCols=[1], bottomPadding=6, topPadding=6)
    elements.append(communicationCountsTableSim)
    elements.append(Spacer(1, 32))

    timeMgmtCountsSim, overallCountsSim = getLevelCounts(dfSim, colRubric=colTS)
    timeMgmtCountsTableSim = createTable(timeMgmtCountsSim, 'Time Management Level Counts', colRatio=[1.3, 1.7, 1, 1, 1, 1], customTextCols=[1], bottomPadding=6, topPadding=6)
    elements.append(timeMgmtCountsTableSim)
    elements.append(Spacer(1, 32))
    
    # add table for overall counts
    overallCountsTableSim = createTable(overallCountsSim, 'Overall Entrustment Level Counts', colRatio=[1.3, 1.7], bottomPadding=6, topPadding=6)
    elements.append(overallCountsTableSim)
    elements.append(PageBreak())

    # merge all level counts into one dataframe for display
    studentIDNameDict = dfSim.set_index(colId)[colName].to_dict()
    entrustmentData = entrustmentCountsSim.drop(columns=[colName], errors='ignore')
    # add average column
    getAverageLevels(entrustmentData)
    professionalismData = professionalismCountsSim.drop(columns=[colName], errors='ignore')
    getAverageLevels(professionalismData)
    communicationData = communicationCountsSim.drop(columns=[colName], errors='ignore')
    getAverageLevels(communicationData)
    timeMgmtData = timeMgmtCountsSim.drop(columns=[colName], errors='ignore')
    getAverageLevels(timeMgmtData)
    mergedDf = entrustmentData.merge(professionalismData, on=colId, suffixes=('', '_P')) \
                            .merge(communicationData, on=colId, suffixes=('', '_C')) \
                            .merge(timeMgmtData, on=colId, suffixes=('', '_T'))
    
    # add student name column
    mergedDf[colName] = mergedDf[colId].apply(lambda x: studentIDNameDict.get(x, 'Unknown'))
    # reorder columns to have colId, colName first
    cols = mergedDf.columns.tolist()
    cols.remove(colId)
    cols.remove(colName)
    mergedDf = mergedDf[[colId, colName] + cols]
    idCol = pd.MultiIndex.from_tuples([(colId, ''), (colName, '')])

    # Generate grouped MultiIndex for each rubric
    def makeRubricCols(rubricName, df, excludeCol=colId):
        return [(rubricName, col) for col in df.columns if col != excludeCol]

    multiCols = (
        idCol.tolist() +
        makeRubricCols('Entrustment', entrustmentData) +
        makeRubricCols('Professionalism', professionalismData) +
        makeRubricCols('Communication', communicationData) +
        makeRubricCols('Time Management', timeMgmtData)
    )

    # Assign to DataFrame
    mergedDf.columns = pd.MultiIndex.from_tuples(multiCols)
    display(mergedDf.head())
    kwargs = getmodeArgs(filepath)
    with pd.ExcelWriter(filepath, **kwargs) as writer:
        mergedDf.to_excel(writer, sheet_name=f'Level Counts {title}')
    # add table for critical incidents
    ciDfSim, ciCountsSim = getCriticalIncidents(dfSim)
    ciDfSim.rename(columns={colCI: 'Critical Incident'}, inplace=True)
    ciDfSimTable = createTable(ciDfSim, 'Critical Incidents', colRatio=[1, 1.3, 1, 5], customTextCols=[3, 1, 2], bottomPadding=6, topPadding=6, tableTextStyle=tableTextStyleSmall)
    elements.append(ciDfSimTable)
    elements.append(Spacer(1, 12))
    ciCountsSimTable = createTable(ciCountsSim, 'Critical Incident Counts', colRatio=[1, 1.3, 1.7], bottomPadding=6, topPadding=6)
    elements.append(ciCountsSimTable)
    elements.append(PageBreak())

    # add CI df to excel
    kwargs = getmodeArgs(filepath)
    with pd.ExcelWriter(filepath, **kwargs) as writer:
        ciDfSim.to_excel(writer, sheet_name=f'Critical Incidents {title}', index=False)
        ciCountsSim.to_excel(writer, sheet_name=f'CI Counts {title}', index=False)

    # add table for unique dates
    uniqueDatesDfSim = getUniqueDates(dfSim, colId, colDate)
    # display(uniqueDatesDfSim.head())
    uniqueDatesDfSimTable = createTable(uniqueDatesDfSim, 'Dates Attented', colRatio=[1.3, 1.7, 1], customTextCols=[1, 0], bottomPadding=6, topPadding=6)
    elements.append(uniqueDatesDfSimTable)
    elements.append(PageBreak())

    # get data for number of forms submitted by each student
    nForms = dfSim[colId].value_counts()
    display(nForms.head())
    # use the name mapping to get student names
    nForms = nForms.rename_axis(colId).to_frame('Number of Forms Submitted')
    nForms[colName] = nForms.index.map(studentIDNameDict)
    nForms = nForms.reset_index()
    # nForms.rename(columns={colId: 'Number of Forms', 'index': colId}, inplace=True)
    nForms = nForms[[colId, colName, 'Number of Forms Submitted']]
    kwargs = getmodeArgs(filepath)
    with pd.ExcelWriter(filepath, **kwargs) as writer:
        nForms.to_excel(writer, sheet_name=f'Number of Forms {title}', index=False)
    return elements

# create table for scores
def createScoreTables(df):
    scoreElements = []
    totalDf= pd.DataFrame(columns=[colId, 'Student Name', 'Yes', 'No', 'NA'])
    for id in sorted(df[colId].unique()):
        studentDf = df[df[colId] == id]
        studentName = studentDf[colName].values[0]
        aggItems = {}

        for i, row in studentDf.iterrows():
            scoreDict = row['Scores']
            for item, values in scoreDict.items():
                if item not in aggItems:
                    aggItems[item] = {'Yes': 0, 'No': 0, 'NA': 0}
                aggItems[item]['Yes'] += int(values['Yes'])
                aggItems[item]['No'] += int(values['No'])
                aggItems[item]['NA'] += (values['NA'])
        # display(aggItems)
        try:
            studentScoreDf = pd.DataFrame.from_dict(aggItems, orient='index').reset_index().rename(columns={'index': 'Item Code'})
            # add row for total of each column
            studentScoreDf.loc['Total'] = studentScoreDf.sum(numeric_only=True)
            studentScoreDf.loc['Total', 'Item Code'] = 'Total'
            studentScoreDf['Yes'] = studentScoreDf['Yes'].astype(int)
            studentScoreDf['No'] = studentScoreDf['No'].astype(int)
            studentScoreDf['NA'] = studentScoreDf['NA'].astype(int)
            try:
                studentScoreDf['% Yes'] = ((studentScoreDf['Yes'] / (studentScoreDf['Yes'] + studentScoreDf['No'])) * 100).round(2)
            except ZeroDivisionError:
                studentScoreDf['% Yes'] = np.nan
                print(f"ZeroDivisionError for student {studentName} ({id}) in calculating % Yes")
            # add the values of the total row to totalDf
            totalYes = studentScoreDf.loc['Total', 'Yes']
            totalNo = studentScoreDf.loc['Total', 'No']
            totalNA = studentScoreDf.loc['Total', 'NA']
            totalDf = pd.concat([totalDf, pd.DataFrame({colId: [id], 'Student Name': [studentName], 'Yes': [totalYes], 'No': [totalNo], 'NA': [totalNA]})], ignore_index=True)
            # studentScoreDf['% Yes'] = studentScoreDf.apply(
            #     lambda x: (x['Yes'] / (x['Yes'] + x['No']) * 100) if (x['Yes'] + x['No']) != 0 else np.nan)
            # display(studentScoreDf.head())
            studentScoreTable = createTable(studentScoreDf, f'Scores for {studentName} ({id})', colRatio=[1, 1, 1, 1, 1], customTextCols=[], bottomPadding=6, topPadding=6)
            scoreElements.append(studentScoreTable)
            scoreElements.append(Spacer(1, 12))
        except Exception as e:
            print(f"Error in creating score table for {studentName} ({id}): {e}")
            display(studentDf.head())
            display(studentScoreDf.head())
        # studentDf['Scores'] = studentDf['Scores'].apply(lambda x: json.loads(x))
        # studentDfScores = pd.json_normalize(studentDf['Scores'])
    try:
        totalDf['% Yes'] = ((totalDf['Yes'] / (totalDf['Yes'] + totalDf['No'])) * 100).round(2)
    except ZeroDivisionError:
        totalDf['% Yes'] = np.nan
        print("ZeroDivisionError in calculating % Yes for total scores")
    # totalDf.to_excel(f'{folder}\\BOH1 total scores.xlsx')
    return scoreElements, totalDf

### Time series and other reports

In [8]:
folder = '2025\\BOH2'
# folder = '2025/DDS2'
# folder = '2025/DDS1'
# folder = '2025/BOH1'
# folder = '2025/mini CEX/BOH1'
# folder = '2025/mini CEX/DDS2'
# folder = '2025/BOH2/Smile Squad'
# colAssessorSubmitted = 'Finished'
# colPatientDetails = 'Patient'
# colAssessorName = 'CE Name'
df = pd.read_excel(f'{folder}\\all data scores_combined.xlsx')
# print(df[colAssessorSubmitted].apply(type).head())
# display(df.head())
df['Scores'] = df['Scores'].apply(lambda x: json.loads(x))
df['supervisor_data'] = df['supervisor_data'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)
df['student_data'] = df['student_data'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)
display(df['Item Codes'].head())
print(df['Item Codes'].apply(type).head())
df['Item Codes'] = df['Item Codes'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') else x)
print(df['Item Codes'].apply(type).head())
# filter in only 531 and 532 item codes
# df = df[df['Item Codes'].apply(lambda x: any(code in x for code in ['531', '532']) if isinstance(x, list) else False)]
# display(df.head())
print(df[colId].apply(type).head())
# remove 1617495 and 1605538 students
removeStudents = [1617495, 1605538, 1605779, 1605779, 1234567, 1313675]
# keepStudents = [1472800, 1605779]
# df = df[df[colId].isin(keepStudents)]
# df = df[~df[colId].isin(removeStudents)]
df[colDate] = pd.to_datetime(df[colDate], format='mixed')

# df = df[(df[colDate] >= pd.to_datetime('2025-03-31')) & (df[colDate] <= pd.to_datetime('2025-12-22'))]

# check whether the item codes are being extracted as a list
if 'type' not in df.columns:
    df['type'] = 'Simulation'
pagesize = (pageSize[0], pageSize[1])

# df = df[df[colSubject]=='DENT90146']
# sim and clinic time series
dfSim = df[df['type'] == 'Simulation']
dfClinic = df[df['type'] == 'Clinic']
df = df[df[colClinicType]=='Smile Squad']
dfClinic = dfClinic[dfClinic[colClinicType]=='Smile Squad']
print(f"Simulation records: {len(dfSim)}, Clinic records: {len(dfClinic)}")

# separate by subject for simulation
# print(f"Columns in dfSim: {dfSim.columns.tolist()}")
# subjects = dfSim[colSubject].unique()
# print(f"Subjects found: {subjects}")
# # in clinics replace GP with General Practice and PE with Perio
# dfClinic[colClinicType] = dfClinic[colClinicType].replace({'GP': 'General Practice', 'PE': 'Perio'})
# dfSim[colClinicType] = dfSim[colClinicType].replace({'GP': 'General Practice', 'PE': 'Perio'})
clinicsClinic = dfClinic[colClinicType].unique()
clinicsSim = dfSim[colClinicType].unique()
# clinicsSim = [clinic for clinic in clinicsSim if pd.notna(clinic)]
print(f"Clinics found: {clinicsClinic}, {clinicsSim}")

savefolder = savefolder = f'{folder}/NewDataInfo/{today}'
os.makedirs(savefolder, exist_ok=True)

0    ['011', '022', 'Consent', 'Record_keeping', 'i...
1    ['114-115', '141', 'Consent', 'Record_keeping'...
2    ['Consent', 'Record_keeping', 'infection_contr...
3    ['013', '131', 'Consent', 'Record_keeping', 'i...
4    ['Consent', 'Record_keeping', 'infection_contr...
Name: Item Codes, dtype: object

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: Item Codes, dtype: object
0    <class 'list'>
1    <class 'list'>
2    <class 'list'>
3    <class 'list'>
4    <class 'list'>
Name: Item Codes, dtype: object
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
Name: Student ID, dtype: object
Simulation records: 1516, Clinic records: 224
Clinics found: ['Smile Squad'], ['General Practice' 'GP' '1' nan 'Perio' 'Paeds' 'Fixed Pros']

#### Entrustment info

In [17]:
def getReportsByClinicType(dfType, clinics, type_ = 'Clinic'):
    # save to excel file with separate sheets for each clinic type
    print(f"Generating reports for {type_} data")
    filepath = f'{savefolder}\\entrustment {type_}.xlsx'
    dfDict = {}
    # Check if file exists and determine the mode

    writer_kwargs = getmodeArgs(filepath)

    with pd.ExcelWriter(filepath, **writer_kwargs) as writer:
        for clinic in clinics:
            print(f"Processing clinic type: {clinic}")
            dfclinic = dfType[dfType[colClinicType] == clinic]
            levelcounts, _ = getLevelCounts(dfclinic)
            # display(levelcounts.head())
            # add column for average entrustment level
            for level in ['Lvl 1', 'Lvl 2', 'Lvl 3', 'Lvl 4']:
                if level not in levelcounts.columns:
                    levelcounts[level] = 0
            levelcounts['Average'] = levelcounts['Lvl 1'] * 1 + levelcounts['Lvl 2'] * 2 + levelcounts['Lvl 3'] * 3 + levelcounts['Lvl 4'] * 4
            levelcounts['Average'] = levelcounts['Average']/(levelcounts['Lvl 1'] + levelcounts['Lvl 2'] + levelcounts['Lvl 3'] + levelcounts['Lvl 4'])
            levelcounts['Average'] = levelcounts['Average'].round(2)
            display(levelcounts.head())
            dfDict[clinic] = levelcounts
            levelcounts.to_excel(writer, sheet_name=clinic)

dfClinicReportsByType = getReportsByClinicType(dfClinic, clinicsClinic, type_='Clinic')
# dfSimReportsByType = getReportsByClinicType(dfSim, clinicsSim, type_='Simulation')

Generating reports for Clinic data
Processing clinic type: Smile Squad

ES  Student ID    Student Name  Lvl 2  Lvl 3  Lvl 4  Lvl 1  Average
3      1430664       tara zare      2      4      0      0     2.67
4      1461457  Jade Rosenberg      2      1      2      0     3.00
5      1466081    Harlean Kaur      1      4      1      0     3.00
6      1469076       Anson Koo      1      0      5      0     3.67
14     1600923      Jiahua YAN      1      0      4      0     3.60

#### Patient count info

In [16]:
filepath = f'{savefolder}\\patientsessioninfo.xlsx'
writer_kwargs = getmodeArgs(filepath)
with pd.ExcelWriter(filepath, **writer_kwargs) as writer:
# get numer of patients etc for each clinic type in Clinic
    for clinic in clinicsClinic:
        print(f"Processing patient data for clinic type: {clinic}")
        dfclinic = dfClinic[dfClinic[colClinicType] == clinic]
        patientCounts = getNPatients(dfclinic)
        print(f"Patient counts for clinic type {clinic}:")
        display(patientCounts.head())
        # get number of sessions which is unique assessment_id
        sessionCounts = dfclinic.groupby([colId])['assessment_id'].nunique().reset_index()
        sessionCounts[colName] = sessionCounts[colId].apply(lambda x: dfclinic[dfclinic[colId] == x][colName].values[0])
        sessionCounts.rename(columns={'assessment_id': 'Session Counts'}, inplace=True)
        patientCounts.to_excel(writer, sheet_name=f'{clinic} Patients', index=False)
        sessionCounts.to_excel(writer, sheet_name=f'{clinic} Sessions', index=False)

Processing patient data for clinic type: Smile Squad
Patients 224

   Student ID  count
0     1617304      8
1     1472800      8
2     1606096      8
3     1605793      7
4     1594958      7

   Student ID    Student Name  Patient Counts
0     1617304  Somaya Sarwari               8
1     1472800      Phong Pham               8
2     1606096      Aidah Khan               8
3     1605793    steven hanna               7
4     1594958   Dalena Nguyen               7

Patient counts for clinic type Smile Squad:

   Student ID    Student Name  Patient Counts
0     1617304  Somaya Sarwari               8
1     1472800      Phong Pham               8
2     1606096      Aidah Khan               8
3     1605793    steven hanna               7
4     1594958   Dalena Nguyen               7

#### Comment file

In [12]:
# create pdf reports with comments for each student

pageSize = (variableUtils.pageSize[0], variableUtils.pageSize[1])

elements = []
def clean_text_for_paragraph(text):
    """Clean text to prevent XML parsing errors in ReportLab Paragraph"""
    if pd.isna(text) or text is None:
        return ''
    
    # Convert to string
    text = str(text)
    
    # Remove or escape problematic characters
    text = text.replace('&', '&amp;')  # Must be first
    text = text.replace('<', '&lt;')
    text = text.replace('>', '&gt;')
    text = text.replace('"', '&quot;')
    text = text.replace("'", '&#39;')
    text = text.replace('_x000D_', '')  # Remove carriage return artifacts
    
    # Remove control characters and non-printable characters
    text = re.sub(r'[^\x20-\x7E\n\r\t]', '', text)
    
    # Replace newlines with HTML breaks
    text = text.replace('\n', '<br/>')
    text = text.replace('\r', '')
    # Limit text length to prevent overly large cells
    if len(text) > 2000:  # Limit to 2000 characters
        text = text[:2000] + "... [text truncated]"
    # Remove any remaining unclosed tags or problematic sequences
    text = re.sub(r'<(?![/]?br[/]?>)', '&lt;', text)
    
    return text.strip()

def createComments(dfclinic, clinicType):
    students = dfclinic[colId].unique()
    # sort the students by name
    students = sorted(students, key=lambda x: dfclinic[dfclinic[colId] == x][colName].values[0])
    filename = f'{savefolder}\\student feedback {clinicType}.pdf'
    doc = SimpleDocTemplate(filename, pagesize=pageSize, rightMargin=rightMargin, leftMargin=leftMargin, topMargin=topMargin, bottomMargin=bottomMargin)
    dfDict = {}
    for studentId in students:
        studentDf = dfclinic[dfclinic[colId] == studentId]
        # sort by date
        studentDf.sort_values(by=colDate, inplace=True)
        studentDf[colDate] = studentDf[colDate].dt.strftime('%d/%m/%Y')
        name = studentDf[colName].values[0]
        print(f"Creating report for student ID: {studentId}, Name: {name}")
        studentDf[colStudentFeedback] = studentDf[colStudentFeedback].apply(lambda text: re.sub(r'[^\x00-\x7F]+', '', text) if isinstance(text, str) else text)
        # replace \n with <br/>
        studentDf[colStudentFeedback] = studentDf[colStudentFeedback].apply(lambda text: clean_text_for_paragraph(text))
        studentDf[colAssessorFeedback] = studentDf[colAssessorFeedback].apply(lambda text: clean_text_for_paragraph(text))
        commentDf = studentDf[[colDate, colAssessorName, colAssessorFeedback]].copy()
        # replace nan assessor names with 'N/A'
        commentDf[colAssessorName] = commentDf[colAssessorName].fillna('N/A')
        # remove rows with empty comments
        commentDf = commentDf[commentDf[colAssessorFeedback].notna() & (commentDf[colAssessorFeedback].str.strip() != '')]
        # remove columns with all na values
        commentTable = createTable(commentDf, f'Feedback Comments for {name} ({studentId})', colRatio=[1.2, 2, 8] ,customTextCols=[0, 1, 2], bottomPadding=6, topPadding=6, tableTextStyle=tableTextStyleSmall, pageSize=pageSize)
        # elements.append(Paragraph(f'{name} ({studentId})', subheadingStyle))
        # elements.append(Spacer(1, 12))
        elements.append(commentTable)
        elements.append(PageBreak())

        # change <br/> back to \n for excel export
        studentDf[colAssessorFeedback] = studentDf[colAssessorFeedback].apply(lambda text: text.replace('<br/>', '\n') if isinstance(text, str) else text)
        studentDf[colStudentFeedback] = studentDf[colStudentFeedback].apply(lambda text: text.replace('<br/>', '\n') if isinstance(text, str) else text)
        # select only date, assessor name, assessor feedback, student feedback
        studentDf = studentDf[[colDate, colAssessorName, colAssessorFeedback, colStudentFeedback]]
        studentDf = studentDf[studentDf[colAssessorFeedback].notna() & (studentDf[colAssessorFeedback].str.strip() != '')]
        dfDict[f'{studentId} ({name})'] = studentDf
        # break
    doc.build(elements)
    # create pdf
    return dfDict

# for sim and clinic
# dfSimComments = createComments(dfSim, 'Simulation')
dfClinicComments = createComments(dfClinic, 'Clinic')
# filepath = f'{savefolder}\\student comments_sim.xlsx'
# writer_kwargs = getmodeArgs(filepath)
# with pd.ExcelWriter(filepath, **writer_kwargs) as writer:
#     for studentId, commentDf in dfSimComments.items():
#         sheetName = f'{studentId}'
#         # truncate sheet name to 31 characters
#         sheetName = sheetName[:31]
#         commentDf.to_excel(writer, sheet_name=sheetName, index=False)
filepath = f'{savefolder}\\student comments_clinic.xlsx'
writer_kwargs = getmodeArgs(filepath)
with pd.ExcelWriter(filepath, **writer_kwargs) as writer:
    for studentId, commentDf in dfClinicComments.items():
        sheetName = f'{studentId}'
        # truncate sheet name to 31 characters
        sheetName = sheetName[:31]
        commentDf.to_excel(writer, sheet_name=sheetName, index=False)

Creating report for student ID: 1606096, Name: Aidah Khan
Creating table for Feedback Comments for Aidah Khan (1606096)
Creating report for student ID: 1615333, Name: Annie Phung
Creating table for Feedback Comments for Annie Phung (1615333)
Creating report for student ID: 1469076, Name: Anson Koo
Creating table for Feedback Comments for Anson Koo (1469076)
Creating report for student ID: 1352051, Name: Ayesha Riaz
Creating table for Feedback Comments for Ayesha Riaz (1352051)
Creating report for student ID: 1616618, Name: Bubby Tereva
Creating table for Feedback Comments for Bubby Tereva (1616618)
Creating report for student ID: 1624825, Name: Christina Golets
Creating table for Feedback Comments for Christina Golets (1624825)
Creating report for student ID: 1594851, Name: Chuling LI
Creating table for Feedback Comments for Chuling LI (1594851)
Creating report for student ID: 1594958, Name: Dalena Nguyen
Creating table for Feedback Comments for Dalena Nguyen (1594958)
Creating report for student ID: 1146177, Name: Daniella Icho Malak
Creating table for Feedback Comments for Daniella Icho Malak (1146177)
Creating report for student ID: 1605480, Name: Gabrielle Le
Creating table for Feedback Comments for Gabrielle Le (1605480)
Creating report for student ID: 1606071, Name: Halima Fiqi
Creating table for Feedback Comments for Halima Fiqi (1606071)
Creating report for student ID: 1466081, Name: Harlean Kaur
Creating table for Feedback Comments for Harlean Kaur (1466081)
Creating report for student ID: 1634259, Name: Hilda Petros
Creating table for Feedback Comments for Hilda Petros (1634259)
Creating report for student ID: 1637288, Name: Ivan Yang
Creating table for Feedback Comments for Ivan Yang (1637288)
Creating report for student ID: 1461457, Name: Jade Rosenberg
Creating table for Feedback Comments for Jade Rosenberg (1461457)
Creating report for student ID: 1472447, Name: Jasmeet Kaur
Creating table for Feedback Comments for Jasmeet Kaur (1472447)
Creating report for student ID: 1600923, Name: Jiahua YAN
Creating table for Feedback Comments for Jiahua YAN (1600923)
Creating report for student ID: 1617003, Name: Jovilia Gracilla Vergara
Creating table for Feedback Comments for Jovilia Gracilla Vergara (1617003)
Creating report for student ID: 1616141, Name: Kate McLennan Arnott
Creating table for Feedback Comments for Kate McLennan Arnott (1616141)
Creating report for student ID: 1615131, Name: Katie Nguyen
Creating table for Feedback Comments for Katie Nguyen (1615131)
Creating report for student ID: 1617958, Name: Lucia Williams
Creating table for Feedback Comments for Lucia Williams (1617958)
Creating report for student ID: 1625104, Name: Lydia Faranso
Creating table for Feedback Comments for Lydia Faranso (1625104)
Creating report for student ID: 1637313, Name: Moe Myint Tha
Creating table for Feedback Comments for Moe Myint Tha (1637313)
Creating report for student ID: 1472800, Name: Phong Pham
Creating table for Feedback Comments for Phong Pham (1472800)
Creating report for student ID: 1535538, Name: Qiwen Xue
Creating table for Feedback Comments for Qiwen Xue (1535538)
Creating report for student ID: 1610017, Name: Rachel Chong
Creating table for Feedback Comments for Rachel Chong (1610017)
Creating report for student ID: 1617334, Name: Razan Kamarelddin
Creating table for Feedback Comments for Razan Kamarelddin (1617334)
Creating report for student ID: 1616745, Name: Rida Ali
Creating table for Feedback Comments for Rida Ali (1616745)
Creating report for student ID: 1295910, Name: Sabiha Faizi
Creating table for Feedback Comments for Sabiha Faizi (1295910)
Creating report for student ID: 1605677, Name: Sally Sang
Creating table for Feedback Comments for Sally Sang (1605677)
Creating report for student ID: 1606158, Name: Samantha Chim
Creating table for Feedback Comments for Samantha Chim (1606158)
Creating report for student ID: 1617304, Name: Somaya Sarwari
Creating table for Feedback Comments for Somaya Sarwari (1617304)
Creating report for student ID: 1617587, Name: Sujin Ahn
Creating table for Feedback Comments for Sujin Ahn (1617587)
Creating report for student ID: 1472831, Name: Usman Majoo
Creating table for Feedback Comments for Usman Majoo (1472831)
Creating report for student ID: 1473072, Name: Uthman Abdul-Rahman
Creating table for Feedback Comments for Uthman Abdul-Rahman (1473072)
Creating report for student ID: 1606153, Name: Valantina AL-Zeebaree
Creating table for Feedback Comments for Valantina AL-Zeebaree (1606153)
Creating report for student ID: 1605390, Name: Vianna Tran
Creating table for Feedback Comments for Vianna Tran (1605390)
Creating report for student ID: 1625191, Name: Xiaoru (Helen) Mai
Creating table for Feedback Comments for Xiaoru (Helen) Mai (1625191)
Creating report for student ID: 1608030, Name: Zipei Cheng
Creating table for Feedback Comments for Zipei Cheng (1608030)
Creating report for student ID: 1606077, Name: aida yosufi
Creating table for Feedback Comments for aida yosufi (1606077)
Creating report for student ID: 1625619, Name: ella watts
Creating table for Feedback Comments for ella watts (1625619)
Creating report for student ID: 1605793, Name: steven hanna
Creating table for Feedback Comments for steven hanna (1605793)
Creating report for student ID: 1615261, Name: supriya shrestha
Creating table for Feedback Comments for supriya shrestha (1615261)
Creating report for student ID: 1430664, Name: tara zare
Creating table for Feedback Comments for tara zare (1430664)

In [ ]:
for subject in subjects:
    if subject!='DENT90148':
        continue
    print(f"Processing subject: {subject}")
    dfSubject = dfSim[dfSim[colSubject] == subject]
    print(f"Records for {subject}: {len(dfSubject)}")
    if dfSubject.empty:
        print(f"No records for subject: {subject}, skipping...")
        continue
    docSubject = SimpleDocTemplate(f"{folder}\\Simulation time series ({subject}).pdf", pagesize=pagesize,
                            rightMargin=36, leftMargin=36,
                            topMargin=36, bottomMargin=36)
    subjectElements = createTimeSeriesReport(dfSubject, scoreKey='Weighted Score')
    docSubject.build(subjectElements)

#### Time series

In [18]:
# doc = SimpleDocTemplate(f'{folder}\\Score time series (all).pdf', pagesize=pagesize, rightMargin = rightMargin/2, leftMargin = leftMargin/2, 
#                         topMargin = topMargin/2, bottomMargin = bottomMargin/2)
# timeSeriesElements = createTimeSeriesReport(df, 'Weighted Score', pageSize=pagesize)
# doc.build(timeSeriesElements)


# docSim = SimpleDocTemplate(f'{folder}\\Score time series (Simulation).pdf', pagesize=pageSize, rightMargin = rightMargin/2, leftMargin = leftMargin/2,
#                            topMargin = topMargin/2, bottomMargin = bottomMargin/2)
# timeSeriesElements = createTimeSeriesReport(dfSim, 'Weighted Score')
# docSim.build(timeSeriesElements)

docClin = SimpleDocTemplate(f'{savefolder}\\Score time series (Clinic).pdf', pagesize=pageSize, rightMargin = rightMargin/2, leftMargin = leftMargin/2, 
                            topMargin = topMargin/2, bottomMargin = bottomMargin/2)
timeSeriesElements = createTimeSeriesReport(dfClinic, 'Weighted Score')
docClin.build(timeSeriesElements)
import sys
sys.exit(0)

Processing student ID: 1606096
Item: 011, ScoreDict: {'Yes': 16, 'No': 0, 'NA': 1, '% Yes': 100.0, 'Cutoff': 51.56, 'Weighted Cutoff': 54.79, 'Weighted Sum': 70, 'Denominator': 70, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 53.83}, Primary Score (Weighted Score): 100.0
Item: 111, ScoreDict: {'Yes': 0, 'No': 0, 'NA': 4, '% Yes': nan, 'Cutoff': nan, 'Weighted Cutoff': nan, 'Weighted Sum': nan, 'Denominator': nan, 'Weighted Score': nan, 'Total Score': nan}, Primary Score (Weighted Score): nan
Item: 111, ScoreDict: {'Yes': 0, 'No': 0, 'NA': 4, '% Yes': nan, 'Cutoff': nan, 'Weighted Cutoff': nan, 'Weighted Sum': nan, 'Denominator': nan, 'Weighted Score': nan, 'Total Score': nan}, Fallback Score (% Yes): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 131, ScoreDict: {'Yes': 1, 'No': 0, 'NA': 3, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 131, ScoreDict: {'Yes': 1, 'No': 0, 'NA': 3, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 141, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 50.0, 'Weighted Cutoff': 50.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 50.0}, Primary Score (Weighted Score): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Item: 011, ScoreDict: {'Yes': 16, 'No': 0, 'NA': 1, '% Yes': 100.0, 'Cutoff': 51.56, 'Weighted Cutoff': 54.79, 'Weighted Sum': 70, 'Denominator': 70, 'Weighted Score': 100.0, 'Total Score': 98.75, 'Total Cutoff': 53.83}, Primary Score (Weighted Score): 100.0
Item: 131, ScoreDict: {'Yes': 0, 'No': 0, 'NA': 4, '% Yes': nan, 'Cutoff': nan, 'Weighted Cutoff': nan, 'Weighted Sum': nan, 'Denominator': nan, 'Weighted Score': nan, 'Total Score': nan}, Primary Score (Weighted Score): nan
Item: 131, ScoreDict: {'Yes': 0, 'No': 0, 'NA': 4, '% Yes': nan, 'Cutoff': nan, 'Weighted Cutoff': nan, 'Weighted Sum': nan, 'Denominator': nan, 'Weighted Score': nan, 'Total Score': nan}, Fallback Score (% Yes): nan
Item: 141, ScoreDict: {'Yes': 0, 'No': 0, 'NA': 5, '% Yes': nan, 'Cutoff': nan, 'Weighted Cutoff': nan, 'Weighted Sum': nan, 'Denominator': nan, 'Weighted Score': nan, 'Total Score': nan}, Primary Score (Weighted Score): nan
Item: 141, ScoreDict: {'Yes': 0, 'No': 0, 'NA': 5, '% Yes': nan, 'Cutoff': nan, 'Weighted Cutoff': nan, 'Weighted Sum': nan, 'Denominator': nan, 'Weighted Score': nan, 'Total Score': nan}, Fallback Score (% Yes): nan
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Item: 011, ScoreDict: {'Yes': 17, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 51.47, 'Weighted Cutoff': 54.59, 'Weighted Sum': 73, 'Denominator': 73, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 53.67}, Primary Score (Weighted Score): 100.0
Item: 111, ScoreDict: {'Yes': 0, 'No': 0, 'NA': 4, '% Yes': nan, 'Cutoff': nan, 'Weighted Cutoff': nan, 'Weighted Sum': nan, 'Denominator': nan, 'Weighted Score': nan, 'Total Score': nan}, Primary Score (Weighted Score): nan
Item: 111, ScoreDict: {'Yes': 0, 'No': 0, 'NA': 4, '% Yes': nan, 'Cutoff': nan, 'Weighted Cutoff': nan, 'Weighted Sum': nan, 'Denominator': nan, 'Weighted Score': nan, 'Total Score': nan}, Fallback Score (% Yes): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 131, ScoreDict: {'Yes': 1, 'No': 0, 'NA': 3, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 131, ScoreDict: {'Yes': 1, 'No': 0, 'NA': 3, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 141, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 50.0, 'Weighted Cutoff': 50.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 50.0}, Primary Score (Weighted Score): 100.0
Item: 114-115, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 114-115, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Item: 013, ScoreDict: {'Yes': 8, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 20.0, 'Weighted Cutoff': 20.53, 'Weighted Sum': 38, 'Denominator': 38, 'Weighted Score': 100.0, 'Total Score': 96.25, 'Total Cutoff': 26.42}, Primary Score (Weighted Score): 100.0
Item: 022, ScoreDict: {'Yes': 8, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 68.75, 'Weighted Cutoff': 71.84, 'Weighted Sum': 38, 'Denominator': 38, 'Weighted Score': 100.0, 'Total Score': 96.25, 'Total Cutoff': 67.47}, Primary Score (Weighted Score): 100.0
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 131, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 131, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 141, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 50.0, 'Weighted Cutoff': 50.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 96.25, 'Total Cutoff': 50.0}, Primary Score (Weighted Score): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Item: 011, ScoreDict: {'Yes': 16, 'No': 0, 'NA': 1, '% Yes': 100.0, 'Cutoff': 51.56, 'Weighted Cutoff': 54.79, 'Weighted Sum': 70, 'Denominator': 70, 'Weighted Score': 100.0, 'Total Score': 96.25, 'Total Cutoff': 53.83}, Primary Score (Weighted Score): 100.0
Item: 022, ScoreDict: {'Yes': 8, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 68.75, 'Weighted Cutoff': 71.84, 'Weighted Sum': 38, 'Denominator': 38, 'Weighted Score': 100.0, 'Total Score': 96.25, 'Total Cutoff': 67.47}, Primary Score (Weighted Score): 100.0
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 131, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 131, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 141, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 50.0, 'Weighted Cutoff': 50.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 96.25, 'Total Cutoff': 50.0}, Primary Score (Weighted Score): 100.0
Item: 161, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 82.0, 'Weighted Cutoff': 82.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 96.25, 'Total Cutoff': 75.6}, Primary Score (Weighted Score): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Item: 011, ScoreDict: {'Yes': 17, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 51.47, 'Weighted Cutoff': 54.59, 'Weighted Sum': 73, 'Denominator': 73, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 53.67}, Primary Score (Weighted Score): 100.0
Item: 022, ScoreDict: {'Yes': 8, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 68.75, 'Weighted Cutoff': 71.84, 'Weighted Sum': 38, 'Denominator': 38, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 67.47}, Primary Score (Weighted Score): 100.0
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 131, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 131, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 141, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 50.0, 'Weighted Cutoff': 50.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 50.0}, Primary Score (Weighted Score): 100.0
Item: 161, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 82.0, 'Weighted Cutoff': 82.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 75.6}, Primary Score (Weighted Score): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Processing student ID: 1615333
Item: 011, ScoreDict: {'Yes': 17, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 51.47, 'Weighted Cutoff': 54.59, 'Weighted Sum': 73, 'Denominator': 73, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 53.67}, Primary Score (Weighted Score): 100.0
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 141, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 50.0, 'Weighted Cutoff': 50.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 50.0}, Primary Score (Weighted Score): 100.0
Item: 161, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 82.0, 'Weighted Cutoff': 82.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 75.6}, Primary Score (Weighted Score): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Item: 011, ScoreDict: {'Yes': 17, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 51.47, 'Weighted Cutoff': 54.59, 'Weighted Sum': 73, 'Denominator': 73, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 53.67}, Primary Score (Weighted Score): 100.0
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 141, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 50.0, 'Weighted Cutoff': 50.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 50.0}, Primary Score (Weighted Score): 100.0
Item: 114-115, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 114-115, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Item: 011, ScoreDict: {'Yes': 17, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 51.47, 'Weighted Cutoff': 54.59, 'Weighted Sum': 73, 'Denominator': 73, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 53.67}, Primary Score (Weighted Score): 100.0
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 141, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 50.0, 'Weighted Cutoff': 50.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 50.0}, Primary Score (Weighted Score): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Item: 011, ScoreDict: {'Yes': 17, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 51.47, 'Weighted Cutoff': 54.59, 'Weighted Sum': 73, 'Denominator': 73, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 53.67}, Primary Score (Weighted Score): 100.0
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 131, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 131, ScoreDict: {'Yes': 4, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 141, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 50.0, 'Weighted Cutoff': 50.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 50.0}, Primary Score (Weighted Score): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Item: 011, ScoreDict: {'Yes': 16, 'No': 0, 'NA': 1, '% Yes': 100.0, 'Cutoff': 52.81, 'Weighted Cutoff': 56.4, 'Weighted Sum': 68, 'Denominator': 68, 'Weighted Score': 100.0, 'Total Score': 96.25, 'Total Cutoff': 55.12}, Primary Score (Weighted Score): 100.0
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Primary Score (Weighted Score): nan
Item: 121, ScoreDict: {'Yes': 3, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 0.0, 'Weighted Cutoff': nan, 'Weighted Sum': 0, 'Denominator': 0, 'Weighted Score': nan, 'Total Score': nan, 'Total Cutoff': nan}, Fallback Score (% Yes): 100.0
Item: 141, ScoreDict: {'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, 'Cutoff': 50.0, 'Weighted Cutoff': 50.0, 'Weighted Sum': 25, 'Denominator': 25, 'Weighted Score': 100.0, 'Total Score': 96.25, 'Total Cutoff': 50.0}, Primary Score (Weighted Score): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Item: 111, ScoreDict: {'Yes': 2, 'No': 0, 'NA': 2, '% Yes': 100.0, 'Cutoff': 100.0, 'Weighted Cutoff': 100.0, 'Weighted Sum': 10, 'Denominator': 10, 'Weighted Score': 100.0, 'Total Score': 100.0, 'Total Cutoff': 90.0}, Primary Score (Weighted Score): 100.0
Skipping PEC item code: Consent
Skipping PEC item code: positioning
Skipping PEC item code: Record_keeping
Skipping PEC item code: infection_control
Processing student ID: 1469076

SystemExit: 0

In [ ]:
# # Create a doc=========================================================================================================================================================================
docScores = SimpleDocTemplate(f'{folder}\\Report scores.pdf', pagesize=pageSize, rightMargin = rightMargin, leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
docScoresSim = SimpleDocTemplate(f'{folder}\\Report scores Sim.pdf', pagesize=pageSize, rightMargin = rightMargin, leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
docScoresClin = SimpleDocTemplate(f'{folder}\\Report scores Clin.pdf', pagesize=pageSize, rightMargin = rightMargin, leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
scoreElements, totalDf = createScoreTables(df)
docScores.build(scoreElements.copy())
scoreElementsSim, totalDfSim = createScoreTables(dfSim)
docScoresSim.build(scoreElementsSim.copy())
scoreElementsClin, totalDfClin = createScoreTables(dfClinic)
docScoresClin.build(scoreElementsClin.copy())
totalDf.to_excel(f'{folder}\\All student scores in a table.xlsx')

In [19]:

doc = SimpleDocTemplate(f'{savefolder}\\Basic info.pdf', pagesize=pageSize, rightMargin = rightMargin, leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
docSim = SimpleDocTemplate(f'{savefolder}\\Basic info Sim.pdf', pagesize=pageSize, rightMargin = rightMargin, leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
docClin = SimpleDocTemplate(f'{savefolder}\\Basic info Clin.pdf', pagesize=pageSize, rightMargin = rightMargin, leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
elements = []

filename = f'{savefolder}/Basic info.xlsx'
# simElements = createData(dfSim, 'Simulation', filepath=filename)
# elements.extend(simElements)
# docSim.build(simElements.copy())

# now for clinic data
clinElements = createData(dfClinic, 'Clinic', filepath=filename) 
patientCounts = getNPatients(dfClinic)
patientCountsTable = createTable(patientCounts, 'Patient Counts', colRatio=[1.3, 1.7, 1], bottomPadding=8, topPadding=8)
clinElements.append(patientCountsTable)
# text = 'I have used the data in patient_complexity to get the number of patients seen by each student as there is no other field to get the number of patients seen. ' 
# clinElements.append(Paragraph(text, tableTextStyle))
docClin.build(clinElements.copy())
elements.extend(clinElements)


elements.append(PageBreak())
doc.build(elements.copy())

Creating table for Entrustment Level Counts
Creating table for Professionalism Level Counts
Creating table for Communication Level Counts
Creating table for Time Management Level Counts
Creating table for Overall Entrustment Level Counts

  Student ID    Student Name Entrustment                     Professionalism  \
                                   Lvl 2 Lvl 3 Lvl 4 Average           Lvl 1
0    1430664       tara zare           2     4     0    2.67               1
1    1461457  Jade Rosenberg           2     1     2    3.00               0
2    1466081    Harlean Kaur           1     4     1    3.00               0
3    1469076       Anson Koo           1     0     5    3.67               0
4    1600923      Jiahua YAN           1     0     4    3.60               0

                Communication               Time Management              \
  Lvl 2 Average         Lvl 1 Lvl 2 Average           Lvl 2 Lvl 3 Lvl 4
0     5    1.83             0     6     2.0               1     3     2
1     5    2.00             2     3     1.6               0     3     2
2     6    2.00             0     6     2.0               1     2     3
3     6    2.00             0     6     2.0               1     0     5
4     5    2.00             0     5     2.0               0     1     4


  Average
0    3.17
1    3.40
2    3.33
3    3.67
4    3.80

Empty DataFrame
Columns: [Unnamed: 0, form_name, assessment_id, Student Name, Student ID, Date, cohort, subject, type, completed, data, role, clinic, scales, version, checklists, assessor_id, patient_age, patient_drn, Assessor Name, patient_details, patient_interpreter, submitted_by_student, additional_checklists, submitted_by_assessor, student_data, supervisor_data, Student Feedback, TS, ES, CS, PS, Patient Complexity, Assessor Feedback, fta_substitute, teeth_quadrant_details, CI, Item Codes, Scores]
Index: []

Empty DataFrame
Columns: [Student ID, Student Name, Date, CI]
Index: []

Creating table for Critical Incidents
Creating table for Critical Incident Counts
Creating table for Dates Attented

Student ID
1606096    8
1472800    8
1617304    8
1594958    7
1617003    7
Name: count, dtype: int64

Patients 224

   Student ID  count
0     1606096      8
1     1472800      8
2     1617304      8
3     1594958      7
4     1617003      7

   Student ID              Student Name  Patient Counts
0     1606096                Aidah Khan               8
1     1472800                Phong Pham               8
2     1617304            Somaya Sarwari               8
3     1594958             Dalena Nguyen               7
4     1617003  Jovilia Gracilla Vergara               7

Creating table for Patient Counts

In [ ]:
for clinic in df[colClinicType].unique():
    print(f"Processing clinic type: {clinic}")
    dfclinic = df[df[colClinicType] == clinic]
    filepath = f'{savefolder}\\basic info {clinic}.xlsx'
    clinicElements = createData(dfclinic, f'{clinic}', filepath=filepath)

### Scores and seperated Df

In [ ]:
df_ = df.copy()
# df_ = df_[df_['assessor_submitted'] == True]  # filter for only submitted assessments
df_['Item Codes'] = df_['supervisor_data'].apply(extractCodes)
getRowWiseScores(df_)
df_.to_excel(f'{folder}\\all data scores.xlsx')

In [ ]:
df_ = pd.read_excel(f'{folder}\\all data scores.xlsx')
type_ = 'Simulation'
type_ = 'Clinic'
type_ = None
if type_ is not None:
    df_ = df_[df_['type'] == type_]  # filter for type
dfDict = getSeparatedItemDf(df_)
# save the dfs to same workbook with different sheet names
filepath = f'{folder}\\SeparatedbyItems {type_} ({today}).xlsx' if type_ else f'{folder}\\SeparatedbyItems ({today}).xlsx'
if os.path.exists(filepath):
    os.remove(filepath)
# sort the keys of dfDict by date and item code
dfDict = {k: v for k, v in sorted(dfDict.items(), key=lambda item: (item[0], pd.to_datetime(item[1][colDate].iloc[0])))}
# dfDict = dict(sorted(dfDict.items()))
display(dfDict.keys())
with pd.ExcelWriter(filepath, engine='openpyxl') as writer:
    for item, itemDf in dfDict.items():
        print(f'Saving {item} to {filepath}')   
        itemDf.to_excel(writer, sheet_name=item, index=False)
        print(f'Saved {item} to {filepath}')

### New style reports

In [21]:
# df = pd.read_excel(f'{folder}\\all data scores_combined.xlsx')
# df = df[df[colSubject] == 'DENT90148']
df = df[df[colClinicType]=='Smile Squad']
print(folder)
# df = df[df['type']==type_]  # filter for type
print(f"Number of rows before filtering: {len(df)}")
# display(df.head())

df[colDate] = pd.to_datetime(df[colDate], errors='coerce', format='mixed')
# remove before 21 July 2025
# df = df[(df[colDate] >= pd.to_datetime('2025-07-21')) & (df[colDate] <= pd.to_datetime('2025-10-02'))]

# remove where item codes is empty, it's a column with list of item codes
df['Item Codes'] = df['Item Codes'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
removedf = df[df['Item Codes'].apply(lambda x: len(x) == 0)]
# filter in only 531 and 532 item codes
# df = df[df['Item Codes'].apply(lambda x: any(code in x for code in ['531', '532']) if isinstance(x, list) else False)]
print(f"Removing {len(removedf)} rows with empty Item Codes")
df = df[df['Item Codes'].apply(lambda x: len(x) > 0)]
print(f"Number of rows after filtering: {len(df)}")
savefolder = f'{folder}/NewDataInfo/{today}'
if not os.path.exists(savefolder):
    os.makedirs(savefolder)
# display(df.head())
display(removedf.head())

2025\BOH2
Number of rows before filtering: 224
Removing 0 rows with empty Item Codes
Number of rows after filtering: 224

Empty DataFrame
Columns: [Unnamed: 0, form_name, assessment_id, Student Name, Student ID, Date, cohort, subject, type, completed, data, role, clinic, scales, version, checklists, assessor_id, patient_age, patient_drn, Assessor Name, patient_details, patient_interpreter, submitted_by_student, additional_checklists, submitted_by_assessor, student_data, supervisor_data, Student Feedback, TS, ES, CS, PS, Patient Complexity, Assessor Feedback, fta_substitute, teeth_quadrant_details, CI, Item Codes, Scores]
Index: []

In [22]:
# record number of patients seen by each student, a student sees a patient if student_role is Operator and patient_status is I saw a patient
# Filter relevant rows
seenPatientsDf = df[
    (df['role'] == 'Operator') &
    (df['patient_details'] == 'I saw a patient')
]
colAge = 'Patient Age'
# Bin ages into categories
seenPatientsDf['ageGroup'] = pd.cut(
    seenPatientsDf[colAge],
    bins=[0, 6, 17, float('inf')],
    labels=['0-6', '6-17', '18+'],
    right=False
)

# Count per student and age group
ageGroupCount = (
    seenPatientsDf
    .groupby([colId, 'ageGroup'])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)
ageGroupCount.reset_index(drop=True, inplace=True)
ageGroupCount.set_index(colId, inplace=True)
display(ageGroupCount.head())
# Count patients per student
patientCount = seenPatientsDf.groupby(colId).size().reset_index(name='Patients Seen')
# Add student names
patientCount[colName] = patientCount[colId].apply(lambda x: df[df[colId] == x][colName].values[0])

patientCount.set_index(colId, inplace=True)
# Add age group counts to patientCount
patientCount = patientCount.join(ageGroupCount, how='left')
patientCount.reset_index(inplace=True)
patientCount = patientCount[[colId, colName, 'Patients Seen'] + list(ageGroupCount.columns[:])]
# Save patient count to Excel
display(patientCount.head())
patientCount.to_excel(f'{savefolder}\\Patient Counts ({today}).xlsx', index=False)

KeyError: 'Patient Age'

#### Explode based on item code

In [23]:
# Step 1: Parse fields safely
def safeParse(x):
    if isinstance(x, str):
        try: return ast.literal_eval(x)
        except: return {}
    return x if isinstance(x, dict) else {}

df['Scores'] = df['Scores'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)
df['student_data'] = df['student_data'].apply(safeParse)
df['supervisor_data'] = df['supervisor_data'].apply(safeParse)
display(df.head())
# Explode Item Codes
dfExploded = df.explode('Item Codes').reset_index(drop=True)
dfExploded.rename(columns={'Item Codes': 'Item Code'}, inplace=True)

# ---- Extract related info ----
def extractSubDict(d, keyPrefix, type_='supervisor'):
    # if not isinstance(d, dict): return {}
    if keyPrefix in d.keys():
        dictToReturn = {}
        for mckey, value in d[keyPrefix].items():
            dictToReturn[f'{type_}_{keyPrefix}_{mckey}'] = value
        return dictToReturn
    print(f"[MissingKey] {type_.capitalize()} data key '{keyPrefix}' not found in keys: {list(d.keys())}")
    return {k: v for k, v in d.items() if k.startswith(f'{type_}_{keyPrefix}')}

def extractScore(row):
    code = row['Item Code']
    scoreDict = row['Scores']
    assessmentId = row.get('assessment_id', row.get('ResponseId'))
    
    if not isinstance(scoreDict, dict):
        print(f"[TypeError]({assessmentId}) Scores is not a dict for Item Code: {code}, value: {scoreDict}")
        return None
    
    if code not in scoreDict:
        print(f"[MissingKey]({assessmentId}) Item Code '{code}' not found in Scores keys: {list(scoreDict.keys())}")
        display(row)
        return None

    return scoreDict[code]

# Apply with detailed logging
dfExploded['Filtered Scores'] = dfExploded.apply(extractScore, axis=1)

dfExploded['Filtered student_data'] = dfExploded.apply(
    lambda row: extractSubDict(row['student_data'], f'{row["Item Code"]}', type_='student'), axis=1
)

dfExploded['Filtered supervisor_data'] = dfExploded.apply(
    lambda row: extractSubDict(row['supervisor_data'], f'{row["Item Code"]}', type_='assessor'), axis=1
)
# remove the original columns
dfExploded.drop(columns=['Scores', 'student_data', 'supervisor_data'], inplace=True)
dfExploded.rename(columns={
    'Filtered Scores': 'Scores',
    'Filtered student_data': 'student_data',
    'Filtered supervisor_data': 'supervisor_data'
}, inplace=True)
display(dfExploded.head())
# save the exploded dataframe to excel
dfExploded['Scores'] = dfExploded['Scores'].apply(lambda x: json.dumps(x, indent=2, ensure_ascii=False))
dfExploded['student_data'] = dfExploded['student_data'].apply(lambda x: json.dumps(x, indent=2, ensure_ascii=False))
dfExploded['supervisor_data'] = dfExploded['supervisor_data'].apply(lambda x: json.dumps(x, indent=2, ensure_ascii=False))
dfExploded.to_excel(f'{savefolder}\\ExplodedData({today}).xlsx', index=False)

,Unnamed: 0,form_name,assessment_id,Student Name,Student ID,Date,cohort,subject,type,completed,data,role,clinic,scales,version,checklists,assessor_id,patient_age,patient_drn,Assessor Name,patient_details,patient_interpreter,submitted_by_student,additional_checklists,submitted_by_assessor,student_data,supervisor_data,Student Feedback,TS,ES,CS,PS,Patient Complexity,Assessor Feedback,fta_substitute,teeth_quadrant_details,CI,Item Codes,Scores
4262,2290,FoEz6t,9143,Rida Ali,1616745,2025-10-10,BOH2,ORAL20005,Clinic,1.0,"{""student"": {""011"": {""MC1"": ""Yes"", ""MC2"": ""Yes...",Operator,Smile Squad,"{""time_mgmt"": {""name"": ""Time Management Scale""...",2.0,"{""011"": {""name"": ""Comprehensive Oral Examinati...",NaN,10.0,39329587-78,NaN,I saw a patient,No,True,"{""Consent"": {""name"": ""Consent Checklist"", ""fie...",True,"{'011': {'MC1': 'Yes', 'MC2': 'Yes', 'MC3': 'Y...","{'011': {'MC1': 'Yes', 'MC2': 'Yes', 'MC3': 'Y...","Saw two patients today, and DA. did 011 and 02...",4.0,3.0,2.0,2.0,non-complex,"Saw two patients today, and DA. did 011 and 02...",NaN,NaN,NaN,"[011, 022, 141, Consent, Record_keeping, infec...","{'011': {'Yes': 17, 'No': 0, 'NA': 0, '% Yes':..."
4377,2406,fvVTdu,9362,Ivan Yang,1637288,2025-10-13,BOH2,ORAL20005,Clinic,1.0,"{""student"": {""011"": {""MC1"": ""Yes"", ""MC2"": ""Yes...",Operator,Smile Squad,"{""time_mgmt"": {""name"": ""Time Management Scale""...",2.0,"{""011"": {""name"": ""Comprehensive Oral Examinati...",NaN,6.0,39297622-78,NaN,I saw a patient,No,True,"{""Consent"": {""name"": ""Consent Checklist"", ""fie...",True,"{'011': {'MC1': 'Yes', 'MC2': 'Yes', 'MC3': 'Y...","{'011': {'MC1': 'Yes', 'MC2': 'Yes', 'MC3': 'Y...",Very impressed with your tax planning skills a...,4.0,4.0,2.0,2.0,complex,Very impressed with your tax planning skills a...,NaN,NaN,NaN,"[011, 022, 141, Consent, Record_keeping, infec...","{'011': {'Yes': 15, 'No': 0, 'NA': 2, '% Yes':..."
4378,2407,zkmE4a,9362,Ivan Yang,1637288,2025-10-13,BOH2,ORAL20005,Clinic,1.0,"{""student"": {""011"": {""MC1"": ""Yes"", ""MC2"": ""Yes...",Operator,Smile Squad,"{""time_mgmt"": {""name"": ""Time Management Scale""...",2.0,"{""011"": {""name"": ""Comprehensive Oral Examinati...",NaN,5.0,39332315-78,NaN,I saw a patient,No,True,"{""Consent"": {""name"": ""Consent Checklist"", ""fie...",True,"{'011': {'MC1': 'Yes', 'MC2': 'Yes', 'MC3': 'N...","{'011': {'MC1': 'Yes', 'MC2': 'Yes', 'MC3': 'N...",Did very well today,4.0,4.0,2.0,2.0,non-complex,Did very well today,NaN,NaN,NaN,"[011, 022, 114-115, 121, 131, 141, Consent, Re...","{'011': {'Yes': 13, 'No': 0, 'NA': 4, '% Yes':..."
4381,2410,jZdP2L,9370,Annie Phung,1615333,2025-10-13,BOH2,ORAL20005,Clinic,1.0,"{""student"": {""011"": {""MC1"": ""Yes"", ""MC2"": ""Yes...",Operator,Smile Squad,"{""time_mgmt"": {""name"": ""Time Management Scale""...",2.0,"{""011"": {""name"": ""Comprehensive Oral Examinati...",NaN,10.0,90537-78,NaN,I saw a patient,No,True,"{""Consent"": {""name"": ""Consent Checklist"", ""fie...",True,"{'011': {'MC1': 'Yes', 'MC2': 'Yes', 'MC3': 'Y...","{'011': {'MC1': 'Yes', 'MC2': 'Yes', 'MC3': 'Y...","Today I completed a 011, 141, 161G and 121. So...",4.0,4.0,2.0,2.0,non-complex,"Today I completed a 011, 141, 161G and 121. So...",NaN,NaN,NaN,"[011, 121, 141, 161, Consent, Record_keeping, ...","{'011': {'Yes': 17, 'No': 0, 'NA': 0, '% Yes':..."
4382,2411,rAviYz,9389,Rachel Chong,1610017,2025-10-13,BOH2,ORAL20005,Clinic,1.0,"{""student"": {""Consent"": {""MC1"": ""Yes""}, ""time_...",Support Operator,Smile Squad,"{""time_mgmt"": {""name"": ""Time Management Scale""...",2.0,{},NaN,6.0,39332491,NaN,I saw a patient,No,True,"{""Consent"": {""name"": ""Consent Checklist"", ""fie...",True,"{'Consent': {'MC1': 'Yes'}, 'time_mgmt': {'sca...","{'Consent': {'MC1': 'Yes'}, 'positioning': {'M...",roll sleeve up when wipe down,3.0,3.0,2.0,2.0,non-complex,roll sleeve up when wipe down,NaN,NaN,NaN,"[Consent, Record_keeping, infection_control, p...","{'Consent': {'Yes': 1, 'No': 0, 'NA': 0, '% Ye..."

,Unnamed: 0,form_name,assessment_id,Student Name,Student ID,Date,cohort,subject,type,completed,data,role,clinic,scales,version,checklists,assessor_id,patient_age,patient_drn,Assessor Name,patient_details,patient_interpreter,submitted_by_student,additional_checklists,submitted_by_assessor,Student Feedback,TS,ES,CS,PS,Patient Complexity,Assessor Feedback,fta_substitute,teeth_quadrant_details,CI,Item Code,Scores,student_data,supervisor_data
0,2290,FoEz6t,9143,Rida Ali,1616745,2025-10-10,BOH2,ORAL20005,Clinic,1.0,"{""student"": {""011"": {""MC1"": ""Yes"", ""MC2"": ""Yes...",Operator,Smile Squad,"{""time_mgmt"": {""name"": ""Time Management Scale""...",2.0,"{""011"": {""name"": ""Comprehensive Oral Examinati...",NaN,10.0,39329587-78,NaN,I saw a patient,No,True,"{""Consent"": {""name"": ""Consent Checklist"", ""fie...",True,"Saw two patients today, and DA. did 011 and 02...",4.0,3.0,2.0,2.0,non-complex,"Saw two patients today, and DA. did 011 and 02...",NaN,NaN,NaN,011,"{'Yes': 17, 'No': 0, 'NA': 0, '% Yes': 100.0, ...","{'student_011_MC1': 'Yes', 'student_011_MC2': ...","{'assessor_011_MC1': 'Yes', 'assessor_011_MC2'..."
1,2290,FoEz6t,9143,Rida Ali,1616745,2025-10-10,BOH2,ORAL20005,Clinic,1.0,"{""student"": {""011"": {""MC1"": ""Yes"", ""MC2"": ""Yes...",Operator,Smile Squad,"{""time_mgmt"": {""name"": ""Time Management Scale""...",2.0,"{""011"": {""name"": ""Comprehensive Oral Examinati...",NaN,10.0,39329587-78,NaN,I saw a patient,No,True,"{""Consent"": {""name"": ""Consent Checklist"", ""fie...",True,"Saw two patients today, and DA. did 011 and 02...",4.0,3.0,2.0,2.0,non-complex,"Saw two patients today, and DA. did 011 and 02...",NaN,NaN,NaN,022,"{'Yes': 8, 'No': 0, 'NA': 0, '% Yes': 100.0, '...","{'student_022_MC1': 'Yes', 'student_022_MC2': ...","{'assessor_022_MC1': 'Yes', 'assessor_022_MC2'..."
2,2290,FoEz6t,9143,Rida Ali,1616745,2025-10-10,BOH2,ORAL20005,Clinic,1.0,"{""student"": {""011"": {""MC1"": ""Yes"", ""MC2"": ""Yes...",Operator,Smile Squad,"{""time_mgmt"": {""name"": ""Time Management Scale""...",2.0,"{""011"": {""name"": ""Comprehensive Oral Examinati...",NaN,10.0,39329587-78,NaN,I saw a patient,No,True,"{""Consent"": {""name"": ""Consent Checklist"", ""fie...",True,"Saw two patients today, and DA. did 011 and 02...",4.0,3.0,2.0,2.0,non-complex,"Saw two patients today, and DA. did 011 and 02...",NaN,NaN,NaN,141,"{'Yes': 5, 'No': 0, 'NA': 0, '% Yes': 100.0, '...","{'student_141_MC1': 'Yes', 'student_141_MC2': ...","{'assessor_141_MC1': 'Yes', 'assessor_141_MC2'..."
3,2290,FoEz6t,9143,Rida Ali,1616745,2025-10-10,BOH2,ORAL20005,Clinic,1.0,"{""student"": {""011"": {""MC1"": ""Yes"", ""MC2"": ""Yes...",Operator,Smile Squad,"{""time_mgmt"": {""name"": ""Time Management Scale""...",2.0,"{""011"": {""name"": ""Comprehensive Oral Examinati...",NaN,10.0,39329587-78,NaN,I saw a patient,No,True,"{""Consent"": {""name"": ""Consent Checklist"", ""fie...",True,"Saw two patients today, and DA. did 011 and 02...",4.0,3.0,2.0,2.0,non-complex,"Saw two patients today, and DA. did 011 and 02...",NaN,NaN,NaN,Consent,"{'Yes': 1, 'No': 0, 'NA': 0, '% Yes': 100.0, '...",{'student_Consent_MC1': 'Yes'},{'assessor_Consent_MC1': 'Yes'}
4,2290,FoEz6t,9143,Rida Ali,1616745,2025-10-10,BOH2,ORAL20005,Clinic,1.0,"{""student"": {""011"": {""MC1"": ""Yes"", ""MC2"": ""Yes...",Operator,Smile Squad,"{""time_mgmt"": {""name"": ""Time Management Scale""...",2.0,"{""011"": {""name"": ""Comprehensive Oral Examinati...",NaN,10.0,39329587-78,NaN,I saw a patient,No,True,"{""Consent"": {""name"": ""Consent Checklist"", ""fie...",True,"Saw two patients today, and DA. did 011 and 02...",4.0,3.0,2.0,2.0,non-complex,"Saw two patients today, and DA. did 011 and 02...",NaN,NaN,NaN,Record_keeping,"{'Yes': 1, 'No': 0, 'NA': 0, '% Yes': 100.0, '...",{'student_Record_keeping_MC1': 'Yes'},{'assessor_Record_keeping_MC1': 'Yes'}

#### Use the exploded data to group student items

In [25]:
itemSectionMapping = pd.read_excel(f'{folder}\\..\\item_section_mapping.xlsx', dtype=str)
itemSectionMapping.set_index('Item Code', inplace=True)
dfExploded = pd.read_excel(f'{savefolder}\\ExplodedData({today}).xlsx', dtype={'Item Code': str})
dfExploded['Scores'] = dfExploded['Scores'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)
dfExploded['student_data'] = dfExploded['student_data'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)
dfExploded['supervisor_data'] = dfExploded['supervisor_data'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)
dfExplodedScores = dfExploded['Scores'].apply(pd.Series)
dfExploded = pd.concat([dfExploded, dfExplodedScores], axis=1)
# create Id and name dictionary mapping
idNameMapping = dfExploded[[colId, colName]].drop_duplicates().set_index(colId)[colName].to_dict()
print(f"Unique students: {len(idNameMapping)}, {idNameMapping}")
# create a function to map item codes to section names and subsection names

def mapItemToSection(itemCode):
    
    if itemCode in itemSectionMapping.index:
        return itemSectionMapping.loc[itemCode, 'Section'], itemSectionMapping.loc[itemCode, 'Sub-section']
    else:
        codepart = itemCode.split('-')[0]  # get the part before the first underscore
        if codepart in itemSectionMapping.index:
            return itemSectionMapping.loc[codepart, 'Section'], itemSectionMapping.loc[codepart, 'Sub-section']
        else:
            return None, None

dfExploded[['Section', 'Sub-section']] = dfExploded['Item Code'].apply(lambda x: pd.Series(mapItemToSection(x)))
missingMappings = dfExploded[dfExploded['Section'].isna() | dfExploded['Sub-section'].isna()]
missingMappings.to_excel(f'{savefolder}/missing_mappings.xlsx')
# fill missing sections with 'Miscellaneous'
dfExploded['Section'].fillna('Miscellaneous', inplace=True)
dfExploded['Sub-section'].fillna('Miscellaneous', inplace=True)
# view unique missing codes
missingCodes = missingMappings['Item Code'].unique()

print("Missing Item Codes:", missingCodes)

Unique students: 44, {1616745: 'Rida Ali', 1637288: 'Ivan Yang', 1615333: 'Annie Phung', 1610017: 'Rachel Chong', 1466081: 'Harlean Kaur', 1461457: 'Jade Rosenberg', 1624825: 'Christina Golets', 1616141: 'Kate McLennan Arnott', 1625619: 'ella watts', 1616618: 'Bubby Tereva', 1146177: 'Daniella Icho Malak', 1606077: 'aida yosufi', 1606153: 'Valantina AL-Zeebaree', 1606096: 'Aidah Khan', 1535538: 'Qiwen Xue', 1605677: 'Sally Sang', 1615131: 'Katie Nguyen', 1606158: 'Samantha Chim', 1473072: 'Uthman Abdul-Rahman', 1472831: 'Usman Majoo', 1608030: 'Zipei Cheng', 1615261: 'supriya shrestha', 1605793: 'steven hanna', 1469076: 'Anson Koo', 1594958: 'Dalena Nguyen', 1617304: 'Somaya Sarwari', 1472447: 'Jasmeet Kaur', 1617334: 'Razan Kamarelddin', 1430664: 'tara zare', 1637313: 'Moe Myint Tha', 1606071: 'Halima Fiqi', 1605480: 'Gabrielle Le', 1295910: 'Sabiha Faizi', 1472800: 'Phong Pham', 1605390: 'Vianna Tran', 1594851: 'Chuling LI', 1634259: 'Hilda Petros', 1625191: 'Xiaoru (Helen) Mai', 1600923: 'Jiahua YAN', 1617003: 'Jovilia Gracilla Vergara', 1625104: 'Lydia Faranso', 1617587: 'Sujin Ahn', 1352051: 'Ayesha Riaz', 1617958: 'Lucia Williams'}
Missing Item Codes: ['Consent' 'Record_keeping' 'infection_control' 'positioning']

In [26]:
def cfmatrix(studentData, supervisorData):
    # studentData and supervisorData are dicts with keys student_itemCode_MC1 , supervisor_itemCode_MC1 etc with values Yes, No, NA
    matrix = pd.DataFrame(0, index=['Yes', 'No', 'NA'], columns=['Yes', 'No', 'NA']) # rows: student, columns: supervisor
    # replace the values in studentData 'Not Assessed' with 'NA'
    # print(studentData, supervisorData)
    studentData = {k: ('NA' if v == 'Not Assessed' else v) for k, v in studentData.items()}
    supervisorData = {k: ('NA' if v == 'Not Assessed' else v) for k, v in supervisorData.items()}
    
    # Extract matching keys between student and supervisor data
    student_keys = set(studentData.keys())
    supervisor_keys = set(supervisorData.keys())
    
    # Find corresponding MC keys (student_itemCode_MC1 should match with supervisor_itemCode_MC1)
    for student_key in student_keys:
        if student_key.startswith('student_'):
            # Convert student key to supervisor key
            supervisor_key = student_key.replace('student_', 'assessor_', 1)
            
            if supervisor_key in supervisor_keys:
                student_value = studentData[student_key]
                supervisor_value = supervisorData[supervisor_key]
                
                # Only count if both values are valid (not None, not empty string)
                if (student_value in ['Yes', 'No', 'NA'] and 
                    supervisor_value in ['Yes', 'No', 'NA']):
                    matrix.loc[student_value, supervisor_value] += 1
    
    return matrix

# now for each item code, create confusion matrix of student vs supervisor responses
def createCfMatrix(dfItem):
    totalMatrix = pd.DataFrame(0, index=['Yes', 'No', 'NA'], columns=['Yes', 'No', 'NA'])
    for i, row in dfItem.iterrows():
        studentData = row['student_data']
        supervisorData = row['supervisor_data']
        matrix = cfmatrix(studentData, supervisorData)
        totalMatrix += matrix
    stuYesSupNo = totalMatrix.loc['Yes', 'No']
    stuNoSupYes = totalMatrix.loc['No', 'Yes']
    disagreement = {'Student Yes - Supervisor No': stuYesSupNo, 'Student No - Supervisor Yes': stuNoSupYes}
    return totalMatrix, disagreement

def getStudentCfMatrices(dfItem):
    studentMatrices = {}
    disagreements = {}
    for studentId in dfItem[colId].unique():
        dfStudent = dfItem[dfItem[colId] == studentId]
        matrix, disagreement = createCfMatrix(dfStudent)
        studentMatrices[studentId] = matrix
        disagreements[studentId] = disagreement
    return studentMatrices, disagreements

In [ ]:
import pandas as pd
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.styles import Font

def saveAllMatricesInOneWorkbook(clinicDict, outputPath):
    wb = Workbook()
    wb.remove(wb.active)  # Remove default sheet

    for clinicType, matrixDict in clinicDict.items():
        ws = wb.create_sheet(title=str(clinicType)[:31])  # Excel sheet names max 31 chars

        for studentId, matrix in matrixDict.items():
            # Title row
            ws.append([f"Confusion Matrix for {studentId}"])
            ws.merge_cells(start_row=ws.max_row, start_column=1, end_row=ws.max_row, end_column=4)
            titleCell = ws.cell(row=ws.max_row, column=1)
            titleCell.font = Font(bold=True)

            # Matrix with headers
            matrix.index.name = "Student\\Supervisor"
            for row in dataframe_to_rows(matrix, index=True, header=True):
                ws.append(row)

            ws.append([])  # Blank line between students

    wb.save(outputPath)


def createCfandDisagreementReports(dfExploded, type_='Clinic'):
    clinicDict = {}
    dfClinicExploded = dfExploded[dfExploded['type'] == type_]
    disagreementFilePath = f'{savefolder}/Disagreements_ {type_} ({today}).xlsx'
    if os.path.exists(disagreementFilePath):
        os.remove(disagreementFilePath)
    writer_kwargs = getmodeArgs(disagreementFilePath)
    print(f"Saving disagreements to {disagreementFilePath}, writer_kwargs: {writer_kwargs}")
    with pd.ExcelWriter(disagreementFilePath, **writer_kwargs) as writer:
        for clinicType in dfClinicExploded[colClinicType].unique():
            dfClinicType = dfClinicExploded[dfClinicExploded[colClinicType] == clinicType]
            matrixDict, disagreements = getStudentCfMatrices(dfClinicType)
            # save disagreements to excel
            disagreementDf = pd.DataFrame.from_dict(disagreements, orient='index')
            disagreementDf['Student Name'] = disagreementDf.index.map(idNameMapping)    
            disagreementDf.reset_index(inplace=True)
            disagreementDf.rename(columns={'index': colId}, inplace=True)
            # reorder columns to put colId and Student Name first dynamically
            cols = [colId, 'Student Name'] + [col for col in disagreementDf.columns if col not in [colId, 'Student Name']]
            disagreementDf = disagreementDf[cols]
            display(disagreementDf.head())
            disagreementDf.to_excel(writer, sheet_name=str(clinicType)[:31])
            clinicDict[clinicType] = matrixDict
    saveAllMatricesInOneWorkbook(clinicDict, outputPath=f'{savefolder}/Cf Matrices {type_} ({today}).xlsx')

createCfandDisagreementReports(dfExploded, type_='Clinic')
# createCfandDisagreementReports(dfExploded, type_='Simulation')

Saving disagreements to 2025\BOH2/NewDataInfo/03-12-2025/Disagreements_ Clinic (03-12-2025).xlsx, writer_kwargs: {'engine': 'openpyxl', 'mode': 'w'}

,Student ID,Student Name,Student Yes - Supervisor No,Student No - Supervisor Yes
0,1616745,Rida Ali,0,0
1,1637288,Ivan Yang,0,0
2,1615333,Annie Phung,0,0
3,1610017,Rachel Chong,0,0
4,1466081,Harlean Kaur,0,0

Saving disagreements to 2025\BOH2/NewDataInfo/03-12-2025/Disagreements_ Simulation (03-12-2025).xlsx, writer_kwargs: {'engine': 'openpyxl', 'mode': 'w'}

IndexError: At least one sheet must be visible

In [28]:
def getCountInfo(dfExploded, type_, savefolder):
    if 'type' not in dfExploded.columns:
        dfType  = dfExploded.copy()  # no filtering if no type column
    else:
        dfType= dfExploded[dfExploded['type'] == type_]  # filter for simulation type

    # save the exploded dataframe with scores to excel
    dfType['Scores'] = dfType['Scores'].apply(lambda x: json.dumps(x, indent=2, ensure_ascii=False))
    dfType['student_data'] = dfType['student_data'].apply(lambda x: json.dumps(x, indent=2, ensure_ascii=False))
    dfType['supervisor_data'] = dfType['supervisor_data'].apply(lambda x: json.dumps(x, indent=2, ensure_ascii=False))
    # save the exploded dataframe with sections to excel
    # dfType.to_excel(f'{folder}\\ExplodedDataWithSections({today}).xlsx', index=False)

    # create a pivot table for student Id and item code with counts
    dfType['Item Code'] = dfType['Item Code'].astype(str)  # Ensure Item Code is string type
    # Pivot table with count of each item code per student
    # Pivot with multi-level columns: Section → Item Code
    dfPivot = dfType.pivot_table(
        index=['Student ID', 'Student Name'],
        columns=['Section', 'Item Code'],
        values='assessment_id' if 'assessment_id' in dfType.columns else 'ResponseId',
        aggfunc='count',
        fill_value=0
    )
    pivotfilepath = f'{savefolder}\\CodeCountPivotTable ({today}).xlsx'
    writer_kwargs = getmodeArgs(pivotfilepath)
    # dfPivot['Student Name'] = dfPivot.index.map(idNameMapping)
    dfPivot = dfPivot.reset_index()
    with pd.ExcelWriter(pivotfilepath, **writer_kwargs) as writer:
        dfPivot.to_excel(writer, sheet_name=type_)

    # Group by Student ID, Section, and Item Code for score pivot table
    aggDf = dfType.groupby(['Student ID', 'Student Name', 'Section', 'Item Code', 'ES'])[['Yes', 'No']].sum().reset_index()

    # Compute % Yes from aggregated values
    aggDf['% Yes'] = ((aggDf['Yes'] / (aggDf['Yes'] + aggDf['No'])) * 100).round(2)

    # Create pivot table with Section > Item Code as column MultiIndex
    pivotTable = aggDf.pivot_table(
        index=['Student ID', 'Student Name'],
        columns=['Section', 'Item Code'],
        values='% Yes',
        aggfunc='first',  # one value per (student, section, item)
        fill_value=np.nan
    )
    # pivotTable['Student Name'] = pivotTable.index.map(idNameMapping)
    pivotTable = pivotTable.reset_index()
    writer_kwargs = getmodeArgs(pivotfilepath)
    with pd.ExcelWriter(pivotfilepath, **writer_kwargs) as writer:
        pivotTable.to_excel(writer, sheet_name=f'{type_} % Yes')

    # create pivot table with average ES per item code per student
    esPivotTable = dfType.pivot_table(
        index=['Student ID', 'Student Name'],
        columns=['Section', 'Item Code'],
        values='ES',
        aggfunc='mean',
        fill_value=np.nan
    )
    # esPivotTable['Student Name'] = esPivotTable.index.map(idNameMapping)
    # round to 2 decimal places
    esPivotTable = esPivotTable.round(2)
    esPivotTable = esPivotTable.reset_index()
    writer_kwargs = getmodeArgs(pivotfilepath)
    with pd.ExcelWriter(pivotfilepath, **writer_kwargs) as writer:
        esPivotTable.to_excel(writer, sheet_name=f'{type_} Average ES')

    # for each section, get the count of item codes 
    # Count occurrences of each Item Code within each Section
    sectionItemCodeCounts = dfType.groupby(['Section', 'Item Code']).size().reset_index(name='Count')

    # Display result
    # display(sectionItemCodeCounts.head())
    # sort by Section and Count
    sectionItemCodeCounts.sort_values(by=['Section', 'Count'], ascending=[True, False], inplace=True)
    # Save to Excel
    sectionItemCodeCounts.to_excel(f'{savefolder}\\SectionItemCodeCounts {type_} ({today}).xlsx', index=False)
    return dfType

# savefolder = f'{folder}/NewDataInfo'

os.makedirs(savefolder, exist_ok=True)
# getCountInfo(dfExploded, 'Simulation', savefolder)
getCountInfo(dfExploded, 'Clinic', savefolder)
pass

In [29]:
# Get student IDs
studentIds = dfExploded[colId].unique()
print(f"Total unique student IDs: {len(studentIds)}")
# sort student IDs
studentIds = sorted(studentIds)

# Define output file
def saveStudentWiseInfo(dfExploded, studentIds, type_, savefolder):
    if 'type' not in dfExploded.columns:
        dfType  = dfExploded.copy()  # no filtering if no type column
    else:
        dfType = dfExploded[dfExploded['type'] == type_]  # filter for simulation type
    outputFile = f'{savefolder}\\StudentData{type_} ({today}).xlsx'
    # if os.path.exists(outputFile):
    #     os.remove(outputFile)

    # Safe sheet name helper
    def safeSheetName(name):
        name = re.sub(r'[\\/*?:\[\]]', '', name)  # remove invalid characters
        return name[:31]  # Excel sheet name max length

    usedNames = set()

    if type_ == 'Simulation':
        typedropcols = [ 'role', 'clinic', 'pateint_age', 'patient_drn','patient_details', 'patient_interpreter',
                        'Patient Complexity', 'fta_substitute', 'student_role', 'clinic_type'	,'patient_status',	'teeth_quadrant_info']
    elif type_ == 'Clinic':
        typedropcols=[]

    with pd.ExcelWriter(outputFile, engine='openpyxl') as writer:
        for studentId in studentIds:
            studentData = dfType[dfType[colId] == studentId]
            studentData.drop(columns = ['Scores', 'data', 'scales', 'checklists', 'assessor_id', 'additional_checklists',
                                        'student_data', 'supervisor_data', 'Unnamed: 0'] + typedropcols, inplace=True, errors='ignore')
            colsToMove = [colTS, colPS, colCS, colES]
            studentData = studentData[[col for col in studentData.columns if col not in colsToMove] + colsToMove]
            colsToMove = [colCI, colAssessorFeedback, colStudentFeedback]

            # Reorder columns
            studentData = studentData[[col for col in studentData.columns if col not in colsToMove] + colsToMove]
            if not studentData.empty:
                studentName = studentData[colName].values[0]
                baseName = f"{studentId} ({studentName})"
                sheetName = safeSheetName(baseName)

                # Ensure uniqueness
                suffix = 1
                while sheetName in usedNames:
                    sheetName = safeSheetName(f"{baseName}_{suffix}")
                    suffix += 1

                usedNames.add(sheetName)

                print(f"Saving data for {sheetName}")
                studentData.to_excel(writer, sheet_name=sheetName, index=False)
            else:
                print(f"No data found for Student ID: {studentId}")

# saveStudentWiseInfo(dfExploded, studentIds, 'Simulation', savefolder)
saveStudentWiseInfo(dfExploded, studentIds, 'Clinic', savefolder)
pass

Total unique student IDs: 44
Saving data for 1146177 (Daniella Icho Malak)
Saving data for 1295910 (Sabiha Faizi)
Saving data for 1352051 (Ayesha Riaz)
Saving data for 1430664 (tara zare)
Saving data for 1461457 (Jade Rosenberg)
Saving data for 1466081 (Harlean Kaur)
Saving data for 1469076 (Anson Koo)
Saving data for 1472447 (Jasmeet Kaur)
Saving data for 1472800 (Phong Pham)
Saving data for 1472831 (Usman Majoo)
Saving data for 1473072 (Uthman Abdul-Rahman)
Saving data for 1535538 (Qiwen Xue)
Saving data for 1594851 (Chuling LI)
Saving data for 1594958 (Dalena Nguyen)
Saving data for 1600923 (Jiahua YAN)
Saving data for 1605390 (Vianna Tran)
Saving data for 1605480 (Gabrielle Le)
Saving data for 1605677 (Sally Sang)
Saving data for 1605793 (steven hanna)
Saving data for 1606071 (Halima Fiqi)
Saving data for 1606077 (aida yosufi)
Saving data for 1606096 (Aidah Khan)
Saving data for 1606153 (Valantina AL-Zeebaree)
Saving data for 1606158 (Samantha Chim)
Saving data for 1608030 (Zipei Cheng)
Saving data for 1610017 (Rachel Chong)
Saving data for 1615131 (Katie Nguyen)
Saving data for 1615261 (supriya shrestha)
Saving data for 1615333 (Annie Phung)
Saving data for 1616141 (Kate McLennan Arnott)
Saving data for 1616618 (Bubby Tereva)
Saving data for 1616745 (Rida Ali)
Saving data for 1617003 (Jovilia Gracilla Verga
Saving data for 1617304 (Somaya Sarwari)
Saving data for 1617334 (Razan Kamarelddin)
Saving data for 1617587 (Sujin Ahn)
Saving data for 1617958 (Lucia Williams)
Saving data for 1624825 (Christina Golets)
Saving data for 1625104 (Lydia Faranso)
Saving data for 1625191 (Xiaoru (Helen) Mai)
Saving data for 1625619 (ella watts)
Saving data for 1634259 (Hilda Petros)
Saving data for 1637288 (Ivan Yang)
Saving data for 1637313 (Moe Myint Tha)

In [30]:
# for each student, creata a more processed dataframe and save to excel file one for each student

def processStudentData(studentData: pd.DataFrame, threshold=80):
    if studentData.empty:
        return pd.DataFrame()

    # Sort for visual clarity
    studentData.sort_values(by=['Section', 'Sub-section'], inplace=True)

    # ---------- Section + Sub-section Level ----------
    groupSubsection = studentData.groupby(['Section', 'Sub-section'], dropna=False)[['Yes', 'No', 'NA']].sum().reset_index()
    groupSubsection['Total'] = groupSubsection['Yes'] + groupSubsection['No']
    groupSubsection['% Yes'] = groupSubsection.apply(
        lambda row: (row['Yes'] / row['Total'] * 100) if row['Total'] > 0 else None, axis=1
    )
    groupSubsection['Below Threshold'] = groupSubsection['% Yes'].apply(
        lambda x: 'Yes' if x is not None and x < threshold else 'No'
    )

    # ---------- Section-Only Aggregation ----------
    groupSection = studentData.groupby('Section')[['Yes', 'No', 'NA']].sum().reset_index()
    groupSection['Sub-section'] = 'All'
    groupSection['Total'] = groupSection['Yes'] + groupSection['No']
    groupSection['% Yes'] = groupSection.apply(
        lambda row: (row['Yes'] / row['Total'] * 100) if row['Total'] > 0 else None, axis=1
    )
    groupSection['Below Threshold'] = groupSection['% Yes'].apply(
        lambda x: 'Yes' if x is not None and x < threshold else 'No'
    )

    # Reorder columns
    groupSection = groupSection[['Section', 'Sub-section', 'Yes', 'No', 'NA', 'Total', '% Yes', 'Below Threshold']]
    groupSubsection = groupSubsection[['Section', 'Sub-section', 'Yes', 'No', 'NA', 'Total', '% Yes', 'Below Threshold']]

    # ---------- Combine ----------
    combined = pd.concat([groupSection, groupSubsection]).sort_values(by=['Section', 'Sub-section'])

    return combined


for studentId in studentIds:
    studentData = dfExploded[dfExploded[colId] == studentId]
    studentName = studentData[colName].values[0] if not studentData.empty else 'Unknown'
    print(f"Processing data for Student ID: {studentId} ({studentName})")
    outputFolder = f'{savefolder}\\ProcessedData'
    
    if not os.path.exists(outputFolder):
        os.makedirs(outputFolder)
    outputFile = f'{outputFolder}\\{studentName} ({studentId}).xlsx'
    
    if not studentData.empty:
        processedData = processStudentData(studentData)
        if not processedData.empty:
            processedData.to_excel(outputFile, index=False)
        else:
            print(f"No valid data to process for Student ID: {studentId}")
    else:
        print(f"No data found for Student ID: {studentId}")
    # break  # remove this to process all students

Processing data for Student ID: 1146177 (Daniella Icho Malak)
Processing data for Student ID: 1295910 (Sabiha Faizi)
Processing data for Student ID: 1352051 (Ayesha Riaz)
Processing data for Student ID: 1430664 (tara zare)
Processing data for Student ID: 1461457 (Jade Rosenberg)
Processing data for Student ID: 1466081 (Harlean Kaur)
Processing data for Student ID: 1469076 (Anson Koo)
Processing data for Student ID: 1472447 (Jasmeet Kaur)
Processing data for Student ID: 1472800 (Phong Pham)
Processing data for Student ID: 1472831 (Usman Majoo)
Processing data for Student ID: 1473072 (Uthman Abdul-Rahman)
Processing data for Student ID: 1535538 (Qiwen Xue)
Processing data for Student ID: 1594851 (Chuling LI)
Processing data for Student ID: 1594958 (Dalena Nguyen)
Processing data for Student ID: 1600923 (Jiahua YAN)
Processing data for Student ID: 1605390 (Vianna Tran)
Processing data for Student ID: 1605480 (Gabrielle Le)
Processing data for Student ID: 1605677 (Sally Sang)
Processing data for Student ID: 1605793 (steven hanna)
Processing data for Student ID: 1606071 (Halima Fiqi)
Processing data for Student ID: 1606077 (aida yosufi)
Processing data for Student ID: 1606096 (Aidah Khan)
Processing data for Student ID: 1606153 (Valantina AL-Zeebaree)
Processing data for Student ID: 1606158 (Samantha Chim)
Processing data for Student ID: 1608030 (Zipei Cheng)
Processing data for Student ID: 1610017 (Rachel Chong)
Processing data for Student ID: 1615131 (Katie Nguyen)
Processing data for Student ID: 1615261 (supriya shrestha)
Processing data for Student ID: 1615333 (Annie Phung)
Processing data for Student ID: 1616141 (Kate McLennan Arnott)
Processing data for Student ID: 1616618 (Bubby Tereva)
Processing data for Student ID: 1616745 (Rida Ali)
Processing data for Student ID: 1617003 (Jovilia Gracilla Vergara)
Processing data for Student ID: 1617304 (Somaya Sarwari)
Processing data for Student ID: 1617334 (Razan Kamarelddin)
Processing data for Student ID: 1617587 (Sujin Ahn)
Processing data for Student ID: 1617958 (Lucia Williams)
Processing data for Student ID: 1624825 (Christina Golets)
Processing data for Student ID: 1625104 (Lydia Faranso)
Processing data for Student ID: 1625191 (Xiaoru (Helen) Mai)
Processing data for Student ID: 1625619 (ella watts)
Processing data for Student ID: 1634259 (Hilda Petros)
Processing data for Student ID: 1637288 (Ivan Yang)
Processing data for Student ID: 1637313 (Moe Myint Tha)

In [31]:
metricOrder = ['Yes', 'No', 'NA', '% Yes']
def colSortKey(col):
    section, subsection, metric = col
    return (
        section,
        subsection == 'All',  # False first, then True → 'All' comes last
        subsection,
        metricOrder.index(metric) if metric in metricOrder else len(metricOrder)
    )

def processStudentMultiHeaderRow(studentData: pd.DataFrame, studentId, studentName: str):
    if studentData.empty:
        return pd.DataFrame(), None

    # Group by Section and Sub-section
    group = studentData.groupby(['Section', 'Sub-section'], dropna=False)[['Yes', 'No', 'NA']].sum().copy()

    # Compute '% Yes'
    group['% Yes'] = group.apply(
        lambda row: round((row['Yes'] / (row['Yes'] + row['No']) * 100), 2) if (row['Yes'] + row['No']) > 0 else 0.0,
        axis=1
    )

    # ---------- Add "All" Sub-section per Section ----------
    groupAll = group.groupby(level=0)[['Yes', 'No', 'NA']].sum()
    groupAll['% Yes'] = groupAll.apply(
        lambda row: round((row['Yes'] / (row['Yes'] + row['No']) * 100), 2) if (row['Yes'] + row['No']) > 0 else 0.0,
        axis=1
    )
    groupAll['Sub-section'] = 'All'
    groupAll.reset_index(inplace=True)
    groupAll.set_index(['Section', 'Sub-section'], inplace=True)

    # Combine with original
    group = pd.concat([group, groupAll]).sort_index()

    # Stack → Pivot to wide with correct metric order
    stacked = group.stack().reset_index()
    stacked.columns = ['Section', 'Sub-section', 'Metric', 'Value']


    stacked['Metric'] = pd.Categorical(stacked['Metric'], categories=metricOrder, ordered=True)
    stacked.sort_values(['Section', 'Sub-section', 'Metric'], inplace=True)

    wideDf = stacked.pivot_table(index=None, 
                                 columns=['Section', 'Sub-section', 'Metric'], 
                                 values='Value', 
                                 fill_value=0)

    sortedColumns = sorted(wideDf.columns, key=colSortKey)
    print(f"Sorted columns: {sortedColumns}")
    # Add student info
    wideDf[('Info', '', 'StudentID')] = studentId
    wideDf[('Info', '', 'StudentName')] = studentName
    wideDf = wideDf[[('Info', '', 'StudentID'), ('Info', '', 'StudentName')]]\
             .join(wideDf.drop(columns=[('Info', '', 'StudentID'), ('Info', '', 'StudentName')]))

    return wideDf, wideDf.columns



def createmultiHeaderExcel(dfExploded, savefolder, type_=None):

    allRows = []
    allColumns = None
    if type_ is not None:
        dfExploded = dfExploded[dfExploded['type'] == type_]
    for studentId in studentIds:
        studentData = dfExploded[dfExploded[colId] == studentId]
        studentName = studentData[colName].values[0] if not studentData.empty else 'Unknown'
        print(f"Processing Student ID: {studentId} ({studentName})")

        rowDf, colMultiIndex = processStudentMultiHeaderRow(studentData, studentId, studentName)
        if rowDf is not None:
            allRows.append(rowDf)
            if allColumns is None:
                allColumns = colMultiIndex

    # Combine all rows
    finalDf = pd.concat(allRows, ignore_index=True)
    infoCols = [('Info', '', 'StudentID'), ('Info', '', 'StudentName')]

    # Sort only non-info columns
    otherCols = sorted([col for col in finalDf.columns if col not in infoCols], key=colSortKey)

    # Rebuild columns in correct order
    finalDf = finalDf[infoCols + otherCols]

    # Save with multi-index columns
    outputPath = f'{savefolder}\\AllStudents_Sectionwise.xlsx'
    writer_kwargs = getmodeArgs(outputPath)
    with pd.ExcelWriter(outputPath, **writer_kwargs) as writer:
        finalDf.to_excel(writer, header=True, sheet_name=type_ if type_ else 'All')
    print(f"Saved to {outputPath}")

# createmultiHeaderExcel(dfExploded, savefolder, type_='Simulation')
createmultiHeaderExcel(dfExploded, savefolder, type_='Clinic')
# createmultiHeaderExcel(dfExploded, savefolder, type_=None)

Processing Student ID: 1146177 (Daniella Icho Malak)
Sorted columns: [('Diagnostics', 'Examinations', 'Yes'), ('Diagnostics', 'Examinations', 'No'), ('Diagnostics', 'Examinations', 'NA'), ('Diagnostics', 'Examinations', '% Yes'), ('Diagnostics', 'All', 'Yes'), ('Diagnostics', 'All', 'No'), ('Diagnostics', 'All', 'NA'), ('Diagnostics', 'All', '% Yes'), ('Miscellaneous', 'Miscellaneous', 'Yes'), ('Miscellaneous', 'Miscellaneous', 'No'), ('Miscellaneous', 'Miscellaneous', 'NA'), ('Miscellaneous', 'Miscellaneous', '% Yes'), ('Miscellaneous', 'All', 'Yes'), ('Miscellaneous', 'All', 'No'), ('Miscellaneous', 'All', 'NA'), ('Miscellaneous', 'All', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'All', '% Yes')]
Processing Student ID: 1295910 (Sabiha Faizi)
Sorted columns: [('Diagnostics', 'Examinations', 'Yes'), ('Diagnostics', 'Examinations', 'No'), ('Diagnostics', 'Examinations', 'NA'), ('Diagnostics', 'Examinations', '% Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'No'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'NA'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', '% Yes'), ('Diagnostics', 'All', 'Yes'), ('Diagnostics', 'All', 'No'), ('Diagnostics', 'All', 'NA'), ('Diagnostics', 'All', '% Yes'), ('Miscellaneous', 'Miscellaneous', 'Yes'), ('Miscellaneous', 'Miscellaneous', 'No'), ('Miscellaneous', 'Miscellaneous', 'NA'), ('Miscellaneous', 'Miscellaneous', '% Yes'), ('Miscellaneous', 'All', 'Yes'), ('Miscellaneous', 'All', 'No'), ('Miscellaneous', 'All', 'NA'), ('Miscellaneous', 'All', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'All', '% Yes')]
Processing Student ID: 1352051 (Ayesha Riaz)
Sorted columns: [('Diagnostics', 'Examinations', 'Yes'), ('Diagnostics', 'Examinations', 'No'), ('Diagnostics', 'Examinations', 'NA'), ('Diagnostics', 'Examinations', '% Yes'), ('Diagnostics', 'All', 'Yes'), ('Diagnostics', 'All', 'No'), ('Diagnostics', 'All', 'NA'), ('Diagnostics', 'All', '% Yes'), ('Miscellaneous', 'Miscellaneous', 'Yes'), ('Miscellaneous', 'Miscellaneous', 'No'), ('Miscellaneous', 'Miscellaneous', 'NA'), ('Miscellaneous', 'Miscellaneous', '% Yes'), ('Miscellaneous', 'All', 'Yes'), ('Miscellaneous', 'All', 'No'), ('Miscellaneous', 'All', 'NA'), ('Miscellaneous', 'All', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'All', '% Yes')]
Processing Student ID: 1430664 (tara zare)
Sorted columns: [('Diagnostics', 'Examinations', 'Yes'), ('Diagnostics', 'Examinations', 'No'), ('Diagnostics', 'Examinations', 'NA'), ('Diagnostics', 'Examinations', '% Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'No'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'NA'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', '% Yes'), ('Diagnostics', 'All', 'Yes'), ('Diagnostics', 'All', 'No'), ('Diagnostics', 'All', 'NA'), ('Diagnostics', 'All', '% Yes'), ('Miscellaneous', 'Miscellaneous', 'Yes'), ('Miscellaneous', 'Miscellaneous', 'No'), ('Miscellaneous', 'Miscellaneous', 'NA'), ('Miscellaneous', 'Miscellaneous', '% Yes'), ('Miscellaneous', 'All', 'Yes'), ('Miscellaneous', 'All', 'No'), ('Miscellaneous', 'All', 'NA'), ('Miscellaneous', 'All', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'All', '% Yes')]
Processing Student ID: 1461457 (Jade Rosenberg)
Sorted columns: [('Diagnostics', 'Examinations', 'Yes'), ('Diagnostics', 'Examinations', 'No'), ('Diagnostics', 'Examinations', 'NA'), ('Diagnostics', 'Examinations', '% Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'No'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'NA'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', '% Yes'), ('Diagnostics', 'All', 'Yes'), ('Diagnostics', 'All', 'No'), ('Diagnostics', 'All', 'NA'), ('Diagnostics', 'All', '% Yes'), ('Miscellaneous', 'Miscellaneous', 'Yes'), ('Miscellaneous', 'Miscellaneous', 'No'), ('Miscellaneous', 'Miscellaneous', 'NA'), ('Miscellaneous', 'Miscellaneous', '% Yes'), ('Miscellaneous', 'All', 'Yes'), ('Miscellaneous', 'All', 'No'), ('Miscellaneous', 'All', 'NA'), ('Miscellaneous', 'All', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'All', '% Yes')]
Processing Student ID: 1466081 (Harlean Kaur)
Sorted columns: [('Diagnostics', 'Examinations', 'Yes'), ('Diagnostics', 'Examinations', 'No'), ('Diagnostics', 'Examinations', 'NA'), ('Diagnostics', 'Examinations', '% Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'No'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'NA'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', '% Yes'), ('Diagnostics', 'All', 'Yes'), ('Diagnostics', 'All', 'No'), ('Diagnostics', 'All', 'NA'), ('Diagnostics', 'All', '% Yes'), ('Miscellaneous', 'Miscellaneous', 'Yes'), ('Miscellaneous', 'Miscellaneous', 'No'), ('Miscellaneous', 'Miscellaneous', 'NA'), ('Miscellaneous', 'Miscellaneous', '% Yes'), ('Miscellaneous', 'All', 'Yes'), ('Miscellaneous', 'All', 'No'), ('Miscellaneous', 'All', 'NA'), ('Miscellaneous', 'All', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'All', '% Yes')]
Processing Student ID: 1469076 (Anson Koo)
Sorted columns: [('Diagnostics', 'Examinations', 'Yes'), ('Diagnostics', 'Examinations', 'No'), ('Diagnostics', 'Examinations', 'NA'), ('Diagnostics', 'Examinations', '% Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'No'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'NA'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', '% Yes'), ('Diagnostics', 'All', 'Yes'), ('Diagnostics', 'All', 'No'), ('Diagnostics', 'All', 'NA'), ('Diagnostics', 'All', '% Yes'), ('Miscellaneous', 'Miscellaneous', 'Yes'), ('Miscellaneous', 'Miscellaneous', 'No'), ('Miscellaneous', 'Miscellaneous', 'NA'), ('Miscellaneous', 'Miscellaneous', '% Yes'), ('Miscellaneous', 'All', 'Yes'), ('Miscellaneous', 'All', 'No'), ('Miscellaneous', 'All', 'NA'), ('Miscellaneous', 'All', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'All', '% Yes')]
Processing Student ID: 1472447 (Jasmeet Kaur)
Sorted columns: [('Diagnostics', 'Examinations', 'Yes'), ('Diagnostics', 'Examinations', 'No'), ('Diagnostics', 'Examinations', 'NA'), ('Diagnostics', 'Examinations', '% Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'No'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'NA'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', '% Yes'), ('Diagnostics', 'All', 'Yes'), ('Diagnostics', 'All', 'No'), ('Diagnostics', 'All', 'NA'), ('Diagnostics', 'All', '% Yes'), ('Miscellaneous', 'Miscellaneous', 'Yes'), ('Miscellaneous', 'Miscellaneous', 'No'), ('Miscellaneous', 'Miscellaneous', 'NA'), ('Miscellaneous', 'Miscellaneous', '% Yes'), ('Miscellaneous', 'All', 'Yes'), ('Miscellaneous', 'All', 'No'), ('Miscellaneous', 'All', 'NA'), ('Miscellaneous', 'All', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Dental Prophylaxis and Bleaching', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'All', '% Yes')]
Processing Student ID: 1472800 (Phong Pham)
Sorted columns: [('Diagnostics', 'Examinations', 'Yes'), ('Diagnostics', 'Examinations', 'No'), ('Diagnostics', 'Examinations', 'NA'), ('Diagnostics', 'Examinations', '% Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'Yes'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'No'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', 'NA'), ('Diagnostics', 'Radiological Examination, Analysis and Interpretation', '% Yes'), ('Diagnostics', 'All', 'Yes'), ('Diagnostics', 'All', 'No'), ('Diagnostics', 'All', 'NA'), ('Diagnostics', 'All', '% Yes'), ('Miscellaneous', 'Miscellaneous', 'Yes'), ('Miscellaneous', 'Miscellaneous', 'No'), ('Miscellaneous', 'Miscellaneous', 'NA'), ('Miscellaneous', 'Miscellaneous', '% Yes'), ('Miscellaneous', 'All', 'Yes'), ('Miscellaneous', 'All', 'No'), ('Miscellaneous', 'All', 'NA'), ('Miscellaneous', 'All', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Other Preventive Services', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'All', '% Yes')]
Processing Student ID: 1472831 (Usman Majoo)
Sorted columns: [('Diagnostics', 'Examinations', 'Yes'), ('Diagnostics', 'Examinations', 'No'), ('Diagnostics', 'Examinations', 'NA'), ('Diagnostics', 'Examinations', '% Yes'), ('Diagnostics', 'All', 'Yes'), ('Diagnostics', 'All', 'No'), ('Diagnostics', 'All', 'NA'), ('Diagnostics', 'All', '% Yes'), ('Miscellaneous', 'Miscellaneous', 'Yes'), ('Miscellaneous', 'Miscellaneous', 'No'), ('Miscellaneous', 'Miscellaneous', 'NA'), ('Miscellaneous', 'Miscellaneous', '% Yes'), ('Miscellaneous', 'All', 'Yes'), ('Miscellaneous', 'All', 'No'), ('Miscellaneous', 'All', 'NA'), ('Miscellaneous', 'All', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'Remineralisation Agents', '% Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'Yes'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'No'), ('Preventive, Prophylactic and Bleaching Services', 'All', 'NA'), ('Preventive, Prophylactic and Bleaching Services', 'All', '% Yes')]
Processing Student ID: 1473072 (Uthman Abdul-Rahman)

### Data summary collection

#### Collecting patient counts and code counts

In [ ]:
df = pd.read_excel(f'{folder}/all data scores_combined.xlsx')
# get student count for each patient status
studentPatientCounts = df.groupby([colId, 'role']).size().reset_index(name='Patient Count')
# sort by student ID
studentPatientCounts[colId] = studentPatientCounts[colId].astype(int)
studentPatientCounts.sort_values(by=colId, inplace=True)
studentPatientCounts = studentPatientCounts[studentPatientCounts['role'] == 'Operator']
display(studentPatientCounts)
# get min max and mean of patient count
minPatientCount = studentPatientCounts['Patient Count'].min()
maxPatientCount = studentPatientCounts['Patient Count'].max()
meanPatientCount = studentPatientCounts['Patient Count'].mean()
print(f'Min Patient Count: {minPatientCount}, Max Patient Count: {maxPatientCount}, Mean Patient Count: {meanPatientCount:.2f}')

In [ ]:
# get item codes list for all rows
def get_item_code_counts(df):
    """
    Extracts item codes from the 'Item Codes' column, flattens the list, and returns a DataFrame of counts.
    """
    print(f'Extracting item codes from {len(df)} rows')
    itemCodesList = df['Item Codes'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x).sum()
    print(f'Item Codes List: {itemCodesList}')
    # get counts of each item code
    itemCodeCounts = pd.Series(itemCodesList).value_counts().reset_index()
    itemCodeCounts.columns = ['Item Code', 'Count']
    itemCodeCounts.sort_values(by='Count', ascending=False, inplace=True)
    display(itemCodeCounts.head(5))
    return itemCodeCounts

itemCodeCounts = get_item_code_counts(df)
display(itemCodeCounts)


# colClinicType = 'clinic_type'
# gpdf = df[(df[colClinicType] == 'General Practice')| (df[colClinicType] == 'GP')]
# itemCodeCounts = get_item_code_counts(gpdf)
# # display(itemCodeCounts)

# periodf = df[(df[colClinicType] == 'Periodontics')| (df[colClinicType] == 'Perio')]
# itemCodeCounts = get_item_code_counts(periodf)
# # display(itemCodeCounts)

# remprosdf = df[(df[colClinicType] == 'Rem Pros')]
# itemCodeCounts = get_item_code_counts(remprosdf)
# display(itemCodeCounts)

In [ ]:
# get trends in entrustment levels
# get counts of each entrustment level for each student
def getEntrustmentTrends(df, colRubric=colES):
    # get counts of each entrustment level for each student
    entrustmentcounts = df.groupby([colRubric]).size()
    entrustmentcounts = entrustmentcounts.reset_index(name='Count')
    entrustmentcounts.rename(columns={colRubric: 'Entrustment Level'}, inplace=True)
    entrustmentcounts.sort_values(by='Count', ascending=False, inplace=True)
    display(entrustmentcounts.head())
getEntrustmentTrends(df, colRubric=colES)

### DDS2 patient analysis

In [ ]:
df['Item Codes'] = df['supervisor_data'].apply(extractCodes)
dfclinic = df[df['type']=='Clinic']
def getbarchart(df, colpie):
    pieData = df[colpie].value_counts()
    pieData = pieData.reset_index()
    # pieData.rename(columns={'index': colpie, colpie: 'Counts'}, inplace=True)
    # pieData['%'] = (pieData['Counts'] / pieData['Counts'].sum()) * 100
    total = pieData['count'].sum()
    display(pieData.head())

    fig, ax = plt.subplots(figsize=(figSize[0], figSize[1]*0.45))
    ax.bar(pieData[colpie], pieData['count'])
    # ax.set_xlabel(colpie)
    ax.set_ylabel("Count")
    ax.set_title(f"Distribution of {colpie}")
    for i, v in enumerate(pieData['count']):
        ax.text(i, v + 0.2, str(v), color='black', ha='center', fontsize=8)
    
    plt.xticks(rotation=45, fontsize=8)
    plt.tight_layout()

    return fig, pieData

figoverall,_ = getbarchart(dfclinic, 'patient_details')
img = addPlotImage(figoverall, 0.8)
colpatientstatus = 'patient_details'
doc = SimpleDocTemplate(f'{folder}\\DDS2 patient status report.pdf', pagesize=pageSize, rightMargin = rightMargin,
                        leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
elements = []
elements.append(KeepTogether([Paragraph('Patient Status Report overall', subheadingStyle), Spacer(1, 12), img]))
elements.append(Spacer(1, 36))
# get bar chart for each item code
allItems = dfclinic['Item Codes'].sum()
allItems = list(set(allItems))
for item in allItems:
    itemDf = dfclinic[dfclinic['Item Codes'].apply(lambda x: item in x)] # select rows where item is in Item Codes
    if itemDf.empty or len(itemDf) < 5:
        continue
    print(f'Item: {item}')
    display(itemDf.head())
    fig, pieData = getbarchart(itemDf, colpatientstatus)
    img = addPlotImage(fig, 0.8)
    # plt.show()
    title = Paragraph(f'Patient Status for {item}', subheadingStyle)
    elements.append(KeepTogether([title, Spacer(1, 12), img]))
    elements.append(Spacer(1, 36))

doc.build(elements)

# add a role column, I saw a patient maps to Operator, others map to Assistant
dfclinic['role'] = dfclinic[colpatientstatus].apply(lambda x: 'Operator' if 'I saw a patient' == x else 'Assistant')
# group by id
dfclinicgrouped = dfclinic.groupby([colId, 'role']).size().unstack(fill_value=0).reset_index()
dfclinicgrouped.columns.name = None  # Remove the index name
# dfclinicgrouped = dfclinicgrouped.rename_axis(None, axis=1)  # Remove the axis name
display(dfclinicgrouped.head())  
dfclinicgrouped['Student Name'] = dfclinicgrouped[colId].apply(lambda x: df[df[colId] == x][colName].values[0])
dfclinicgrouped = dfclinicgrouped[[colId, 'Student Name', 'Operator', 'Assistant']]
dfclinicgrouped.sort_values(by=['Operator', 'Assistant'], ascending=False, inplace=True)    
display(dfclinicgrouped.head())

dfclinicgrouped['% Operator'] = dfclinicgrouped['Operator'] / (dfclinicgrouped['Operator'] + dfclinicgrouped['Assistant']) * 100
dfclinicgrouped['% Operator'] = dfclinicgrouped['% Operator'].round(2)
display(dfclinicgrouped.head())

roletable = createTable(dfclinicgrouped, 'Student Role Counts', colRatio=[1.3, 1.7, 1, 1, 1], customTextCols=[1], bottomPadding=6, topPadding=6)
elements = []
elements.append(roletable)
doc2 = SimpleDocTemplate(f'{folder}\\DDS2 report by role.pdf', pagesize=pageSize, rightMargin = rightMargin,
                        leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
doc2.build(elements)

In [ ]:
def getWeeklyBarChart(df, colPie, dateCol='Date'):
    df[dateCol] = pd.to_datetime(df[dateCol], errors='coerce')
    df['Week'] = df[dateCol].dt.to_period('W').apply(lambda r: r.start_time)

    # Group and pivot
    weeklyCounts = df.groupby(['Week', colPie]).size().reset_index(name='count')
    pivotDf = weeklyCounts.pivot(index='Week', columns=colPie, values='count').fillna(0)
    pivotDf.index = pivotDf.index.strftime('%Y-%m-%d')
    newColumnOrder = ['I saw a patient', 'Failed to attend (FTA)', 'Patient cancelled within 24 hours','New patient block not filled',		'Unable to book a patient']
    pivotDf = pivotDf[newColumnOrder]
    display(pivotDf.head())
    fig, ax = plt.subplots(figsize=(figSize[0], figSize[1]))
    pivotDf.plot(kind='bar', stacked=True, ax=ax)

    ax.set_ylabel("Count")
    ax.set_title(f"Weekly Distribution of {colPie}")
    ax.legend(title=colPie)
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()

    return fig, pivotDf

figWeekly, _ = getWeeklyBarChart(dfclinic, 'patient_status', 'Date')
img = addPlotImage(figWeekly, 0.85)
elements = []
elements.append(KeepTogether([Paragraph('Weekly Patient Status Distribution', subheadingStyle), Spacer(1, 12), img]))

doc3 = SimpleDocTemplate(f'{folder}\\DDS2 weekly patient status report.pdf', pagesize=pageSize, rightMargin = rightMargin,
                        leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
doc3.build(elements)

### DDS2 examiner analysis

In [ ]:
# Examiner analysis:
import statsmodels.api as sm
from statsmodels.stats.multicomp import MultiComparison
import matplotlib.pyplot as plt
from scipy.stats import f_oneway, kruskal
from scipy.stats import pearsonr
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import matplotlib.cm as cm
from matplotlib.colors import to_hex
colAssessorName = 'Assessor Name'
workbookpath = '2025\DDS2\\all data scores_combined.xlsx'
# workbookpath = '2025\BOH2\Form 1\\all data scores.xlsx'
# workbookpath = '2025\BOH1\\all data scores.xlsx'
# workbookpath = '2025\\Viva\\DDS3\\all data scores_v2.xlsx'
folder, file, ext = getFolderandFileName(workbookpath)
df = pd.read_excel(workbookpath)
assessorDf = pd.DataFrame(columns=[colAssessorName, colId, colName, 'type',  'Date', 'Item', 'Yes', 'No', 'NA', 'Total MC', '% Yes', 'Weighted Score', 'Entrustment', colSubject])
df[colDate] = pd.to_datetime(df[colDate], errors='coerce', format='mixed').dt.date
for i, row in df.iterrows():
    scoreDict = json.loads(row['Scores'])
    assessorName = row[colAssessorName]
    studentName = row[colName]
    studentId = row[colId]
    for item, values in scoreDict.items():
        Yes = values['Yes']
        No = values['No']
        NA = values['NA']
        totMC = Yes + No + NA
        weightedScore = values.get('Weighted Score', np.nan)
        Yesper = values['% Yes']
        assessorDf = pd.concat([assessorDf, pd.DataFrame({colAssessorName: [assessorName], colId: [studentId], colName: [studentName], 'type': row.get('type', ''), 'Date': [row[colDate]], 'Item': [item],'Yes': [Yes], 'No': [No],
                                                           'NA': [NA],'Total MC': totMC, '% Yes': [Yesper], 'Weighted Score': [weightedScore], 'Entrustment': row[colES], colSubject: row[colSubject]})], ignore_index=True)

# sort by assessor name and student ID
assessorDf.sort_values(by=[colAssessorName, colId], inplace=True)
display(assessorDf.head(10))

assessorDf.to_excel(f'{folder}\\assessorDf.xlsx', index=False)

Linear effect model analysis

In [ ]:
import pandas as pd
import statsmodels.formula.api as smf
from statsmodels.formula.api import ols
from scipy.stats import chi2
import sys
# Load or define your dataframe
df = pd.read_excel(f'{folder}\\assessorDf.xlsx')  # if from file
os.makedirs(f'{folder}\\assessor analysis', exist_ok=True)
# Ensure numeric column
df['% Yes'] = pd.to_numeric(df['% Yes'], errors='coerce')
df = df.dropna(subset=["% Yes", "Assessor Name", "Student ID", "Item"]).copy()
# filter the DENT90148 entries
df = df[df[colSubject] == 'DENT90148']
confounding = pd.crosstab(df['Student ID'], df['Assessor Name'])
display(confounding.head(10))
confounding.to_excel(f'{folder}\\assessor analysis\\counfounding_assessor_student.xlsx', index=True)

# replace names with anonymous ids
def plotConfoundingHeatmap(confounding):    
    assessorNames = confounding.columns.tolist()
    assessorMap = {name: f'A{i+1}' for i, name in enumerate(assessorNames)}
    confounding.rename(columns=assessorMap, inplace=True)
    # replace student ids with anonymous ids
    studentIds = confounding.index.tolist()
    studentMap = {sid: f'S{i+1}' for i, sid in enumerate(studentIds)}
    confounding.rename(index=studentMap, inplace=True)
    # display(confounding.head(10))
    # Figure size (adjust depending on number of assessors/students)
    plt.figure(figsize=(18, 18))  

    # Heatmap
    sns.heatmap(
        confounding,              # use raw counts
        cmap="Blues",             # darker shade = higher frequency
        linewidths=0.5,           # gridlines between cells
        linecolor='grey',
        square=True,
        cbar_kws={"label": "Number of Assessments"}  # colorbar label
    )
    # Labels and formatting
    plt.title("Student–Assessor Pairing Presence", fontsize=16, pad=20)
    plt.xlabel("Assessor", fontsize=14)
    plt.ylabel("Student", fontsize=14)

    # Rotate x labels for readability
    plt.xticks(rotation=90, ha='center', fontsize=10)
    plt.yticks(fontsize=9)

    plt.savefig(f"{folder}\\assessor analysis\\student_assessor_pairing_heatmap.png", dpi=300, bbox_inches='tight')
    plt.show()

plotConfoundingHeatmap(confounding)
df['constantGroup'] = 'all'  # dummy group for compliance

model = smf.mixedlm(
    formula="Q('% Yes') ~ 1",
    data=df,
    groups=df["constantGroup"],  # required, but constant
    vc_formula={
        "Assessor": "0 + C(Q('Assessor Name'))",
        "Student": "0 + C(Q('Student ID'))",
        "Item": "0 + C(Item)"
    }
)
result = model.fit()
print("Full Model Summary:")
print(result.summary())


model_reduced = smf.mixedlm(
    formula="Q('% Yes') ~ 1",
    data=df,
    groups=df["constantGroup"],
    vc_formula={
        "Student": "0 + C(Q('Student ID'))",
        "Item": "0 + C(Item)"
    }
)
result_reduced = model_reduced.fit()
print("\nReduced Model Summary:")
print(result_reduced.summary())

# Compare log-likelihoods
from scipy.stats import chi2
lr_stat = 2 * (result.llf - result_reduced.llf)
p_val = chi2.sf(lr_stat, df=1)

print(f"\nLR Test for Assessor Effect: LR stat = {lr_stat:.3f}, p = {p_val:.5f}")


# === Save variance components as DataFrame ===
var_df = pd.DataFrame({
    "Component": ["Assessor Var", "Student Var", "Item Var"],
    "Variance_Full": result.vcomp,
    "Variance_Reduced": [0.0] + list(result_reduced.vcomp)  # no Assessor in reduced
})
var_df.to_excel(f"{folder}\\assessor analysis\\variance_components.xlsx", index=False)

# === Save Likelihood Ratio Test result ===
with open(f"{folder}\\assessor analysis\\likelihood_ratio_test.txt", "w") as f:
    f.write(f"LR Stat = {lr_stat:.3f}\n")
    f.write(f"P-value = {p_val:.5f}\n")

In [ ]:
# Treat them as categories
model = ols("Q('% Yes') ~ C(Q('Assessor Name')) + C(Q('Student ID')) + C(Item)", data=df).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print(anova_table)

In [ ]:
assessorDf= df.copy()
namemap = {name: f'A{i+1}' for i, name in enumerate(assessorDf[colAssessorName].unique())}
print("Renaming assessor names to dummy names..." + f" {namemap}")
assessorDf[colAssessorName] = assessorDf[colAssessorName].replace(namemap)
assessorDfClinic = assessorDf[assessorDf['type'] == 'Clinic']
assessorDfSimulation = assessorDf[assessorDf['type'] == 'Simulation']
display(assessorDfClinic.head())
display(assessorDfSimulation.head())
with open(f'{folder}\\assessor analysis\\namemap.json', 'w') as f:
    json.dump(namemap, f, indent=2)
print(assessorDf['Item'].value_counts())

In [ ]:

os.makedirs(f'{folder}\\assessor analysis', exist_ok=True)
def assessorAnalysis(df, item=None, colScore ='Weighted Score', type_ = 'Clinic'):
    if item and item!= 'All':
        df = df[df['Item'] == item]
    display(df.head())
    confounding = pd.crosstab(df['Student ID'], df['Assessor Name'])
    plotConfoundingHeatmap(confounding)
    # how many rows with not NA in the column
    print(f'Number of rows with not NA in the column {colScore}: {len(df[df[colScore].notna()])}')
    # change assessor names to dummy names assessor_1, assessor_2, etc.

    uniqueAssessors = df[colAssessorName].dropna().unique()
    # don't consider assessors with less than 10 entries
    uniqueAssessors = [assessor for assessor in uniqueAssessors if len(df[df[colAssessorName] == assessor]) >= 10]
    palette = sns.color_palette("hls", n_colors=len(uniqueAssessors))
    cmap = cm.get_cmap('tab20', len(uniqueAssessors))   
    colors = [to_hex(cmap(i)) for i in range(len(uniqueAssessors))]
    groupedDf = df.groupby([colAssessorName]).agg({'Yes': 'sum', 'No': 'sum', 'NA': 'sum', colScore: 'mean'}).reset_index()
    # display(groupedDf.head())
    groupedDf['% Yes'] = ((groupedDf['Yes'] / (groupedDf['Yes'] + groupedDf['No'])) * 100)
    groupedDf['% Yes'] = groupedDf['% Yes'].round(2)
    groupedDf['% Yes'] = pd.to_numeric(groupedDf['% Yes'], errors='coerce').round(2)
    display(groupedDf)

    if len(groupedDf) == 0:
        print(f"No data available for {item} ({type_})")
        return
    groupedDf.to_excel(f'{folder}\\assessor analysis\\assessor_{item}_yes ({type_}).xlsx', index=False)

    # plot a bar graph of the counts
    groupedDf.sort_values(by=['% Yes'], ascending=False, inplace=True)
    fig, ax = plt.subplots(figsize=(figSize[0]*1.5, figSize[1]*0.3))
    sns.barplot(x=groupedDf[colAssessorName], y=groupedDf['% Yes'], ax=ax)
    ax.set_title(f'Assessor % Yes Counts for {item} ({type_})' if item else f'Assessor % Yes Counts ({type_})')
    ax.set_xlabel('Assessors')
    ax.set_ylabel('% Yes')
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.set_xticklabels(ax.get_xticklabels(), rotation=90)
    for j, v in enumerate(groupedDf['% Yes']):   # show the counts on top of the bars
        ax.text(j, v + 2, str(v), color='black', ha='center', fontsize=8, rotation=90)
    ax.set_ylim(0, max(groupedDf['% Yes'])*1.2)  # Set y-axis limit to accommodate text
    plt.savefig(f'{folder}\\assessor analysis\\assessor_{item}_yes ({type_}).png', dpi=300, bbox_inches='tight')

    # plot distribution of % Yes for each assessor
    plt.figure(figsize=(10, 6))
    sns.kdeplot(data=df, x=colScore, hue=colAssessorName, linestyle='--', color=colors, fill=False)
    # a dotted kde for the overall distribution
    # sns.kdeplot(data=df, x=colScore, color='black', linestyle='-', label='Overall Distribution')
    plt.title(f"Distribution of Weighted Scores per Examiner {item} ({type_})" if item else f"Distribution of Weighted Scores per Examiner ({type_})")
    plt.xlabel("Weighted Score")
    plt.tight_layout()
    plt.savefig(f'{folder}\\assessor analysis\\assessor_{item}_distribution ({type_}).png', dpi=300, bbox_inches='tight')
    
    # box plot of weighted scores for each assessor
    mean_order = df.groupby(colAssessorName)[colScore].mean().sort_values(ascending=False).index
    plt.figure(figsize=(10, 6))
    sns.boxplot(data=df, x=colAssessorName, y=colScore, palette=colors, order=mean_order)
    plt.title(f"Box Plot of Weighted Scores per Examiner {item} ({type_})" if item else f"Box Plot of Weighted Scores per Examiner ({type_})")
    plt.xlabel("Examiner")
    plt.ylabel("Weighted Score")
    plt.xticks(rotation=90)
    plt.tight_layout()
    plt.savefig(f'{folder}\\assessor analysis\\assessor_{item}_boxplot ({type_}).png', dpi=300, bbox_inches='tight')

    # stats analysis
    grouped_scores = [group[colScore].dropna().values for name, group in df.groupby(colAssessorName)]

    # Perform One-Way ANOVA
    anova_stat, anova_p = f_oneway(*grouped_scores)

    # Perform Kruskal-Wallis H-test (non-parametric alternative to ANOVA)
    kruskal_stat, kruskal_p = kruskal(*grouped_scores)

    # Summary of results
    statistical_summary = pd.DataFrame({
        'Test': ['One-Way ANOVA', 'Kruskal-Wallis H'],
        'Test Statistic': [anova_stat, kruskal_stat],
        'p-value': [anova_p, kruskal_p]
    })

    display(statistical_summary)

    # Post-hoc analysis if ANOVA is significant
    if anova_p < 0.05:
        df.dropna(subset=[colScore], inplace=True)  # Ensure no NaN values in scores
        print(f"Performing Tukey's HSD post-hoc test for {item}" if item else "Performing Tukey's HSD post-hoc test")
        mc = MultiComparison(df[colScore], df[colAssessorName])
        tukey_result = mc.tukeyhsd()
        tukey_summary = pd.DataFrame(data=tukey_result._results_table.data[1:], columns=tukey_result._results_table.data[0])
        display(tukey_summary[tukey_summary['reject'] == True])
        savefile = f'{folder}\\assessor analysis\\assessor_anova_results.xlsx' if item else f'{folder}\\assessor analysis\\anova_results.xlsx'
        if os.path.exists(savefile):    
            with pd.ExcelWriter(savefile, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
                    tukey_summary[tukey_summary['reject'] == True].to_excel(writer, sheet_name=item if item else 'All', index=False)
        else:
            with pd.ExcelWriter(savefile, engine='openpyxl') as writer:
                tukey_summary[tukey_summary['reject'] == True].to_excel(writer, sheet_name=item if item else 'All', index=False)

# assessorAnalysis(assessorDf)
assessorAnalysis(assessorDf, item='415-AC', colScore='% Yes', type_='All')
sys.exit(0)  # Exit after running the analysis

### Mini-cex examiner analysis

In [ ]:
# Examiner analysis:
import statsmodels.api as sm
from statsmodels.stats.multicomp import MultiComparison
import matplotlib.pyplot as plt
from scipy.stats import f_oneway, kruskal
from scipy.stats import pearsonr
from statsmodels.stats.multicomp import pairwise_tukeyhsd

df = pd.read_excel(f'{folder}\\miniCEX BOH scoresheet.xlsx')
# display(df.head())
for examiner in df['assessor_name'].unique():
    examinerDf = df[df['assessor_name'] == examiner]
    print(f'Examiner: {examiner}')
    # display(examinerDf.head())




# 1. Bar plot of average weighted score per examiner
plt.figure(figsize=(8, 5))
ax = sns.barplot(data=df, x='assessor_name', y='Weighted Score', estimator='mean', ci=None)
plt.title("Average Weighted Score per Examiner")
plt.ylabel("Average Weighted Score")
plt.xlabel("Examiner")
plt.tight_layout()
# annotate the bars with the mean score
# Annotate each bar with its height (mean score)
for p in ax.patches:
    height = p.get_height()
    ax.annotate(f'{height:.1f}', (p.get_x() + p.get_width() / 2., height),
                ha='center', va='bottom', fontsize=10)
plt.show()


# 2. Box plot of weighted scores per examiner
plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x='assessor_name', y='Weighted Score')
plt.title("Score Distribution (Boxplot) by Examiner")
plt.ylabel("Weighted Score")
plt.xlabel("Examiner")
plt.tight_layout()
plt.show()

# 3. Distribution plot of Weighted Score per examiner
plt.figure(figsize=(10, 6))
sns.kdeplot(data=df, x='Weighted Score', hue='assessor_name', linestyle='--')
# a dotted kde for the overall distribution
# sns.kdeplot(data=df, x='Weighted Score', color='black', linestyle='-', label='Overall Distribution')
plt.title("Distribution of Weighted Scores per Examiner")
plt.xlabel("Weighted Score")
plt.tight_layout()
plt.show()

# ES v/s  Weighted Score plot
# Set up the plot
# Create subplots for each assessor
unique_assessors = df['assessor_name'].unique()
num_assessors = len(unique_assessors)
fig, axes = plt.subplots(num_assessors, 1, figsize=(8, 3 * num_assessors), sharex=True)
correlation_summary = []
for ax, assessor in zip(axes, unique_assessors):
    assessor_df = df[df['assessor_name'] == assessor]
        # Compute correlation
    if len(assessor_df) > 1:
        r, p = pearsonr(assessor_df['ES'], assessor_df['Weighted Score'])
    else:
        r, p = float('nan'), float('nan')
    
    # Store stats
    correlation_summary.append({
        'Assessor': assessor,
        'Pearson r': round(r, 3),
        'p-value': round(p, 3),
        'n': len(assessor_df)
    })
    
    sns.regplot(data=assessor_df, x='ES', y='Weighted Score', ci=None, ax=ax, color='blue', marker='o')
    ax.set_title(f'{assessor}\nPearson r={r:.2f}, p={p:.3f}, n={len(assessor_df)}')
    ax.set_xlabel('Entrustment Score (ES)')
    ax.set_ylabel('Weighted Score')
    ax.set_ylim(40, 105)
    ax.set_xlim(0.8, 4.2)
    ax.set_yticks(range(40, 110, 10))
    ax.set_xlabel('')
    ax.set_xticks(range(1, 5))
    ax.grid(True)
axes[-1].set_xlabel('Entrustment Score (ES)') 
plt.tight_layout()
plt.show()




# Prepare data per examiner
grouped_scores = [group['Weighted Score'].dropna().values for name, group in df.groupby('assessor_name')]

# Perform One-Way ANOVA
anova_stat, anova_p = f_oneway(*grouped_scores)

# Perform Kruskal-Wallis H-test (non-parametric alternative to ANOVA)
kruskal_stat, kruskal_p = kruskal(*grouped_scores)

# Summary of results
statistical_summary = pd.DataFrame({
    'Test': ['One-Way ANOVA', 'Kruskal-Wallis H'],
    'Test Statistic': [anova_stat, kruskal_stat],
    'p-value': [anova_p, kruskal_p]
})

display(statistical_summary)


# Tukey HSD test for multiple comparisons
df['Weighted Score'] = pd.to_numeric(df['Weighted Score'], errors='coerce')
tukey_df = df[['Weighted Score', 'assessor_name']].dropna()

# Perform Tukey HSD
tukey_result = pairwise_tukeyhsd(endog=tukey_df['Weighted Score'],
                                 groups=tukey_df['assessor_name'],
                                 alpha=0.05)

# Extract results into DataFrame
tukey_summary = tukey_result.summary()
tukey_data = tukey_summary.data[1:]  # skip header row
tukey_columns = tukey_summary.data[0]

tukey_summary_df = pd.DataFrame(tukey_data, columns=tukey_columns)
display(tukey_summary_df)

# Prepare data for Tukey HSD plot
multi_comp = MultiComparison(df['Weighted Score'], df['assessor_name'])
tukey_plot = multi_comp.tukeyhsd()
# Tukey plot
fig = tukey_plot.plot_simultaneous()
plt.title('Tukey HSD: Examiner Comparison')
plt.xlabel('Mean Difference in Weighted Score')
plt.tight_layout()
plt.show()

### Student Report creation mini cex

In [ ]:
display(ebelWeights['521'])

In [ ]:
IC_BOH_fullnames = {
    "MC1": "Performs hand hygiene in accordance with the five moments of hand hygiene.",
    "MC2": "Performs hand rub and hand washing technique in accordance with the World Health Organization guidelines.",
    "MC3": "Dons/doffs PPE in accordance with the Australian Commission on Safety and Quality in Health Care guidelines.",
    "MC4": "Follows record keeping requirements (places instrument tracking sticker onto tracking sheet).",
    "MC5": "Checks instrument expiry.",
    "MC6": "Checks sterilisation was successful by colour change indicator.",
    "MC7": "Peels instrument packaging open and places instruments onto bracket table.",
    "MC8": "Transports instruments safely, with sharps pointing towards the floor.",
    "MC9": "Adjusts clinician chair correctly.",
    "MC10": "Maintains good posture, positioning of self, patient, and bracket tray.",
    "MC11": "Demonstrates safe management and disposal of sharps.",
    "MC12": "Disposes of waste into appropriate receptacle.",
    "MC13": "Takes out detergent wipes.",
    "MC14": "Wipes non-clinical area from high to low.",
    "MC15": "Wipes operator and DA’s chair from back to front.",
    "MC16": "Wipes dental unit from top to bottom, cleanest to dirtiest.",
    "MC17": "Flushes lines.",
    "MC18": "Sets up bay (places bibs and glasses out)."
}


df = pd.read_excel(f'{folder}\\all data scores.xlsx')
rubricRef = pd.read_excel('2025\Rubric Reference Table.xlsx')
rubricRef.set_index('Score', inplace=True)
folder, file, ext = getFolderandFileName(f'{folder}\\all data scores.xlsx')
df = df.replace('_x000D_', '', regex=True)
# dfboh = df[df['cohort'] == 'BOH1']
dfboh = df[df['assessor_submitted'] == True]
ids = dfboh[colId].unique()
importantCols = [colName, colId,  colDate, colAssessorName, colAssessorFeedback, colCI]
dfboh[rubricCols] = dfboh[rubricCols].astype('Int64')
os.makedirs(f'{folder}\\Student Reports', exist_ok=True)
for id in ids:
    studentDoc = SimpleDocTemplate(f'{folder}\\Student Reports\\{id}.pdf', pagesize=pageSize, rightMargin=rightMargin, leftMargin=leftMargin, topMargin=topMargin, bottomMargin=bottomMargin)
    elements = []
    studentDf = dfboh[dfboh[colId] == id]
    studentName = studentDf[colName].values[0]
    # studentDf = studentDf[impCols]
    studentDf = studentDf[studentDf['supervisor_data'].notna()]
    # display(studentDf.head())
    # convert supervisor_data to json
    studentDf['supervisor_data'] = studentDf['supervisor_data'].apply(lambda x: json.loads(x))
    studentDf['Scores'] = studentDf['Scores'].apply(lambda x: json.loads(x))
    display(studentDf.head())
    for i, row in studentDf.iterrows():

        # for all the important columns display column name and value
        elements.append(Paragraph(f'Form {i+1}: {row[colDate]}', subheadingStyle))
        # elements.append(Paragraph(f'Role: {row["role"]}', subsubheadingStyle))
        elements.append(Spacer(1, 10))
        for col in importantCols:
            if pd.isna(row[col]) or row[col] == 'nan':
                continue
            # print(f'{col}: {row[col.lower()]}')
            elements.append(Paragraph(f'{col.strip()}', smallsubsubheadingStyleL))
            elements.append(Spacer(1, 6))
            text = str(row[col]).strip().replace('\n', '<br/>')
            # text = row[col].strip()
            # remove non-ascii characters
            text = re.sub(r'[^\x00-\x7F]+', '', text)

            elements.append(Paragraph(f'{text}', tableTextStyleL))
            elements.append(Spacer(1, 12))

        for col in rubricCols:
            if pd.isna(row[col]) or row[col] == 'nan':
                continue
            # print(f'{col}: {row[col.lower()]}')
            elements.append(Paragraph(f'{col.strip()}', smallsubsubheadingStyleL))
            elements.append(Spacer(1, 6))
            text =f'Lvl {row[col]}: {rubricRef.loc[row[col], col]}'
            text = text.strip().replace('\n', '<br/>')
            # text = row[col].strip()
            # remove non-ascii characters
            text = re.sub(r'[^\x00-\x7F]+', '', text)

            elements.append(Paragraph(f'{text}', tableTextStyleL))
            elements.append(Spacer(1, 12))

        # create a table of the supervisor data
        # convert to list from string
        row['Item Codes'] = ast.literal_eval(row['Item Codes']) if isinstance(row['Item Codes'], str) else row['Item Codes']
        itemCode = row['Item Codes'] if 'Item Codes' in row else []
        itemCode = itemCode[0] if len(itemCode) > 0 else None
        if itemCode is None: 
            continue
        ebelWeight = ebelWeights[itemCode]

        evalDf = pd.DataFrame.from_dict(row['supervisor_data'], orient='index').T
        # display(evalDf.head())
        mcCols = [col for col in evalDf.columns if 'MC' in col]
        evalDf = evalDf[mcCols]
        evalDf = evalDf.T.reset_index()

        evalDf.columns = ['Checklist', 'Result']
        evalDf['Checklist'] = evalDf['Checklist'].map(lambda x: x.split('_')[-1])
        evalDf.set_index('Checklist', inplace=True)
        
        # Ensure ebelWeight index is the checklist codes
        ebelWeight.index.name = 'Checklist'
        # display(evalDf)
        # display(ebelWeight)
        # Merge on Checklist
        evalDf = evalDf.merge(ebelWeight, on='Checklist', how='left')
        # display(evalDf.head())
        evalDf.reset_index(inplace=True)
        evalDf = evalDf[['Checklist', 'Full Question', 'Result']]
        # display(evalDf.head())        
        evalTable = createTable(evalDf, 'Marking Checklist', colRatio=[1, 5, 1], customTextCols=[1], bottomPadding=6, topPadding=6, cellHighlight=True,
                                tableTextStyle=tableTextStyleSmall)
        elements.append(evalTable)
        elements.append(Spacer(1, 12))
        scores = row['Scores'][itemCode]
        print(scores)
        scoreText = f"<b> Total Score: {scores['Total Score']}</b>" if 'Total Score' in scores else f"<b> %Yes: {scores['% Yes']}</b>"
        noteText = f"""In marking checklist each checklist item holds a different score weightage.<br/> Your total score is result of 
        your performance in marking checklist as well as your performance in the rubric. <br/>
        """ 
        elements.append(Paragraph(scoreText, tableTextStyleL))
        elements.append(Spacer(1, 12))
        elements.append(Paragraph(noteText, tableTextStyleL))
        elements.append(PageBreak())
    studentDoc.build(elements)
    # break

### BOH3 and DDS4 time series

In [ ]:
## BOH3 scores
workbookpath = '2025\BOH3+DDS4\Session 8\\2025 BOH3 and DDS4 CAF_Merged.xlsx'
folder, file, ext = getFolderandFileName(workbookpath)
df = pd.read_excel(workbookpath)
fullnameDict = { col: df.loc[0, col] for col in df.columns}
df.drop(index=0, inplace=True)
def getStudentList(listpath, cohort='BOH3'):
    listdf = pd.read_excel(listpath, keep_default_na=False, na_values=[''])
    if cohort is not None:
        listdf = listdf[listdf['Cohort'] == cohort]
    validIds = listdf['Student ID'].to_list()
    # convert to int
    validIds = [int(id) for id in validIds]
    print(f"Number of valid student IDs in {cohort}: {len(validIds)}")
    return validIds
validIds = getStudentList('2025\RE_ Student List.xlsx', cohort=None)
colId = 'Student ID'

In [ ]:
df.columns = df.columns.str.strip()
print(df.columns)

beforecolumns = [
    "Given name", "Family Name", "Student ID", "Email",
    "Date", "Cohort", "Rotation", "Clinic", "Role"
]

evalCols = [col for col in df.columns if 'Evaluation#' in col]
supEvalCols = [col for col in evalCols if 'Evaluation#2' in col]
colES = 'Entrustment'
colCI = 'Clinical Incident'
colCIReason = 'CI Explanation'
colEdu = 'Edu Name'
colFeedback = ['Student Reflection',	'Edu Feedback']
df = df[beforecolumns + evalCols +  [colES, colCI, colCIReason, colEdu] + colFeedback]
df = df[df[colId].isin(validIds)]
display(df.head())
cohort = 'BOH3'
# cohort = 'DDS4'

In [ ]:
dfOperator = df[df['Role'] == 'Operator']
dfOperator['#Yes'] = df.apply(lambda x: (x[supEvalCols] == 'Yes').sum(), axis=1)
dfOperator['#No'] = df.apply(lambda x: (x[supEvalCols] == 'No').sum(), axis=1)
dfOperator['#NA'] = df.apply(lambda x: (x[supEvalCols] == 'NA').sum(), axis=1)
dfOperator['%Yes'] = (dfOperator['#Yes'] / (dfOperator['#Yes'] + dfOperator['#No'])*100).round(2)
dfOperator[colES] = dfOperator[colES].str.extract('Lvl (\d+)').astype('Int64')
dfOperator.sort_values(by=['Family Name', 'Given name'], inplace=True)

In [ ]:
# aggregate Yes No and NA over student ID
dfOperatorAgg = dfOperator.groupby('Student ID').agg({
    '#Yes': 'sum',
    '#No': 'sum',
    '#NA': 'sum',
    'Family Name': 'first',
    'Given name': 'first',
    'Cohort': 'first'
}).reset_index()
dfOperatorAgg['%Yes'] = (dfOperatorAgg['#Yes'] / (dfOperatorAgg['#Yes'] + dfOperatorAgg['#No'])*100).round(2)
display(dfOperatorAgg.head(10))
dfOperatorAgg.to_excel(f'{folder}\\Operator aggregated.xlsx', index=False)

In [ ]:
dfOperator = dfOperator[dfOperator['Cohort'] == cohort]

In [ ]:
pageSize =( 11.69 * 2  * inch, 8.27 * 2 * inch)
print(pageSize)
clinicShortforms = {
    "RDHM": "RDHM",
    "MDC": "MDC",
    "YOUR Community ": "YOUR",
    "La Trobe Community ": "LaTrobe",
    "Banyule ": "Banyule",
    "IPC ": "IPC",
    "Health Ability ": "HAbility",
    "EACH": "EACH",
    "Echuca Regional Health ": "Echuca",
    "Link Health ": "Link",
    "VAHS": "VAHS",
    "Cohealth ": "Cohealth",
    "Other": "Other",
    "Goulburn Valley Health ": "GVH",
    "Cobram District CHC ": "Cobram",
    "Rumbalara": "Rumbalara",
    "North Richmond Community Health": "NRCH",
    "Northeast Health ": "NEHealth"
}
display(dfOperator.head())
print(dfOperator['Clinic'].unique())
colScore = '%Yes'
def annotateClinicLabels(ax, df, xCol, yCol, labelCol, shortformDict):
    offsetCounter = defaultdict(int)
    for _, row in df.iterrows():
        key = (row[xCol], row[yCol])
        if pd.isna(row[xCol]) or pd.isna(row[yCol]):
            continue
        offset = offsetCounter[key] * 5
        offsetCounter[key] += 1
        label = shortformDict.get(row[labelCol], row[labelCol])
        ax.annotate(label,
                    (row[xCol], row[yCol]),
                    textcoords="offset points", xytext=(0, 5 + 2 * offset),
                    ha='center', fontsize=6)

imgSize = (28, 7)
def createTimeSeries(studentDf, studentName, id, colScore):
    print(studentDf[colScore].min(), studentDf[colScore].max())
    fig, ax = plt.subplots(figsize=imgSize)
    ax.scatter(studentDf['Date'], studentDf[colScore], color='blue')
    ax.set_xticklabels(ax.get_xticklabels(), rotation=90)
    annotateClinicLabels(ax, studentDf, 'Date', colScore, 'Clinic', clinicShortforms)
    title = f'{studentName} ({id})'
    ax.set_title(title)
    ax.set_xlabel("Date")
    ax.set_ylabel("Score (% Yes)")
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.tick_params(axis='x', rotation=45)
    ax.set_ylim(0.8*studentDf[colScore].min(), 1.2*studentDf[colScore].max())
    ax.set_yticks(range(int((studentDf[colScore].min() - 1)/10)*10, int(studentDf[colScore].max() + 1), int(max(studentDf[colScore].max()//10, 1))))
    fig.tight_layout()
    return fig


docTimeSeries = SimpleDocTemplate(f'{folder}\\{cohort} Time series report.pdf', pagesize=pageSize,
                                   rightMargin = rightMargin, leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)   
timeSeriesElements = []
for id in dfOperator['Student ID'].unique():
    if id == 123456:
        continue
    studentDf = dfOperator[dfOperator['Student ID'] == id]
    studentName = studentDf['Family Name'].values[0] + ' ' + studentDf['Given name'].values[0]
    print(f'Student: {studentName} ({id})')
    # display(studentDf)
    studentDf['Date'] = pd.to_datetime(studentDf['Date'], format='mixed')
    studentDf.sort_values(by='Date', inplace=True)
    studentDf['Date'] = studentDf['Date'].dt.strftime('%d %b')
    timeSeriesfig = createTimeSeries(studentDf, studentName, id, colScore)
    timeSeriesImg = addPlotImage(timeSeriesfig, 0.9, pageSize)
    # now entrustment time series
    label = colES
    fig, ax = plt.subplots(figsize=imgSize)
    ax.plot(studentDf[colDate], studentDf[label], label=label, marker='o', color = 'orange')
    annotateClinicLabels(ax, studentDf, colDate, label, 'Clinic', clinicShortforms)
    ax.set_title('Entrustment Time Series')
    ax.set_xlabel('Date')
    ax.set_ylabel('Entrustment')
    ax.set_ylim(0, studentDf[label].max() + 0.5)
    ax.tick_params(axis='x', rotation=45)
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.set_yticks(range(0, int(studentDf[label].max()+1), 1))
    ax.set_yticklabels(range(0, int(studentDf[label].max()+1), 1))
    plt.tight_layout()
    ax.set_title(f'Entrustment Level for {studentName} ({id})')
    esTimeSeriesImg = addPlotImage(fig, 0.9, pageSize)
    timeSeriesElements.append(KeepTogether([timeSeriesImg, Spacer(1, 12), esTimeSeriesImg]))
    timeSeriesElements.append(PageBreak())


    plt.show()
    # break

docTimeSeries.build(timeSeriesElements.copy())

In [ ]:
results = []
for id in dfOperator['Student ID'].unique():
    # figure out which of the Evaluation# columns have the lowest and highest scores
    studentDf = dfOperator[dfOperator['Student ID'] == id]
    studentName = studentDf['Family Name'].values[0] + ' ' + studentDf['Given name'].values[0]
    print(f'Student: {studentName} ({id})')
    studentDf['Date'] = pd.to_datetime(studentDf['Date'], format='mixed')
    studentDf.sort_values(by='Date', inplace=True)
    studentDf['Date'] = studentDf['Date'].dt.strftime('%d %b')
    # get the columns that have the lowest and highest scores
    colScores = [col for col in studentDf.columns if 'Evaluation#2' in col]
    studentDf[colScores] = studentDf[colScores].replace({'Yes': 1, 'No': 0, 'NA': np.nan})
    # turn the scores into numeric
    studentDf[colScores] = studentDf[colScores].apply(pd.to_numeric, errors='coerce')
    meanScores = studentDf[colScores].mean()
    # Top 3 and bottom 3 using full names
    best3 = meanScores.sort_values(ascending=False).head(3)
    worst3 = meanScores.sort_values().head(3)

    results.append({
        'ID': id,
        'Name': studentName,
        'Best 3': '<br/> '.join([fullnameDict.get(col, col).split(' - ')[-1].split('\n')[0] for col in best3.index]),
        'Best<br/>Scores': '<br/> '.join([str(int(x*100)) for x in best3.values]),
        'Worst 3': '<br/> '.join([fullnameDict.get(col, col).split(' - ')[-1].split('\n')[0] for col in worst3.index]),
        'Worst<br/>Scores': '<br/> '.join([str(int(x*100)) for x in worst3.values]),
    })
    # break
# convert results to a dataframe
resultsDf = pd.DataFrame(results)
resultsTable = createTable(resultsDf, 'Best and Worst areas of students', colRatio=[1, 1, 4, 1, 4, 1], customTextCols=[1, 2, 3, 4, 5], bottomPadding=12, topPadding=12,
                           tableTextStyle=tableTextStyleSmall)
table = resultsTable._content[2]
headerRow = table._cellvalues[0]
tableTextStyleLarge.fontName = 'Helvetica-Bold'
for i in range(len(headerRow)):
    headerText = str(headerRow[i])
    wrappedPara = Paragraph(headerText, tableTextStyleLarge)
    table._cellvalues[0][i] = wrappedPara
# change the header to wrap text
resultElements = []
resultElements.append(resultsTable)
docResults = SimpleDocTemplate(f'{folder}\{cohort} Best and Worst areas of students.pdf', pagesize=pageSize,
                                   rightMargin = rightMargin, leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
docResults.build(resultElements.copy())
display(resultsDf.head())

## BOH3 scores

In [ ]:
workbookpath = '2025\BOH3+DDS4\Session 4\\2025 BOH3 and DDS4 CAF.xlsx'
folder, file, ext = getFolderandFileName(workbookpath)
df = pd.read_excel(workbookpath)
fullnameDict = { col: df.loc[0, col] for col in df.columns}
df.drop(index=0, inplace=True)

In [ ]:
df.columns = df.columns.str.strip()
print(df.columns)

beforecolumns = [
    "Given name", "Family Name", "Student ID", "Email",
    "Date", "Cohort", "Rotation", "Clinic", "Role"
]

evalCols = [col for col in df.columns if 'Evaluation#' in col]
supEvalCols = [col for col in evalCols if 'Evaluation#2' in col]
colES = 'Entrustment'
colCI = 'Clinical Incident'
colCIReason = 'CI Explanation'
colEdu = 'Edu Name'
colFeedback = ['Student Reflection',	'Edu Feedback']
df = df[beforecolumns + evalCols +  [colES, colCI, colCIReason, colEdu] + colFeedback]
display(df.head())

In [ ]:
dfOperator = df[df['Role'] == 'Operator']
dfOperator['#Yes'] = df.apply(lambda x: x[supEvalCols].str.contains('Yes').sum(), axis=1)
dfOperator['#No'] = df.apply(lambda x: x[supEvalCols].str.contains('No').sum(), axis=1)
dfOperator['#NA'] = df.apply(lambda x: x[supEvalCols].str.contains('NA').sum(), axis=1)
dfOperator['%Yes'] = (dfOperator['#Yes'] / (dfOperator['#Yes'] + dfOperator['#No'])*100).round(2)
dfOperator[colES] = dfOperator[colES].str.extract('Lvl (\d+)').astype('Int64')
display(dfOperator.head())

In [ ]:
# remove codes of the form 524_MCx and 578_MCx

def compare_supervisors(studentDf):
    if len(studentDf) != 2:
        print("Error: The student must have exactly two rows for comparison.")
        return None
    
    row1, row2 = studentDf.iloc[0], studentDf.iloc[1]
    
    # Identify columns where neither row has NA
    valid_cols = [col for col in assessormcCols if row1[col] != 'NA' and row2[col] != 'NA']
    
    # Filter to only Yes/No columns
    yes_no_cols = [col for col in valid_cols if studentDf[col].isin(['Yes', 'No']).all()]
    
    # Count differences
    diff_yes_to_no = sum(row1[col] == 'Yes' and row2[col] == 'No' for col in yes_no_cols)
    diff_no_to_yes = sum(row1[col] == 'No' and row2[col] == 'Yes' for col in yes_no_cols)
    
    # Count how many more Yes answers the first supervisor has over the second
    yes_first_more = sum(row1[col] == 'Yes' and row2[col] == 'No' for col in yes_no_cols) - \
                     sum(row1[col] == 'No' and row2[col] == 'Yes' for col in yes_no_cols)

    return {
        "Yes to No": diff_yes_to_no,
        "No to Yes": diff_no_to_yes,
        "Yes (First Supervisor) More By": yes_first_more
    }

def createAssessorSummary(df, assessormcCols):
    assessor_value_counts = {}
    for assessor in df['assessor_name'].unique():
        assessorDf = df[df['assessor_name'] == assessor]
        # Count occurrences of each unique value across all assessor MC columns
        value_counts = assessorDf[assessormcCols].apply(pd.Series.value_counts).sum(axis=1).to_dict()
        # add value for number of assessments
        value_counts['Total Forms'] = len(assessorDf)
        value_counts['entrustment'] = assessorDf['entrustment'].value_counts().to_dict()
        # Store result
        assessor_value_counts[assessor] = value_counts

    # Convert results to DataFrame for better visualization
    assessor_summary_df = pd.DataFrame.from_dict(assessor_value_counts, orient='index').fillna(0)
    assessor_summary_df['Total'] = assessor_summary_df.sum(axis=1)
    # total of Yes and No
    assessor_summary_df['YesNoTotal'] = assessor_summary_df['Yes'] + assessor_summary_df['No']
    assessor_summary_df['Leniency'] = assessor_summary_df['Yes'] / assessor_summary_df['YesNoTotal']
    # sort on linency
    assessor_summary_df.sort_values(by='Leniency', inplace=True, ascending=False)
    return assessor_summary_df

### Standard Setting

In [ ]:
ssFile = '2025\StandardSetting.xlsx'
data524_578file = '2025\DDS2\Michael\michaelData 524+578.xlsx'
data533_577file = '2025\DDS2\Michael\michaelData 533+577.xlsx'
data524_578 = pd.read_excel(data524_578file)
folder, file, ext = getFolderandFileName(data524_578file)
data533_577 = pd.read_excel(data533_577file)
ss1 = pd.read_excel(ssFile, sheet_name= 'MW SIM Adhesive List')
marking_dict1 = ss1.set_index("Marking Checklist")["Importance"].to_dict()
ss2 = pd.read_excel(ssFile, sheet_name = '577')
marking_dict2 = ss2.set_index("Marking Checklist")["Importance"].to_dict()
ss3 = pd.read_excel(ssFile, sheet_name = '578')
marking_dict3 = ss3.set_index("Marking Checklist")["Importance"].to_dict()

# change dict keys to assessor_code_MC\d
def changeKey(d, code):
    newd = {}
    for key, value in d.items():
        newkey = f'assessor_{code}_{key}'
        newd[newkey] = value
    return newd
marking_dict524 = changeKey(marking_dict1, '524')
marking_dict533 = changeKey(marking_dict1, '533')
marking_dict577 = changeKey(marking_dict2, '577')
marking_dict578 = changeKey(marking_dict3, '578')
joint_dict = {**marking_dict524, **marking_dict533, **marking_dict577, **marking_dict578}

In [ ]:
def defineVars(df):
    pecItems  = ['positioning', 'Consent', 'Record', 'infection']
    rubricCols = ['time_mgmt', 'communication', 'professionalism', 'entrustment']
    mcCols = [col for col in df.columns if 'MC' in col and 'positioning' not in col and 'Consent' not in col and 'Record' not in col and 'infection' not in col]
    pecCols = [col for col in df.columns if 'positioning' in col or 'Consent' in col or 'Record' in col or 'infection' in col]
    studentmcCols = [col for col in mcCols if 'student' in col]
    assessormcCols = [col for col in mcCols if 'assessor' in col]

    otherCols = [col for col in df.columns if col not in mcCols and col not in rubricCols and col not in pecCols]
    print(otherCols)
    otherfullnamedict = {'student_name': 'Student Name', 'assessor_name': 'Assessor Name', 'date': 'Date', 'cohort': 'Cohort', 'subject': 'Subject', 'type': 'Type',
                        'time_mgmt': 'Time Management', 'communication': 'Communication', 'professionalism': 'Professionalism', 'entrustment': 'Entrustment',
                        'student_feedback': 'Student Feedback', 'assessor_feedback': 'Assessor Feedback', 'clinical_incident': 'Clinical Incident',
                        'patient_complexity': 'Complexity', 'Consent': 'Consent'}
    return mcCols, pecCols, studentmcCols, assessormcCols, otherCols, otherfullnamedict, rubricCols

In [ ]:
# 524 and 578
data524_578.drop(columns = ['student_524_MC3',	'student_524_MC4', 'assessor_524_MC3', 'assessor_524_MC4'], inplace=True, errors='ignore')

# get unique students
unique_students = data524_578['student_name'].nunique()
print(f"Unique students: {unique_students}")   
studentList = data524_578['student_name'].unique()
# print(studentList)
mcCols, pecCols, studentmcCols, assessormcCols, otherCols, otherfullnamedict, rubricCols = defineVars(data524_578)
data524_578.drop(studentmcCols, axis=1, inplace=True)
# Function to fill NaN values from the other row
# Function to fill NaN values from the other row in a group
def fill_nan_from_other_row(series):
    return series.fillna(method='ffill').fillna(method='bfill')

# Apply the function correctly using transform() instead of apply()
data524_578[assessormcCols] = data524_578.groupby("student_name")[assessormcCols].transform(fill_nan_from_other_row)
for student in studentList:
    studentDf = data524_578[data524_578['student_name'] == student]
    # for each student we have two dates, for the Nan values in one date, we can fill with the other date
    # display(studentDf)

# marking_dict524 is importance dict for each MC question for 524 with assessor_524_MC\d: Importance as key value pair
# marking_dict533 is importance dict for each MC question for 533 with assessor_533_MC\d: Importance as key value pair
# marking_dict577 is importance dict for each MC question for 577 with assessor_577_MC\d: Importance as key value pair
# marking_dict578 is importance dict for each MC question for 578 with assessor_578_MC\d: Importance as key value pair

# importance 10 is critical, 7-9 are important, 4-6 are moderate, 1-3 are minor

# add a column to see whether critical was marked Yes
def getCritical(row, marking_dict, valueMatch):
    counter = 0 
    for key, value in marking_dict.items():
        if key not in row:
            continue
        if value in [10]:
            if row[key]==valueMatch:
                counter += 1
    return counter

data524_578['#CriticalYes'] = data524_578.apply(lambda x: getCritical(x, joint_dict, 'Yes'), axis=1)
data524_578['#CriticalNo'] = data524_578.apply(lambda x: getCritical(x, joint_dict, 'No'), axis=1)
# Add a column to calculate the percentage of critical Yes responses, handling zero denominator
data524_578['%CriticalYes'] = data524_578.apply(
    lambda x: (x['#CriticalYes'] / (x['#CriticalYes'] + x['#CriticalNo']) * 100) if (x['#CriticalYes'] + x['#CriticalNo']) != 0 else np.nan,
    axis=1
)

# add column to see how many important were marked Yes, get the counts
def getImportant(row, marking_dict, valueMatch):
    counter = 0
    for key, value in marking_dict.items():
        if key not in row:
            continue
        if value in [7, 8, 9]:
            if row[key]==valueMatch:
                counter += 1
    return counter
data524_578['#ImportantYes'] = data524_578.apply(lambda x: getImportant(x, joint_dict, 'Yes'), axis=1)
data524_578['#ImportantNo'] = data524_578.apply(lambda x: getImportant(x, joint_dict, 'No'), axis=1)
data524_578['%ImportantYes'] = data524_578.apply(
    lambda x: (x['#ImportantYes'] / (x['#ImportantYes'] + x['#ImportantNo']) * 100) if (x['#ImportantYes'] + x['#ImportantNo']) != 0 else np.nan,
    axis=1
)
# add column to see how many moderate were marked Yes, get the counts
def getModerate(row, marking_dict, valueMatch):
    counter = 0
    for key, value in marking_dict.items():
        if key not in row:
            continue
        if value in [4, 5, 6]:
            if row[key]==valueMatch:
                counter += 1
    return counter
data524_578['#ModerateYes'] = data524_578.apply(lambda x: getModerate(x, joint_dict, 'Yes'), axis=1)
data524_578['#ModerateNo'] = data524_578.apply(lambda x: getModerate(x, joint_dict, 'No'), axis=1)
data524_578['%ModerateYes'] = data524_578.apply(
    lambda x: (x['#ModerateYes'] / (x['#ModerateYes'] + x['#ModerateNo']) * 100) if (x['#ModerateYes'] + x['#ModerateNo']) != 0 else np.nan,
    axis=1
)


# add column to see how many minor were marked Yes, get the counts
def getMinor(row, marking_dict, valueMatch):
    counter = 0
    for key, value in marking_dict.items():
        if key not in row:
            continue
        if value in [1, 2, 3]:
            if row[key]==valueMatch:
                counter += 1
    return counter
data524_578['#MinorYes'] = data524_578.apply(lambda x: getMinor(x, joint_dict, 'Yes'), axis=1)
data524_578['#MinorNo'] = data524_578.apply(lambda x: getMinor(x, joint_dict, 'No'), axis=1)
data524_578['%MinorYes'] = data524_578.apply(
    lambda x: (x['#MinorYes'] / (x['#MinorYes'] + x['#MinorNo']) * 100) if (x['#MinorYes'] + x['#MinorNo']) != 0 else np.nan,
    axis=1
)
display(data524_578.head()) 

doc = SimpleDocTemplate(f'{folder}\\524+578 student eval.pdf', pagesize=pageSize, rightMargin = rightMargin, leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
elements = []
# create a stacked bar chart for important Yes, No for all students
fig, ax = plt.subplots(figsize=(figSize[0], figSize[1]))
plotdf = data524_578[['student_name', '#CriticalYes', '#CriticalNo', '#ImportantYes', '#ImportantNo', '#ModerateYes', '#ModerateNo', '#MinorYes', '#MinorNo']]
plotdf = plotdf.groupby('student_name').mean()
# plotdf.set_index('student_name', inplace=True)
plotdf[['#ImportantYes', '#ImportantNo']].plot(kind='barh', stacked=True, ax=ax)
img = addPlotImage(fig)
# elements.append(img)

statdf = data524_578[['student_name', '%CriticalYes', '%ImportantYes', '%ModerateYes', '%MinorYes']]
statdf = statdf.groupby('student_name').mean()
statdf.sort_values(by=['%CriticalYes', '%ImportantYes', '%ModerateYes', '%MinorYes'], ascending=False, inplace=True)
# round the values
statdf = statdf.round(2)
# display(statdf)
# statdf.to_excel(f'{folder}\\524+578 student eval.xlsx')
statdf.drop(columns=["%CriticalYes"], inplace=True)
statdf.reset_index(inplace=True)
stattable = createTable(statdf, 'Student Evaluation', colRatio=[1, 1, 1, 1])
elements.append(stattable)
doc.build(elements)

# create guttman of the whole data
guttmandf = data524_578.copy()
guttmandf = guttmandf.applymap(lambda x: 1 if x == 'Yes' else x)
guttmandf = guttmandf.applymap(lambda x: 0 if x == 'No' else x)
guttmandf = guttmandf.applymap(lambda x: np.nan if x == 'NA' else x)
# aggregate the data by student name sum of MC columns and take mean for rubric columns and first row for other columns, join the string in 'assessor_feedback'
agg_dict = {
    'assessor_feedback': lambda x: ','.join(x),
    'clinical_incident': 'first',
    'time_mgmt': 'mean',
    'communication': 'mean',
    'professionalism': 'mean',
    'entrustment': 'mean',
}

# Add assessor MC columns to aggregate them using 'sum'
agg_dict.update({col: 'sum' for col in assessormcCols})
leftovercols = [col for col in guttmandf.columns if col not in agg_dict.keys()]
agg_dict.update({col: 'first' for col in leftovercols})
guttmandf['assessor_feedback'] = guttmandf['assessor_feedback'].astype(str)
# Apply aggregation
guttmandf = guttmandf.groupby('student_name').agg(agg_dict)
guttmandf['MC Score'] = guttmandf[assessormcCols].sum(axis=1)
# get columnwise total for mcCols
colTotal = guttmandf[assessormcCols].sum(skipna=True)
guttmandf.loc['Column Total'] = pd.Series(colTotal, index=assessormcCols)

# sort columns by total
guttmandf = guttmandf[guttmandf.loc['Column Total'].sort_values(ascending=False).index]
# sort rows by MC Score
guttmandf = guttmandf.sort_values(by='MC Score', ascending=False)
display(guttmandf)
# guttmandf.to_excel(f'{folder}\\524+578 guttman.xlsx')

In [ ]:
# for 533 and 577
data533_577.drop(columns = ['student_533_MC13', 'student_533_MC11', 'assessor_533_MC12', 'assessor_533_MC7'], inplace=True, errors='ignore')
data533_577.drop(columns = ['student_577_MC3', 'student_577_MC4'], inplace=True, errors='ignore')

# get unique students
unique_students = data533_577['student_name'].nunique()
print(f"Unique students: {unique_students}")   
studentList = data533_577['student_name'].unique()
mcCols, pecCols, studentmcCols, assessormcCols, otherCols, otherfullnamedict, rubricCols = defineVars(data533_577)
data533_577.drop(studentmcCols, axis=1, inplace=True)

# Function to fill NaN values from the other row in a group
def fill_nan_from_other_row(series):
    return series.fillna(method='ffill').fillna(method='bfill')

# Apply the function correctly using transform() instead of apply()
data533_577[assessormcCols] = data533_577.groupby("student_name")[assessormcCols].transform(fill_nan_from_other_row)
for student in studentList:
    studentDf = data533_577[data533_577['student_name'] == student]

# add a column to see whether critical was marked Yes
data533_577['#CriticalYes'] = data533_577.apply(lambda x: getCritical(x, joint_dict, 'Yes'), axis=1)
data533_577['#CriticalNo'] = data533_577.apply(lambda x: getCritical(x, joint_dict, 'No'), axis=1)
data533_577['%CriticalYes'] = data533_577.apply(
    lambda x: (x['#CriticalYes'] / (x['#CriticalYes'] + x['#CriticalNo']) * 100) if (x['#CriticalYes'] + x['#CriticalNo']) != 0 else np.nan,
    axis=1
)

# add column to see how many important were marked Yes, get the counts
data533_577['#ImportantYes'] = data533_577.apply(lambda x: getImportant(x, joint_dict, 'Yes'), axis=1)
data533_577['#ImportantNo'] = data533_577.apply(lambda x: getImportant(x, joint_dict, 'No'), axis=1)
data533_577['%ImportantYes'] = data533_577.apply(
    lambda x: (x['#ImportantYes'] / (x['#ImportantYes'] + x['#ImportantNo']) * 100) if (x['#ImportantYes'] + x['#ImportantNo']) != 0 else np.nan,
    axis=1
)

# add column to see how many moderate were marked Yes, get the counts
data533_577['#ModerateYes'] = data533_577.apply(lambda x: getModerate(x, joint_dict, 'Yes'), axis=1)
data533_577['#ModerateNo'] = data533_577.apply(lambda x: getModerate(x, joint_dict, 'No'), axis=1)
data533_577['%ModerateYes'] = data533_577.apply(
    lambda x: (x['#ModerateYes'] / (x['#ModerateYes'] + x['#ModerateNo']) * 100) if (x['#ModerateYes'] + x['#ModerateNo']) != 0 else np.nan,
    axis=1
)

# add column to see how many minor were marked Yes, get the counts
data533_577['#MinorYes'] = data533_577.apply(lambda x: getMinor(x, joint_dict, 'Yes'), axis=1)
data533_577['#MinorNo'] = data533_577.apply(lambda x: getMinor(x, joint_dict, 'No'), axis=1)
data533_577['%MinorYes'] = data533_577.apply(
    lambda x: (x['#MinorYes'] / (x['#MinorYes'] + x['#MinorNo']) * 100) if (x['#MinorYes'] + x['#MinorNo']) != 0 else np.nan,
    axis=1
)
display(data533_577.head()) 

doc = SimpleDocTemplate(f'{folder}\\533+577 student eval.pdf', pagesize=pageSize, rightMargin = rightMargin, leftMargin = leftMargin, topMargin = topMargin, bottomMargin = bottomMargin)
elements = []
fig, ax = plt.subplots(figsize=(figSize[0], figSize[1]))
plotdf = data533_577[['student_name', '#CriticalYes', '#CriticalNo', '#ImportantYes', '#ImportantNo', '#ModerateYes', '#ModerateNo', '#MinorYes', '#MinorNo']]
plotdf = plotdf.groupby('student_name').mean()
plotdf[['#ImportantYes', '#ImportantNo']].plot(kind='barh', stacked=True, ax=ax)
img = addPlotImage(fig)

statdf = data533_577[['student_name', '%CriticalYes', '%ImportantYes', '%ModerateYes', '%MinorYes']]
statdf = statdf.groupby('student_name').mean()
statdf.sort_values(by=['%CriticalYes', '%ImportantYes', '%ModerateYes', '%MinorYes'], ascending=False, inplace=True)
statdf = statdf.round(2)
# statdf.drop(columns=["%CriticalYes"], inplace=True)
statdf.reset_index(inplace=True)
statdf.to_excel(f'{folder}\\533+577 student eval.xlsx')
stattable = createTable(statdf, 'Student Evaluation', colRatio=[1, 1, 1, 1])
elements.append(stattable)
doc.build(elements)

guttmandf = data533_577.copy()
guttmandf = guttmandf.applymap(lambda x: 1 if x == 'Yes' else x)
guttmandf = guttmandf.applymap(lambda x: 0 if x == 'No' else x)
guttmandf = guttmandf.applymap(lambda x: np.nan if x == 'NA' else x)
agg_dict = {
    'assessor_feedback': lambda x: ','.join(x),
    'clinical_incident': 'first',
    'time_mgmt': 'mean',
    'communication': 'mean',
    'professionalism': 'mean',
    'entrustment': 'mean',
}

agg_dict.update({col: 'sum' for col in assessormcCols})
leftovercols = [col for col in guttmandf.columns if col not in agg_dict.keys()]
agg_dict.update({col: 'first' for col in leftovercols})
guttmandf['assessor_feedback'] = guttmandf['assessor_feedback'].astype(str)
guttmandf = guttmandf.groupby('student_name').agg(agg_dict)
guttmandf['MC Score'] = guttmandf[assessormcCols].sum(axis=1)
colTotal = guttmandf[assessormcCols].sum(skipna=True)
guttmandf.loc['Column Total'] = pd.Series(colTotal, index=assessormcCols)
guttmandf = guttmandf[guttmandf.loc['Column Total'].sort_values(ascending=False).index]
guttmandf = guttmandf.sort_values(by='MC Score', ascending=False)
display(guttmandf)
guttmandf.to_excel(f'{folder}\\533+577 guttman.xlsx')

## Student Reports

In [ ]:
# workbookpath = '2025\BOH2\\all_data_combined.xlsx'
# workbookpath = '2025\BOH1\\all_data_combined.xlsx'
workbookpath  = '2025\DDS2\\all_data_combined.xlsx'
# workbookpath = '2025\DDS1\\all_data_combined.xlsx'
# workbookpath = '2025\mini CEX\DDS2\\all_data_combined.xlsx'
folder, file, ext = getFolderandFileName(workbookpath)
df = pd.read_excel(workbookpath, sheet_name='all_data_flat')
df.fillna('', inplace=True)
df.rename(columns={'student_number':'student_id'}, inplace=True)
df.drop(columns=['assessment_id'], inplace=True)
df['student_id'] = df['student_id'].astype(str)
with open('2025\sim_checklists.json') as f:
    simChecklist = json.load(f)
    simChecklist = {item['key']: item for item in simChecklist['result']}     # can get full name by key fields MCx
with open('2025\clinic_checklists.json') as f:
    clinicChecklist = json.load(f)
    clinicChecklist = {item['key']: item for item in clinicChecklist['result']}

pprint(simChecklist, indent=4)
pprint(clinicChecklist, indent=4)
pecItems  = ['positioning', 'Consent', 'Record', 'infection']
rubricCols = ['time_mgmt', 'communication', 'professionalism', 'entrustment']
mcCols = [col for col in df.columns if 'MC' in col and 'positioning' not in col and 'Consent' not in col and 'Record' not in col and 'infection' not in col]
pecCols = [col for col in df.columns if 'positioning' in col or 'Consent' in col or 'Record' in col or 'infection' in col]
studentmcCols = [col for col in mcCols if 'student' in col]
assessormcCols = [col for col in mcCols if 'assessor' in col]

otherCols = [col for col in df.columns if col not in mcCols and col not in rubricCols and col not in pecCols]
print(otherCols)
otherfullnamedict = {'student_name': 'Student Name', 'assessor_name': 'Assessor Name', 'date': 'Date', 'cohort': 'Cohort', 'subject': 'Subject', 'type': 'Type',
                     'time_mgmt': 'Time Management', 'communication': 'Communication', 'professionalism': 'Professionalism', 'entrustment': 'Entrustment',
                     'student_feedback': 'Student Feedback', 'assessor_feedback': 'Assessor Feedback', 'clinical_incident': 'Clinical Incident',
                     'patient_complexity': 'Complexity', 'Consent': 'Consent'}
mcColDict = {}
for col in mcCols:
    key = col.split('_')[1]
    if key not in mcColDict:
        mcColDict[key] = []
    mcColDict[key].append(col)
def get_items(row):
    items = []
    for key, cols in mcColDict.items():
        if any((not pd.isna(row[col])) and (row[col] not in ['', 'nan']) for col in cols):
            if key in pecItems:
                continue
            items.append(key)
    return items

df['Items'] = df.apply(get_items, axis=1)

# df = df[df['type'] == 'Clinic']
# anonymize student names, assessor names and student ids
studentIds = df['student_id'].unique()
anonIds = {id: f'Student {i+1}' for i, id in enumerate(df['student_id'].unique())}
anonNames = {name: f'Name_{i}' for i, name in enumerate(df['student_name'].unique())}
anonAssessors = {name: f'Assessor_{i}' for i, name in enumerate(df['assessor_name'].unique())}
df['student_id'] = df['student_id'].map(anonIds)
df['student_name'] = df['student_name'].map(anonNames)
df['assessor_name'] = df['assessor_name'].map(anonAssessors)
display(df.head())

In [ ]:
def createStudentReport(df, studentID):
    elements = []
    studentdf = df[df['student_id'] == studentID]
    studentName = studentdf['student_name'].iloc[0]
    # sort by date
    studentdf['date'] = pd.to_datetime(studentdf['date']).dt.date
    studentdf.sort_values('date', inplace=True)
    studentdf['date'] = studentdf['date']
    # filter out 31 march 2025 and 7 april 2025
    # studentdf = studentdf[studentdf['date'].isin(['31-03-2025', '07-04-2025'])]
    savefolder = f'{folder}\\Student Reports V1'#\\31Mar-7Apr'
    os.makedirs(savefolder, exist_ok=True)
    doc = SimpleDocTemplate(f'{savefolder}\\{studentID} ({studentName}).pdf', pagesize= pageSize, leftMargin = leftMargin,
                            rightMargin = rightMargin, topMargin = topMargin, bottomMargin = bottomMargin)
    
    # first heading
    # elements.append(Paragraph(f'{studentName}', headingStyle))
    elements.append(Spacer(1, 48))
    firstheading = f'Form submissions'
    secondheading = f'{studentName} | {studentID}'

    # get the forms
    for i, (idx, row) in enumerate(studentdf.iterrows()):
        formitems = row['Items']
        type = row.get('type', 'Clinic')
        elements.append(Paragraph(f'Form {i+1}: {row[colDate.lower()]}', subheadingStyle))
        elements.append(Spacer(1, 12))
        # elements.append(Paragraph(f'Role: {row[colRole]}', subsubheadingStyle))
        if len(formitems) > 0:
            elements.append(Spacer(1, 12))
            elements.append(Paragraph('Items Performed', subsubheadingStyleL))
            elements.append(Spacer(1, 12))
            elements.append(Paragraph(', '.join(formitems), tableTextStyleL))
        elements.append(Spacer(1, 12))
        # add other columns
        for col in otherCols:
            if pd.isna(row[col]) or row[col] == 'nan' or row[col] == '':
                continue
            # print(f'{col}: {row[col]}')
            elements.append(Paragraph(f'{otherfullnamedict[col] if col in otherfullnamedict.keys() else col}', smallsubsubheadingStyleL))
            elements.append(Spacer(1, 6))
            # text = row[col]
            # print(col, row[col])
            # if type is not string, convert to string
            if not isinstance(row[col], str):
                row[col] = str(row[col])
            text = row[col].strip().replace('\n', '<br/>')
            # remove _x000D_
            text = re.sub(r'_x000D_', '', text)
            # remove non-ascii characters
            text = re.sub(r'[^\x00-\x7F]+', '', text)
            elements.append(Paragraph(f'{text}', tableTextStyleL))
            elements.append(Spacer(1, 12))


        rubricDf = pd.DataFrame(columns = ['Rubric', 'Score'])
        for col in rubricCols:
            if pd.isna(row[col]) or row[col] == 'nan' or row[col] == '':
                continue
            rubricDf = pd.concat([rubricDf, pd.DataFrame({'Rubric': [otherfullnamedict[col]], 'Score': [row[col]]})])
        if len(rubricDf) != 0:
            rubricTable = createTable(rubricDf, 'Rubric Scores', colRatio=[1, 3], customTextCols=[0, 1], tableTextStyle=tableTextStyleSmall)
            # alter top and bottom padding
            table = rubricTable._content[2]
            table.setStyle(TableStyle([
                ('TOPPADDING', (0, 0), (-1, -1), 7),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
            ]))
            elements.append(rubricTable)
            elements.append(Spacer(1, 12))
        # add mc col table
        for item in formitems:
            print('\n', item, type)
            stumcCol = [col for col in studentmcCols if item in col]
            assmcCol = [col for col in assessormcCols if item in col]
            print(f'Student MC Columns: {stumcCol}')
            print(f'Assessor MC Columns: {assmcCol}')
            if type == 'Simulation':
                if item not in simChecklist:
                    checklist = {'name': item, 'fields': {}}
                    print(f'Item {item} not found in simulation checklist')
                else:
                    print(f'Item {item} found in simulation checklist')
                    checklist = simChecklist[item]
                itemName = checklist['name']
            else:
                if item not in clinicChecklist:
                    checklist = {'name': item, 'fields': {}}
                else:
                    checklist = clinicChecklist[item]
                itemName = checklist['name']
            if len(studentmcCols) == 0 and len(assessormcCols) == 0:
                continue
            evaldf = pd.DataFrame(columns = ['Marking Checklist', 'Student', 'Educator'])
            for stucol, educol in zip(stumcCol, assmcCol):
                qno = stucol.split('_')[-1]
                if qno not in checklist['fields'].keys():
                    markingchecklist = qno
                    print(f'Question {qno} not found in checklist for item {item}')
                else:
                    markingchecklist = checklist['fields'][qno]
                student = row[stucol]
                educator = row[educol]
                # if both student and educator are empty, skip
                if (pd.isna(student) or student == '') and (pd.isna(educator) or educator == ''):
                    print(f'Skipping empty student and educator for item {item}, question {qno}')
                    continue
                evaldf = pd.concat([evaldf, pd.DataFrame({'Marking Checklist': [markingchecklist], 'Student': [student], 'Educator': [educator]})])
            
            evaldf.replace({'Not Assessed': 'NA', 'Not Reviewed': 'NA', 'nan': 'NA'}, inplace=True)
            evalTable = createTable(evaldf, f'Evaluation for {item}: {itemName}', colRatio = [5, 1, 1], customTextCols=[0], cellHighlight=True, tableTextStyle=tableTextStyleSmall)
            # alter top and bottom padding
            table = evalTable._content[2]
            # if it's a table
            if isinstance(table, Table):
                table.setStyle(TableStyle([
                    ('TOPPADDING', (0, 0), (-1, -1), 7),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
                ]))
            elements.append(evalTable)
            elements.append(Spacer(1, 12))
        # add pec table
        # pecdf = pd.DataFrame(columns = ['Marking Checklist', 'Student', 'Educator'])
        # for col in pecCols:
        #     pecdf = pd.concat([pecdf, pd.DataFrame({'Marking Checklist': [fullnamedict[col].split(' - ')[-1]], 'Student': [row[col]], 'Educator': [row[col.replace('#1', '#2')]]})])
        # pecdf.replace({'Not Assessed': 'NA', 'Not Reviewed': 'NA', 'nan': 'NA'}, inplace=True)
        # pecTable = createTable(pecdf, 'Other Marking Checklist', colRatio = [5, 1, 1], customTextCols=[0], cellHighlight=True, tableTextStyle=tableTextStyleSmall)
        # elements.append(pecTable)
        # table = pecTable._content[2]
        # table.setStyle(TableStyle([
        #     ('TOPPADDING', (0, 0), (-1, -1), 7),
        #     ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        # ]))
        elements.append(PageBreak())
    doc.build(elements, onFirstPage=getBannerDrawer(firstheading, secondheading))

for studentID in studentIds:
    # print(studentID)
    if int(studentID)!= 1536461:
        continue
    createStudentReport(df, anonIds[studentID])
    # break
import sys
sys.exit(0)

In [ ]:
plt.ioff()
colorDict = {
    'Yes': '#4c72b0',             # Muted Blue
    'Yes with guidance': '#55a868',  # Soft Green
    'No': '#e07a5f',             # Warm Red-Orange
    'Not assessed': '#bfbfbf',    # Neutral Grey
    'NA': '#bfbfbf'              # Grey for renamed 'Not assessed'
}

def getYesNo(df, stuCols, supCols):
    df['YesStu'] = df[stuCols].apply(lambda x: (x == 'Yes').sum(), axis=1)
    df['NoStu'] = df[stuCols].apply(lambda x: (x == 'No').sum(), axis=1)
    df['NAStu'] = df[stuCols].apply(lambda x: (x == 'NA').sum(), axis=1)
    df['ScoreStu'] = df['YesStu']/(df['YesStu'] + df['NoStu'] + 0.00001)
    df['YesSup'] = df[supCols].apply(lambda x: (x == 'Yes').sum(), axis=1)
    df['NoSup'] = df[supCols].apply(lambda x: (x == 'No').sum(), axis=1)
    df['NASup'] = df[supCols].apply(lambda x: (x == 'NA').sum(), axis=1)
    df['ScoreSup'] = df['YesSup']/(df['YesSup'] + df['NoSup'] + 0.00001)
    df['ScoreDiff'] = df['ScoreStu'] - df['ScoreSup']
    return df
colId = 'student_name'

def plotStackedYesNo(df, colId, title):
    plotdf = df[[colId, 'YesStu', 'NoStu', 'NAStu', 'YesSup', 'NoSup', 'NASup']]
    # sort by highest NoSup
    # display(plotdf)
    plotdf = plotdf.groupby(colId).sum()
    plotdf.sort_values(by='NoSup', ascending=True, inplace=True)
    # drop rows with YesStu and YesSup = 0 and NoStu and NoSup = 0
    plotdf = plotdf[(plotdf['YesStu'] + plotdf['YesSup'] > 0) & (plotdf['NoStu'] + plotdf['NoSup'] > 0)]
    if len(plotdf) < 5:
        return None
    # display(plotdf)
    # plotdf.set_index(colId, inplace=True)
    studf = plotdf[['YesStu', 'NoStu', 'NAStu']]
    studf.columns = ['Yes', 'No', 'NA']
    supdf = plotdf[['YesSup', 'NoSup', 'NASup']]
    supdf.columns = ['Yes', 'No', 'NA']
    colors = [colorDict[key] for key in ['Yes', 'No', 'NA']]
    fig, ax = plt.subplots(1, 2, figsize=(figSize[0], figSize[1]))
    studf.plot(kind='barh', stacked=True, ax=ax[0], color=colors)
    ax[0].set_title('Student')
    ax[0].set_yticklabels(ax[0].get_yticklabels(), fontsize=6)
    ax[0].set_ylabel('')
    supdf.plot(kind='barh', stacked=True, ax=ax[1], color=colors)
    ax[1].set_title('Supervisor')
    ax[1].set_ylabel('')    
    ax[1].set_yticklabels(ax[1].get_yticklabels(), fontsize=6)
    # hide legend for first plot
    ax[0].get_legend().remove()
    ax[1].legend(title='Evaluation', bbox_to_anchor=(1.05, 1.02))
    # add horizontal space
    plt.tight_layout()
    ax
    # fig.suptitle(title, y = 1.02)
    img = addPlotImage(fig, 0.9)
    return img

uniquevals = [ 'Yes','No', 'NA']
# colors = {'Yes': 'blue', 'No': 'orange', 'Not assessed': 'lightgrey', 'Not relevant': 'green'}
colors = ['blue', 'orange', 'lightgrey']
def figToImage(fig):
    """Converts a Matplotlib figure to a PIL Image"""
    buf = BytesIO()
    fig.savefig(buf, format='png', bbox_inches='tight')
    buf.seek(0)
    return PIL.Image.open(buf)

def getEvalCounts(df, colGeneralEval, checklist, item):
    # create df for evaluation counts for each column
    evalcountDf = pd.DataFrame(columns = ['Question'] + uniquevals)
    for col in colGeneralEval:
        evalcount = df[col].value_counts()
        # remove ''
        evalcount = evalcount.drop('', errors='ignore')
        if len(evalcount) ==0:
            return None
        print(evalcount)
        qno = col.split('_')[-1]
        if qno in checklist[item]['fields']:
            fulltext = checklist[item]['fields'][qno]
        else:
            fulltext = 'Not Found'
        evalcountDf = pd.concat([evalcountDf, pd.DataFrame({'Question': [qno],
                                                             **evalcount.to_dict()})])
    evalcountDf.fillna(0, inplace=True)
    # sort by the total sum of the columns
    evalcountDf['sum'] = evalcountDf[uniquevals].sum(axis=1)
    evalcountDf = evalcountDf.sort_values('sum', ascending=False)
    # remove rows with sum = 0
    evalcountDf = evalcountDf[evalcountDf['sum'] != 0]
    evalcountDf.drop('sum', axis=1, inplace=True)
    # sort by question where question is MC\d+ use the digit
    evalcountDf['Question Num'] = evalcountDf['Question'].str.extract(r'(\d+)', expand=False).astype(int)
    evalcountDf = evalcountDf.sort_values('Question Num')
    evalcountDf.drop('Question Num', axis=1, inplace=True)
    # if max value is less than 2 then return None
    if evalcountDf[uniquevals].max().max() < 2:
        return None
    # evalcountDf = evalcountDf.head(15)
    return evalcountDf

# create stacked bar chart for general evaluation counts
def createStackedBarChart(df, title, plotCol):
    fig, ax = plt.subplots(figsize=(figSize[0]*0.6, figSize[1]*0.8))
    plotdf = df.set_index(plotCol)
    plotdf = plotdf.loc[::-1]  # Reverse the order of bars
    if len(plotdf) == 0:
        return None
    # remove rows with all zeros
    plotdf = plotdf.loc[(plotdf!=0).any(axis=1)]
    
    plotdf.plot(kind='barh', stacked=True, ax=ax, color=colors)
    ax.set_title(title)
    ax.set_xlabel('Questions')
    ax.set_ylabel('Counts')
    ax.set_xticklabels(ax.get_xticklabels(), rotation=0, fontsize=8)
    ax.legend(loc='center left', bbox_to_anchor=(0.5, 1.1))
    plt.tight_layout()
    return fig

In [ ]:
# overall report
df.replace({'nan': 'NA', 'Not Assessed': "NA", "Not Reviewed": "NA"}, inplace=True)
elements = []

elements.append(Paragraph(f'Overall Report', headingStyle))
elements.append(Spacer(1, 24))
def getFrontTable(df):
    nforms = len(df)
    typecounts = df['type'].value_counts()
    entrustmentcounts = df['entrustment'].value_counts().drop('', errors='ignore')
    entrustmentcounts = entrustmentcounts.sort_index()
    # item counts
    allitems = []
    for idx, row in df.iterrows():
        allitems.extend(row['Items'])
    counts = pd.Series(allitems).value_counts()
    itemcounts = counts.to_dict()

    # create a table for the counts
    countdf = pd.DataFrame(columns = ['Metric', 'Value'])
    countdf = pd.concat([countdf, pd.DataFrame({'Metric': ['Number of Forms'], 'Value': [nforms]})])
    typecountText = '<br/> '.join([f'{key}: {value}' for key, value in typecounts.items()])
    # countdf = pd.concat([countdf, pd.DataFrame({'Metric': ['Type Counts'], 'Value': [typecountText]})])
    entrustmentText = '<br/> '.join([f'{int(key)}: {value}' for key, value in entrustmentcounts.items()])
    itemcountText = '<br/> '.join([f'{key}: {value}' for key, value in itemcounts.items()])
    countdf = pd.concat([countdf, pd.DataFrame({'Metric': ['Entrustment Counts'], 'Value': [entrustmentText]})])
    countdf = pd.concat([countdf, pd.DataFrame({'Metric': ['Item Counts'], 'Value': [itemcountText]})])
    countTable = createTable(countdf, 'Summary Table', colRatio=[3, 1], customTextCols=[0, 1], tableTextStyle=tableTextStyleLarge)
    return countTable

# create a student name and items table
studentItemDf = df[[colId, 'Items']]
#aggregate items with combining the item lists
studentItemDf = studentItemDf.groupby(colId).agg({'Items': 'sum'}).reset_index()

studentItemDf['Items'] = studentItemDf['Items'].apply(lambda x: list(set(x)))
studentItemDf['Items'] = studentItemDf['Items'].apply(lambda x: ', '.join(x))
studentItemDf = studentItemDf.sort_values(colId)
# studentItemTable = createTable(studentItemDf, 'Student Items Table', colRatio=[2, 2], customTextCols=[0, 1], tableTextStyle=tableTextStyleLarge)
# elements.append(studentItemTable)
# elements.append(Spacer(1, 128))
# elements.append(PageBreak())

# get all the items
validType = 'Clinic' # 'Simulation' or 'Clinic'
for type_ in df['type'].unique():
    print(type_)
    if validType is not None and type_ != validType:
        continue
    thisdf = df[df['type'] == type_]
    fronttable = getFrontTable(thisdf)
    elements.append(fronttable)
    elements.append(PageBreak())
    allitems = []
    for idx, row in thisdf.iterrows():
        allitems.extend(row['Items'])
    allitems = list(set(allitems))
    elements.append(Paragraph(f'{type_}', subheadingStyle))
    elements.append(Spacer(1, 12))
    checklist = simChecklist if type_ == 'Simulation' else clinicChecklist
    # create stackec bar chart of value counts for each column for ech item
    for item in allitems:
        if item not in checklist:
            continue
        print(item, checklist[item]['name'])

        stuCols = [col for col in studentmcCols if item in col]
        supCols = [col for col in assessormcCols if item in col]

        itemdf = getYesNo(thisdf, stuCols, supCols)
        imgstuEval = plotStackedYesNo(itemdf, colId, item)
        
        
        evalcountDfStu = getEvalCounts(thisdf, stuCols, checklist, item)
        evalcountDfSup = getEvalCounts(thisdf, supCols, checklist, item)
        if evalcountDfStu is None or evalcountDfSup is None:
            continue
        # display(evalcountDf.head())
        figStu = createStackedBarChart(evalcountDfStu, 'Student', 'Question')
        figSup = createStackedBarChart(evalcountDfSup, 'Supervisor', 'Question')
        if figStu is None or figSup is None:
            continue
        imgSup = figToImage(figSup)
        imgStu = figToImage(figStu)
        fig, axes = plt.subplots(1, 2, figsize=(figSize[0], figSize[1]))
        axes[0].imshow(imgStu)
        axes[0].axis('off')
        axes[1].imshow(imgSup)
        axes[1].axis('off')
        plt.tight_layout()
        
        img = addPlotImage(fig, 0.85)
        # elements.append(Paragraph(f'{item}: {checklist[item]["name"]}', subsubheadingStyle))
        # elements.append(Spacer(1, 12))
        if imgstuEval is not None:
            elements.append(Paragraph(f'{item}: {checklist[item]["name"]}', subsubheadingStyle))
            elements.append(Spacer(1, 12))
            elements.append(imgstuEval)
            elements.append(PageBreak())
        # elements.append(Spacer(1, 24))
        elements.append(Paragraph('Question wise evaluation', subsubheadingStyle))
        elements.append(img)
        # create a full text reference table
        fulltextdf = pd.DataFrame(columns = ['Question', 'Full Text'])
        for qno, text in checklist[item]['fields'].items():
            fulltextdf = pd.concat([fulltextdf, pd.DataFrame({'Question': [qno], 'Full Text': [text]})])
        fulltextdf['Question Num'] = fulltextdf['Question'].str.extract(r'(\d+)', expand=False).astype(int)
        fulltextdf = fulltextdf.sort_values('Question Num')
        fulltextdf.drop('Question Num', axis=1, inplace=True)
        toppadding = 6
        bottompadding = 6
        if len(fulltextdf) > 10:
            toppadding = 3
            bottompadding = 3
        fulltextTable = createTable(fulltextdf, 'MC Reference Table', colRatio=[1, 3], customTextCols=[0, 1], tableTextStyle=tableTextStyleSmall,
                                    tableWidth=0.9, topPadding=toppadding, bottomPadding=bottompadding)
        elements.append(fulltextTable)
        elements.append(PageBreak())

doc = SimpleDocTemplate(f'{folder}\\Overall Report Student Eval {validType}.pdf', pagesize= pageSize, leftMargin = leftMargin,
                        rightMargin = rightMargin, topMargin = topMargin, bottomMargin = bottomMargin)
doc.build(elements)